import {Router} from 'express';
import sharp from 'sharp';
import fs from 'fs/promises';
import path from 'path';
import {query} from '../../config/db.js';
import {asyncHandler} from '../../utils/asyncHandler.js';
import {mediaUpload} from '../../middleware/upload.js';
import {sanitizeRichHtml} from '../../utils/richText.js';
import {slugify} from '../../utils/slug.js';
import {audit} from '../../utils/audit.js';
import {requirePermission} from '../../middleware/admin.js';

const r=Router();
const bool=v=>v===true||v===1||v==='1'||v==='true'||v==='on';
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function uniqueSlug(table,value,excludeId=null){const base=slugify(value),params=[];let candidate=base,n=2;while(true){const row=(await query(`SELECT id FROM ${table} WHERE slug=?${excludeId?' AND id<>?':''} LIMIT 1`,excludeId?[candidate,excludeId]:[candidate]))[0];if(!row)return candidate;candidate=`${base}-${n++}`}}
async function saveMedia(file){if(!file)return null;const out=file.path.replace(/(\.[^.]+)$/,'-optimized.webp');await sharp(file.path).rotate().resize({width:2000,height:1400,fit:'inside',withoutEnlargement:true}).webp({quality:86}).toFile(out);await fs.unlink(file.path).catch(()=>{});return '/uploads/media/'+path.basename(out)}

r.get('/banners',requirePermission('content.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM banners ORDER BY position,sort_order,id DESC')})));
r.post('/banners',requirePermission('content.manage'),mediaUpload.fields([{name:'image',maxCount:1},{name:'mobileImage',maxCount:1}]),asyncHandler(async(req,res)=>{const image=await saveMedia(req.files?.image?.[0]),mobile=await saveMedia(req.files?.mobileImage?.[0]);const x=await query('INSERT INTO banners(title,subtitle,content,button_text,button_url,image,mobile_image,position,sort_order,start_at,end_at,is_active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[req.body.title||'',sanitizeRichHtml(req.body.subtitle||''),sanitizeRichHtml(req.body.content||''),req.body.buttonText||'',req.body.buttonUrl||'',image,mobile,req.body.position||'hero',num(req.body.sortOrder),req.body.startAt||null,req.body.endAt||null,req.body.active===undefined?1:(bool(req.body.active)?1:0)]);await audit(req,'create','banner',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/banners/:id',requirePermission('content.manage'),mediaUpload.fields([{name:'image',maxCount:1},{name:'mobileImage',maxCount:1}]),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM banners WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Banner not found'});const image=req.files?.image?.[0]?await saveMedia(req.files.image[0]):(req.body.image??old.image);const mobile=req.files?.mobileImage?.[0]?await saveMedia(req.files.mobileImage[0]):(req.body.mobileImage??old.mobile_image);await query('UPDATE banners SET title=?,subtitle=?,content=?,button_text=?,button_url=?,image=?,mobile_image=?,position=?,sort_order=?,start_at=?,end_at=?,is_active=? WHERE id=?',[req.body.title??old.title,sanitizeRichHtml(req.body.subtitle??old.subtitle??''),sanitizeRichHtml(req.body.content??old.content??''),req.body.buttonText??old.button_text,req.body.buttonUrl??old.button_url,image,mobile,req.body.position??old.position,num(req.body.sortOrder??old.sort_order),req.body.startAt??old.start_at,req.body.endAt??old.end_at,bool(req.body.active??old.is_active)?1:0,req.params.id]);await audit(req,'update','banner',req.params.id,old,req.body);res.json({success:true})}));
r.delete('/banners/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{await query('DELETE FROM banners WHERE id=?',[req.params.id]);await audit(req,'delete','banner',req.params.id);res.json({success:true})}));

r.get('/services',requirePermission('content.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM services ORDER BY sort_order,id')})));
r.post('/services',requirePermission('content.manage'),mediaUpload.single('image'),asyncHandler(async(req,res)=>{const slug=await uniqueSlug('services',req.body.slug||req.body.name);const image=await saveMedia(req.file);const x=await query('INSERT INTO services(name,slug,description,icon,image,price,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?)',[req.body.name,slug,sanitizeRichHtml(req.body.description||''),req.body.icon||'HeartPulse',image,num(req.body.price),num(req.body.sortOrder),req.body.active===undefined?1:(bool(req.body.active)?1:0)]);await audit(req,'create','service',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/services/:id',requirePermission('content.manage'),mediaUpload.single('image'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM services WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Service not found'});const slug=await uniqueSlug('services',req.body.slug||old.slug||req.body.name||old.name,req.params.id),image=req.file?await saveMedia(req.file):(req.body.image??old.image);await query('UPDATE services SET name=?,slug=?,description=?,icon=?,image=?,price=?,sort_order=?,is_active=? WHERE id=?',[req.body.name??old.name,slug,sanitizeRichHtml(req.body.description??old.description??''),req.body.icon??old.icon,image,num(req.body.price??old.price),num(req.body.sortOrder??old.sort_order),bool(req.body.active??old.is_active)?1:0,req.params.id]);await audit(req,'update','service',req.params.id,old,req.body);res.json({success:true})}));
r.delete('/services/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{await query('UPDATE services SET is_active=0 WHERE id=?',[req.params.id]);res.json({success:true})}));

r.get('/coupons',requirePermission('marketing.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM coupons ORDER BY id DESC')})));
r.post('/coupons',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{const d=req.body;const x=await query('INSERT INTO coupons(code,name,description,discount_type,value,minimum_order,maximum_discount,start_date,end_date,usage_limit,usage_per_user,is_active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[String(d.code||'').toUpperCase().trim(),d.name||'',sanitizeRichHtml(d.description||''),d.discountType||'percentage',num(d.value),num(d.minimumOrder),d.maximumDiscount===''||d.maximumDiscount==null?null:num(d.maximumDiscount),d.startDate,d.endDate,d.usageLimit===''||d.usageLimit==null?null:num(d.usageLimit),num(d.usagePerUser,1),d.active===undefined?1:(bool(d.active)?1:0)]);await audit(req,'create','coupon',x.insertId,null,d);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/coupons/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM coupons WHERE id=?',[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Coupon not found'});const d=req.body;await query('UPDATE coupons SET code=?,name=?,description=?,discount_type=?,value=?,minimum_order=?,maximum_discount=?,start_date=?,end_date=?,usage_limit=?,usage_per_user=?,is_active=? WHERE id=?',[String(d.code??o.code).toUpperCase().trim(),d.name??o.name,sanitizeRichHtml(d.description??o.description??''),d.discountType??o.discount_type,num(d.value??o.value),num(d.minimumOrder??o.minimum_order),d.maximumDiscount===''?null:num(d.maximumDiscount??o.maximum_discount),d.startDate??o.start_date,d.endDate??o.end_date,d.usageLimit===''?null:num(d.usageLimit??o.usage_limit),num(d.usagePerUser??o.usage_per_user,1),bool(d.active??o.is_active)?1:0,req.params.id]);await audit(req,'update','coupon',req.params.id,o,d);res.json({success:true})}));
r.delete('/coupons/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{await query('UPDATE coupons SET is_active=0 WHERE id=?',[req.params.id]);res.json({success:true})}));

r.get('/pages',requirePermission('content.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM cms_pages ORDER BY title')})));
r.post('/pages',requirePermission('content.manage'),asyncHandler(async(req,res)=>{const slug=await uniqueSlug('cms_pages',req.body.slug||req.body.title);const x=await query('INSERT INTO cms_pages(slug,title,content,seo_title,seo_description,is_active) VALUES(?,?,?,?,?,?)',[slug,req.body.title,sanitizeRichHtml(req.body.content||''),req.body.seoTitle||'',req.body.seoDescription||'',req.body.active===undefined?1:(bool(req.body.active)?1:0)]);await audit(req,'create','cms_page',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/pages/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM cms_pages WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Page not found'});const slug=await uniqueSlug('cms_pages',req.body.slug||old.slug||req.body.title||old.title,req.params.id);await query('UPDATE cms_pages SET slug=?,title=?,content=?,seo_title=?,seo_description=?,is_active=? WHERE id=?',[slug,req.body.title??old.title,sanitizeRichHtml(req.body.content??old.content??''),req.body.seoTitle??old.seo_title,req.body.seoDescription??old.seo_description,bool(req.body.active??old.is_active)?1:0,req.params.id]);await audit(req,'update','cms_page',req.params.id,old,req.body);res.json({success:true})}));
r.delete('/pages/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{await query('UPDATE cms_pages SET is_active=0 WHERE id=?',[req.params.id]);res.json({success:true})}));

r.get('/homepage-sections',requirePermission('content.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM homepage_sections ORDER BY sort_order,id')})));
r.patch('/homepage-sections/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM homepage_sections WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Section not found'});await query('UPDATE homepage_sections SET title=?,subtitle=?,is_enabled=?,sort_order=?,config_json=? WHERE id=?',[req.body.title??old.title,sanitizeRichHtml(req.body.subtitle??old.subtitle??''),bool(req.body.enabled??old.is_enabled)?1:0,num(req.body.sortOrder??old.sort_order),req.body.configJson?JSON.stringify(req.body.configJson):old.config_json,req.params.id]);await audit(req,'update','homepage_section',req.params.id,old,req.body);res.json({success:true})}));
r.post('/homepage-sections/reorder',requirePermission('content.manage'),asyncHandler(async(req,res)=>{for(const item of req.body.items||[])await query('UPDATE homepage_sections SET sort_order=? WHERE id=?',[num(item.sortOrder),item.id]);await audit(req,'reorder','homepage_sections',null,null,req.body);res.json({success:true})}));


r.get('/navigation',requirePermission('content.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT n.*,p.label parent_label FROM navigation_items n LEFT JOIN navigation_items p ON p.id=n.parent_id ORDER BY FIELD(n.location,'header','footer_company','footer_shop','footer_help','footer_legal'),n.sort_order,n.id`)})));
r.post('/navigation',requirePermission('content.manage'),asyncHandler(async(req,res)=>{const d=req.body;if(!String(d.label||'').trim()||!String(d.url||'').trim())return res.status(400).json({success:false,message:'Label and URL are required'});const locations=['header','footer_company','footer_shop','footer_help','footer_legal'];const location=locations.includes(d.location)?d.location:'header';const x=await query('INSERT INTO navigation_items(label,url,location,parent_id,open_new_tab,sort_order,is_active) VALUES(?,?,?,?,?,?,?)',[String(d.label).trim(),String(d.url).trim(),location,d.parentId||null,bool(d.openNewTab)?1:0,num(d.sortOrder),d.active===undefined?1:(bool(d.active)?1:0)]);await audit(req,'create','navigation_item',x.insertId,null,d);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/navigation/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM navigation_items WHERE id=?',[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Navigation item not found'});const d=req.body,locations=['header','footer_company','footer_shop','footer_help','footer_legal'];const location=locations.includes(d.location)?d.location:o.location;const parent=d.parentId===undefined?o.parent_id:(d.parentId||null);if(+parent===+req.params.id)return res.status(400).json({success:false,message:'A navigation item cannot be its own parent'});await query('UPDATE navigation_items SET label=?,url=?,location=?,parent_id=?,open_new_tab=?,sort_order=?,is_active=? WHERE id=?',[d.label??o.label,d.url??o.url,location,parent,bool(d.openNewTab??o.open_new_tab)?1:0,num(d.sortOrder??o.sort_order),bool(d.active??o.is_active)?1:0,req.params.id]);await audit(req,'update','navigation_item',req.params.id,o,d);res.json({success:true})}));
r.delete('/navigation/:id',requirePermission('content.manage'),asyncHandler(async(req,res)=>{await query('DELETE FROM navigation_items WHERE id=?',[req.params.id]);await audit(req,'delete','navigation_item',req.params.id);res.json({success:true})}));

r.get('/newsletter',requirePermission('marketing.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM newsletter_subscribers ORDER BY id DESC LIMIT 1000')})));
r.patch('/newsletter/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{await query('UPDATE newsletter_subscribers SET is_active=? WHERE id=?',[bool(req.body.active)?1:0,req.params.id]);res.json({success:true})}));
r.delete('/newsletter/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{await query('DELETE FROM newsletter_subscribers WHERE id=?',[req.params.id]);res.json({success:true})}));

r.get('/contact-messages',requirePermission('support.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM contact_messages ORDER BY id DESC LIMIT 500')})));
r.patch('/contact-messages/:id',requirePermission('support.manage'),asyncHandler(async(req,res)=>{await query('UPDATE contact_messages SET status=?,admin_note=? WHERE id=?',[req.body.status||'new',req.body.adminNote||'',req.params.id]);await audit(req,'update','contact_message',req.params.id,null,req.body);res.json({success:true})}));
r.delete('/contact-messages/:id',requirePermission('support.manage'),asyncHandler(async(req,res)=>{await query('DELETE FROM contact_messages WHERE id=?',[req.params.id]);res.json({success:true})}));

r.post('/media',requirePermission('content.manage'),mediaUpload.single('file'),asyncHandler(async(req,res)=>{if(!req.file)return res.status(400).json({success:false,message:'Image file required'});const url=await saveMedia(req.file);res.status(201).json({success:true,data:{url}})}));

export default r;
