import {readSettings} from '../../services/integrationSettings.js';
import {Router} from 'express';
import {query} from '../../config/db.js';
import {asyncHandler} from '../../utils/asyncHandler.js';
import {requirePermission} from '../../middleware/admin.js';
import {sendMail,verifySmtp} from '../../services/mail.js';
import {mailboxName,verifyImap,listMailbox,getMessage,setSeen,deleteMessage,getAttachment} from '../../services/imap.js';
import {audit} from '../../utils/audit.js';
import {slugify} from '../../utils/slug.js';

const r=Router();
const b=v=>v===true||v===1||v==='1'||v==='true'||v==='on';

r.get('/mailbox-settings',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{const s=await readSettings('email');res.json({success:true,data:{senderName:s?.sender_name,senderEmail:s?.sender_email,smtpHost:s?.smtp_host,smtpPort:s?.smtp_port,imapHost:s?.imap_host||'',imapPort:s?.imap_port||993,passwordConfigured:Boolean(s?.password_configured)}})}));
r.post('/email-settings/test-smtp',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{await verifySmtp();res.json({success:true,message:'SMTP connected successfully'})}));
r.post('/email-settings/test-imap',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{await verifyImap();res.json({success:true,message:'IMAP connected successfully'})}));

r.get('/mailbox',requirePermission('support.view'),asyncHandler(async(req,res)=>{const data=await listMailbox({mailbox:await mailboxName(req.query.mailbox),page:Math.max(1,Number(req.query.page||1)),limit:Math.min(50,Math.max(10,Number(req.query.limit||30))),search:String(req.query.q||'').trim()});res.json({success:true,data})}));
r.get('/mailbox/:uid',requirePermission('support.view'),asyncHandler(async(req,res)=>{const m=await getMessage(req.params.uid,await mailboxName(req.query.mailbox));if(!m)return res.status(404).json({success:false,message:'Email not found'});res.json({success:true,data:m})}));
r.get('/mailbox/:uid/attachments/:index',requirePermission('support.view'),asyncHandler(async(req,res)=>{const a=await getAttachment(req.params.uid,req.params.index,await mailboxName(req.query.mailbox));if(!a)return res.status(404).json({success:false,message:'Attachment not found'});if(a.size>15*1024*1024)return res.status(413).json({success:false,message:'Attachment is too large'});res.type(a.contentType);res.setHeader('Content-Disposition',`attachment; filename="${String(a.filename).replace(/["\r\n]/g,'_')}"`);res.send(a.content)}));
r.patch('/mailbox/:uid/read',requirePermission('support.manage'),asyncHandler(async(req,res)=>{await setSeen(req.params.uid,b(req.body.read)!==false,await mailboxName(req.body.mailbox));res.json({success:true})}));
r.delete('/mailbox/:uid',requirePermission('support.manage'),asyncHandler(async(req,res)=>{await deleteMessage(req.params.uid,await mailboxName(req.query.mailbox));res.json({success:true})}));
r.post('/mailbox/send',requirePermission('support.manage'),asyncHandler(async(req,res)=>{const to=String(req.body.to||'').trim(),subject=String(req.body.subject||'').trim(),message=String(req.body.message||'').trim();if(!/^\S+@\S+\.\S+$/.test(to)||!subject||!message)return res.status(400).json({success:false,message:'Valid recipient, subject and message are required'});const info=await sendMail({to,subject,text:message,inReplyTo:req.body.inReplyTo||undefined,references:req.body.references||undefined});await audit(req,'send_email','mailbox',null,null,{to,subject,messageId:info.messageId});res.status(201).json({success:true,message:'Email sent',data:{messageId:info.messageId}})}));

r.post('/contact-messages/:id/reply',requirePermission('support.manage'),asyncHandler(async(req,res)=>{const m=(await query('SELECT * FROM contact_messages WHERE id=?',[req.params.id]))[0];if(!m)return res.status(404).json({success:false,message:'Message not found'});const text=String(req.body.message||'').trim();if(!text)return res.status(400).json({success:false,message:'Reply message is required'});const info=await sendMail({to:m.email,subject:`Re: ${m.subject||'Your Medico message'}`,text});await query('INSERT INTO contact_message_replies(contact_message_id,admin_id,message,recipient_email,smtp_message_id) VALUES(?,?,?,?,?)',[m.id,req.user.id,text,m.email,info.messageId||null]);await query("UPDATE contact_messages SET status='resolved',updated_at=NOW() WHERE id=?",[m.id]);res.status(201).json({success:true,message:'Reply sent'})}));
r.get('/contact-messages/:id/replies',requirePermission('support.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT id,message,recipient_email,created_at FROM contact_message_replies WHERE contact_message_id=? ORDER BY id',[req.params.id])})));

r.get('/email-templates',requirePermission('settings.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT template_key,subject,text_body,html_body,is_active,updated_at FROM email_templates ORDER BY template_key')})));
r.put('/email-templates/:key',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{const key=String(req.params.key||'').trim();const subject=String(req.body.subject||'').trim();const textBody=String(req.body.textBody||'');const htmlBody=req.body.htmlBody==null?null:String(req.body.htmlBody);if(!key||!subject)return res.status(400).json({success:false,message:'Template key and subject are required'});await query('INSERT INTO email_templates(template_key,subject,text_body,html_body,is_active) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE subject=VALUES(subject),text_body=VALUES(text_body),html_body=VALUES(html_body),is_active=VALUES(is_active)',[key,subject,textBody,htmlBody,b(req.body.active)?1:0]);await audit(req,'update','email_template',key,null,{subject,active:b(req.body.active)});res.json({success:true})}));

r.get('/offers',requirePermission('marketing.view'),asyncHandler(async(req,res)=>{const rows=await query(`SELECT o.*,GROUP_CONCAT(op.product_id ORDER BY op.product_id) product_ids FROM offers o LEFT JOIN offer_products op ON op.offer_id=o.id GROUP BY o.id ORDER BY o.sort_order,o.id DESC`);for(const x of rows)x.productIds=x.product_ids?x.product_ids.split(',').map(Number):[];res.json({success:true,data:rows})}));
r.post('/offers',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{const slug=slugify(req.body.slug||req.body.title);const x=await query('INSERT INTO offers(title,slug,description,discount_percent,banner_image,start_at,end_at,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?,?)',[req.body.title,slug,req.body.description||'',Number(req.body.discountPercent||0),req.body.bannerImage||null,req.body.startAt||null,req.body.endAt||null,Number(req.body.sortOrder||0),req.body.active===false?0:1]);for(const id of req.body.productIds||[])await query('INSERT IGNORE INTO offer_products(offer_id,product_id) VALUES(?,?)',[x.insertId,id]);await audit(req,'create','offer',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.put('/offers/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM offers WHERE id=?',[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Offer not found'});await query('UPDATE offers SET title=?,slug=?,description=?,discount_percent=?,banner_image=?,start_at=?,end_at=?,sort_order=?,is_active=? WHERE id=?',[req.body.title??o.title,slugify(req.body.slug||req.body.title||o.slug),req.body.description??o.description,Number(req.body.discountPercent??o.discount_percent),req.body.bannerImage??o.banner_image,req.body.startAt??o.start_at,req.body.endAt??o.end_at,Number(req.body.sortOrder??o.sort_order),req.body.active===undefined?o.is_active:(b(req.body.active)?1:0),o.id]);if(Array.isArray(req.body.productIds)){await query('DELETE FROM offer_products WHERE offer_id=?',[o.id]);for(const id of req.body.productIds)await query('INSERT IGNORE INTO offer_products(offer_id,product_id) VALUES(?,?)',[o.id,id])}await audit(req,'update','offer',o.id,o,req.body);res.json({success:true})}));
r.delete('/offers/:id',requirePermission('marketing.manage'),asyncHandler(async(req,res)=>{await query('UPDATE offers SET is_active=0 WHERE id=?',[req.params.id]);await audit(req,'disable','offer',req.params.id,null,null);res.json({success:true})}));

export default r;
