import {Router} from 'express';
import fs from 'fs';
import path from 'path';
import {query,pool} from '../../config/db.js';
import {uploadsRoot} from '../../config/paths.js';
import {asyncHandler} from '../../utils/asyncHandler.js';
import {audit} from '../../utils/audit.js';
import {requirePermission} from '../../middleware/admin.js';
import {getSettingsMap} from '../../services/settings.js';

const r=Router();
const bool=v=>v===true||v===1||v==='1'||v==='true'||v==='on';
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;

async function restoreCancelledOrderStock(conn,orderId){
  const [[done]]=await conn.query("SELECT id FROM inventory_movements WHERE reference_type='order' AND reference_id=? AND type='cancellation_restore' LIMIT 1",[orderId]);
  if(done)return;
  const [moves]=await conn.query("SELECT product_id,batch_id,quantity FROM inventory_movements WHERE reference_type='order' AND reference_id=? AND type='sale' AND batch_id IS NOT NULL",[orderId]);
  for(const m of moves){const restore=Math.abs(Number(m.quantity||0));if(!restore)continue;await conn.execute('UPDATE inventory_batches SET remaining_quantity=LEAST(quantity,remaining_quantity+?) WHERE id=?',[restore,m.batch_id]);await conn.execute('INSERT INTO inventory_movements(product_id,batch_id,type,quantity,reference_type,reference_id,note) VALUES(?,?,?,?,?,?,?)',[m.product_id,m.batch_id,'cancellation_restore',restore,'order',orderId,'Stock restored after order cancellation']);}
}

r.get('/dashboard',asyncHandler(async(req,res)=>{
  const [[orders],[revenue],[products],[low],[prescriptions],[customers],[returns],[outOfStock],[bookings]] = await Promise.all([
    query('SELECT COUNT(*) n FROM orders WHERE DATE(created_at)=CURDATE()'),
    query("SELECT COALESCE(SUM(total),0) n FROM orders WHERE DATE(created_at)=CURDATE() AND status<>'cancelled'"),
    query('SELECT COUNT(*) n FROM products WHERE is_active=1 AND deleted_at IS NULL'),
    query(`SELECT COUNT(*) n FROM products p WHERE p.deleted_at IS NULL AND p.is_active=1 AND (SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id)<=p.low_stock_threshold`),
    query("SELECT COUNT(*) n FROM prescriptions WHERE status IN ('uploaded','under_review')"),
    query('SELECT COUNT(*) n FROM users WHERE deleted_at IS NULL'),
    query("SELECT COUNT(*) n FROM returns WHERE status IN ('requested','approved','received')"),
    query(`SELECT COUNT(*) n FROM products p WHERE p.deleted_at IS NULL AND p.is_active=1 AND (SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id)=0`),
    query("SELECT COUNT(*) n FROM service_bookings WHERE status='pending'")
  ]);
  const [recentOrders,lowStock,expiring,sales]=await Promise.all([
    query(`SELECT o.id,o.order_number,o.total,o.status,o.payment_status,o.created_at,CONCAT(u.first_name,' ',u.last_name) customer FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 8`),
    query(`SELECT p.id,p.name,p.sku,p.low_stock_threshold,COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) stock FROM products p LEFT JOIN inventory_batches ib ON ib.product_id=p.id WHERE p.deleted_at IS NULL GROUP BY p.id HAVING stock<=p.low_stock_threshold ORDER BY stock LIMIT 8`),
    query(`SELECT ib.id,p.name,ib.batch_number,ib.expiry_date,ib.remaining_quantity FROM inventory_batches ib JOIN products p ON p.id=ib.product_id WHERE ib.remaining_quantity>0 AND ib.expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 90 DAY) ORDER BY ib.expiry_date LIMIT 8`),
    query("SELECT DATE(created_at) day,COUNT(*) orders,COALESCE(SUM(total),0) revenue FROM orders WHERE created_at>=DATE_SUB(CURDATE(),INTERVAL 6 DAY) AND status<>'cancelled' GROUP BY DATE(created_at) ORDER BY day")
  ]);
  res.json({success:true,data:{todayOrders:orders.n,todayRevenue:revenue.n,products:products.n,lowStock:low.n,pendingPrescriptions:prescriptions.n,customers:customers.n,pendingReturns:returns.n,outOfStock:outOfStock.n,pendingBookings:bookings.n,recentOrders,lowStockProducts:lowStock,expiringBatches:expiring,sales}});
}));

r.get('/orders',requirePermission('orders.view'),asyncHandler(async(req,res)=>{
  const {q='',status='',paymentStatus=''}=req.query;const where=['1=1'],p=[];
  if(q){where.push('(o.order_number LIKE ? OR u.first_name LIKE ? OR u.last_name LIKE ? OR u.phone LIKE ?)');p.push(`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`)}if(status){where.push('o.status=?');p.push(status)}if(paymentStatus){where.push('o.payment_status=?');p.push(paymentStatus)}
  res.json({success:true,data:await query(`SELECT o.id,o.order_number,o.total,o.subtotal,o.discount,o.shipping_fee,o.status,o.payment_status,o.payment_method,o.tracking_code,o.courier_name,o.created_at,CONCAT(u.first_name,' ',u.last_name) customer,u.email,u.phone FROM orders o JOIN users u ON u.id=o.user_id WHERE ${where.join(' AND ')} ORDER BY o.id DESC LIMIT 300`,p)});
}));

r.get('/orders/:id',requirePermission('orders.view'),asyncHandler(async(req,res)=>{const o=(await query(`SELECT o.*,CONCAT(u.first_name,' ',u.last_name) customer,u.email,u.phone FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?`,[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Order not found'});o.items=await query('SELECT * FROM order_items WHERE order_id=? ORDER BY id',[o.id]);o.history=await query(`SELECT h.*,CONCAT(u.first_name,' ',u.last_name) changed_by_name FROM order_status_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.order_id=? ORDER BY h.id`,[o.id]);res.json({success:true,data:o})}));
r.get('/orders/:id/invoice',requirePermission('orders.view'),asyncHandler(async(req,res)=>{const o=(await query(`SELECT o.*,CONCAT(u.first_name,' ',u.last_name) customer,u.email,u.phone FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?`,[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Invoice not found'});o.items=await query('SELECT * FROM order_items WHERE order_id=? ORDER BY id',[o.id]);const settings=await getSettingsMap();res.json({success:true,data:{order:o,settings}})}));

r.patch('/orders/:id',requirePermission('orders.update'),asyncHandler(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [[old]]=await conn.query('SELECT * FROM orders WHERE id=? FOR UPDATE',[req.params.id]);if(!old)throw Object.assign(new Error('Order not found'),{status:404});const allowed=['pending','prescription_review','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled','return_requested','returned','refund_pending','refunded'];const payment=['pending','processing','paid','failed','cancelled','refunded','partially_refunded'];const status=req.body.status??old.status;if(!allowed.includes(status))throw Object.assign(new Error('Invalid order status'),{status:400});if(old.status==='cancelled'&&status!=='cancelled')throw Object.assign(new Error('Cancelled orders cannot be reopened. Create a new order instead.'),{status:400});const ps=req.body.paymentStatus??old.payment_status;if(!payment.includes(ps))throw Object.assign(new Error('Invalid payment status'),{status:400});if(status==='cancelled'&&old.status!=='cancelled')await restoreCancelledOrderStock(conn,old.id);await conn.execute('UPDATE orders SET status=?,payment_status=?,admin_note=?,tracking_code=?,courier_name=?,updated_at=NOW() WHERE id=?',[status,ps,req.body.adminNote??old.admin_note,req.body.trackingCode??old.tracking_code,req.body.courierName??old.courier_name,req.params.id]);if(ps!==old.payment_status)await conn.execute('UPDATE payments SET status=? WHERE order_id=? ORDER BY id DESC LIMIT 1',[ps,req.params.id]);if(status!==old.status){await conn.execute('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[req.params.id,status,req.body.note||'',req.user.id]);await conn.execute('INSERT INTO notifications(user_id,type,title,message) VALUES(?,?,?,?)',[old.user_id,'order_status','Order status updated',`Your order ${old.order_number} is now ${String(status).replaceAll('_',' ')}.`]);}await conn.commit();await audit(req,'update','order',req.params.id,old,req.body);res.json({success:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
r.patch('/orders/:id/status',requirePermission('orders.update'),asyncHandler(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [[old]]=await conn.query('SELECT * FROM orders WHERE id=? FOR UPDATE',[req.params.id]);if(!old)throw Object.assign(new Error('Order not found'),{status:404});const allowed=['pending','prescription_review','confirmed','processing','packed','shipped','out_for_delivery','delivered','cancelled','return_requested','returned','refund_pending','refunded'];if(!allowed.includes(req.body.status))throw Object.assign(new Error('Invalid status'),{status:400});if(old.status==='cancelled'&&req.body.status!=='cancelled')throw Object.assign(new Error('Cancelled orders cannot be reopened.'),{status:400});if(req.body.status==='cancelled'&&old.status!=='cancelled')await restoreCancelledOrderStock(conn,old.id);await conn.execute('UPDATE orders SET status=?,updated_at=NOW() WHERE id=?',[req.body.status,req.params.id]);if(req.body.status!==old.status){await conn.execute('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[req.params.id,req.body.status,req.body.note||'',req.user.id]);await conn.execute('INSERT INTO notifications(user_id,type,title,message) VALUES(?,?,?,?)',[old.user_id,'order_status','Order status updated',`Your order ${old.order_number} is now ${String(req.body.status).replaceAll('_',' ')}.`]);}await conn.commit();await audit(req,'status_change','order',req.params.id,{status:old.status},{status:req.body.status});res.json({success:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
r.get('/inventory',requirePermission('inventory.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT p.id,p.name,p.sku,p.low_stock_threshold,COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) stock,MIN(CASE WHEN ib.remaining_quantity>0 AND ib.expiry_date>CURDATE() THEN ib.expiry_date END) nearest_expiry FROM products p LEFT JOIN inventory_batches ib ON ib.product_id=p.id WHERE p.deleted_at IS NULL GROUP BY p.id ORDER BY stock ASC,p.name LIMIT 500`)})));

r.get('/inventory/batches',requirePermission('inventory.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT ib.*,p.name product_name,p.sku,s.name supplier_name,CASE WHEN ib.expiry_date<CURDATE() THEN 'expired' WHEN ib.expiry_date<=DATE_ADD(CURDATE(),INTERVAL 90 DAY) THEN 'expiring' ELSE 'good' END expiry_status FROM inventory_batches ib JOIN products p ON p.id=ib.product_id LEFT JOIN suppliers s ON s.id=ib.supplier_id ORDER BY ib.expiry_date ASC,ib.id DESC LIMIT 500`)})));

r.post('/inventory/batches',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const d=req.body;const qty=Math.round(num(d.quantity));if(qty<=0)return res.status(400).json({success:false,message:'Quantity must be greater than zero'});if(!d.expiryDate)return res.status(400).json({success:false,message:'Expiry date is required'});const x=await query('INSERT INTO inventory_batches(product_id,supplier_id,batch_number,manufacturing_date,expiry_date,purchase_price,selling_price,quantity,remaining_quantity) VALUES(?,?,?,?,?,?,?,?,?)',[d.productId,d.supplierId||null,d.batchNumber,d.manufacturingDate||null,d.expiryDate,num(d.purchasePrice),d.sellingPrice===''||d.sellingPrice==null?null:num(d.sellingPrice),qty,qty]);await query('INSERT INTO inventory_movements(product_id,batch_id,type,quantity,reference_type,note) VALUES(?,?,?,?,?,?)',[d.productId,x.insertId,'stock_in',qty,'batch',d.note||'Stock received']);await audit(req,'stock_in','inventory_batch',x.insertId,null,d);res.status(201).json({success:true,data:{id:x.insertId}})}));

r.post('/inventory/batches/:id/adjust',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [[b]]=await conn.query('SELECT * FROM inventory_batches WHERE id=? FOR UPDATE',[req.params.id]);if(!b)throw Object.assign(new Error('Batch not found'),{status:404});const change=Math.round(num(req.body.change));if(!change)throw Object.assign(new Error('Adjustment cannot be zero'),{status:400});if(b.remaining_quantity+change<0)throw Object.assign(new Error('Stock cannot become negative'),{status:400});await conn.execute('UPDATE inventory_batches SET remaining_quantity=remaining_quantity+? WHERE id=?',[change,b.id]);await conn.execute('INSERT INTO inventory_movements(product_id,batch_id,type,quantity,reference_type,note) VALUES(?,?,?,?,?,?)',[b.product_id,b.id,'adjustment',change,'admin',req.body.note||'Manual stock adjustment']);await conn.commit();await audit(req,'adjust_stock','inventory_batch',b.id,{remaining:b.remaining_quantity},{change});res.json({success:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

r.get('/inventory/movements',requirePermission('inventory.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT im.*,p.name product_name,p.sku,ib.batch_number FROM inventory_movements im JOIN products p ON p.id=im.product_id LEFT JOIN inventory_batches ib ON ib.id=im.batch_id ORDER BY im.id DESC LIMIT 500`)})));

r.get('/suppliers',requirePermission('inventory.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM suppliers ORDER BY id DESC')})));
r.post('/suppliers',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const x=await query('INSERT INTO suppliers(name,company,phone,email,address,notes,is_active) VALUES(?,?,?,?,?,?,?)',[req.body.name,req.body.company||'',req.body.phone||'',req.body.email||'',req.body.address||'',req.body.notes||'',req.body.active===false?0:1]);await audit(req,'create','supplier',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/suppliers/:id',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM suppliers WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Supplier not found'});await query('UPDATE suppliers SET name=?,company=?,phone=?,email=?,address=?,notes=?,is_active=? WHERE id=?',[req.body.name??old.name,req.body.company??old.company,req.body.phone??old.phone,req.body.email??old.email,req.body.address??old.address,req.body.notes??old.notes,bool(req.body.active??old.is_active)?1:0,req.params.id]);await audit(req,'update','supplier',req.params.id,old,req.body);res.json({success:true})}));
r.delete('/suppliers/:id',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{await query('UPDATE suppliers SET is_active=0 WHERE id=?',[req.params.id]);res.json({success:true})}));



r.get('/purchase-orders',requirePermission('inventory.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT po.*,s.name supplier_name,CONCAT(u.first_name,' ',u.last_name) created_by_name,COUNT(poi.id) item_count,COALESCE(SUM(poi.received_quantity),0) received_units,COALESCE(SUM(poi.quantity),0) ordered_units FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN users u ON u.id=po.created_by LEFT JOIN purchase_order_items poi ON poi.purchase_order_id=po.id GROUP BY po.id ORDER BY po.id DESC LIMIT 300`)})));

r.get('/purchase-orders/:id',requirePermission('inventory.view'),asyncHandler(async(req,res)=>{const po=(await query(`SELECT po.*,s.name supplier_name,CONCAT(u.first_name,' ',u.last_name) created_by_name FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN users u ON u.id=po.created_by WHERE po.id=?`,[req.params.id]))[0];if(!po)return res.status(404).json({success:false,message:'Purchase order not found'});po.items=await query(`SELECT poi.*,p.name product_name,p.sku FROM purchase_order_items poi JOIN products p ON p.id=poi.product_id WHERE poi.purchase_order_id=? ORDER BY poi.id`,[po.id]);res.json({success:true,data:po})}));

r.post('/purchase-orders',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const d=req.body,items=Array.isArray(d.items)?d.items:[];if(!d.supplierId||!items.length)return res.status(400).json({success:false,message:'Supplier and at least one product are required'});const conn=await pool.getConnection();try{await conn.beginTransaction();const poNumber=`PO-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Date.now().toString().slice(-6)}`;let subtotal=0;for(const it of items){const qty=Math.round(num(it.quantity));const price=num(it.purchasePrice);if(!it.productId||qty<=0||price<0)throw Object.assign(new Error('Each purchase item needs a product, positive quantity and valid purchase price'),{status:400});subtotal+=qty*price}const [x]=await conn.execute('INSERT INTO purchase_orders(po_number,supplier_id,status,expected_date,subtotal,notes,created_by) VALUES(?,?,?,?,?,?,?)',[poNumber,d.supplierId,d.status||'ordered',d.expectedDate||null,subtotal,d.notes||'',req.user.id]);for(const it of items)await conn.execute('INSERT INTO purchase_order_items(purchase_order_id,product_id,quantity,purchase_price,batch_number,manufacturing_date,expiry_date) VALUES(?,?,?,?,?,?,?)',[x.insertId,it.productId,Math.round(num(it.quantity)),num(it.purchasePrice),it.batchNumber||null,it.manufacturingDate||null,it.expiryDate||null]);await conn.commit();await audit(req,'create','purchase_order',x.insertId,null,{poNumber,subtotal,itemCount:items.length});res.status(201).json({success:true,data:{id:x.insertId,poNumber}})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

r.patch('/purchase-orders/:id',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM purchase_orders WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Purchase order not found'});const status=['draft','ordered','partially_received','received','cancelled'].includes(req.body.status)?req.body.status:old.status;await query('UPDATE purchase_orders SET status=?,expected_date=?,notes=? WHERE id=?',[status,req.body.expectedDate??old.expected_date,req.body.notes??old.notes,req.params.id]);await audit(req,'update','purchase_order',req.params.id,old,req.body);res.json({success:true})}));

r.post('/purchase-orders/:id/receive',requirePermission('inventory.adjust'),asyncHandler(async(req,res)=>{const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({success:false,message:'Select at least one quantity to receive'});const conn=await pool.getConnection();try{await conn.beginTransaction();const [[po]]=await conn.query('SELECT * FROM purchase_orders WHERE id=? FOR UPDATE',[req.params.id]);if(!po)throw Object.assign(new Error('Purchase order not found'),{status:404});if(po.status==='cancelled')throw Object.assign(new Error('Cancelled purchase order cannot be received'),{status:400});for(const input of items){const qty=Math.round(num(input.receiveQuantity));if(qty<=0)continue;const [[it]]=await conn.query('SELECT * FROM purchase_order_items WHERE id=? AND purchase_order_id=? FOR UPDATE',[input.itemId,po.id]);if(!it)throw Object.assign(new Error('Purchase order item not found'),{status:404});const remaining=it.quantity-it.received_quantity;if(qty>remaining)throw Object.assign(new Error('Received quantity exceeds outstanding purchase quantity'),{status:400});const expiry=input.expiryDate||it.expiry_date;if(!expiry)throw Object.assign(new Error('Expiry date is required when receiving pharmacy inventory'),{status:400});const batch=input.batchNumber||it.batch_number||`${po.po_number}-${it.id}`;const [bx]=await conn.execute('INSERT INTO inventory_batches(product_id,supplier_id,batch_number,manufacturing_date,expiry_date,purchase_price,selling_price,quantity,remaining_quantity) VALUES(?,?,?,?,?,?,?,?,?)',[it.product_id,po.supplier_id,batch,input.manufacturingDate||it.manufacturing_date||null,expiry,it.purchase_price,input.sellingPrice===''||input.sellingPrice==null?null:num(input.sellingPrice),qty,qty]);await conn.execute('INSERT INTO inventory_movements(product_id,batch_id,type,quantity,reference_type,reference_id,note) VALUES(?,?,?,?,?,?,?)',[it.product_id,bx.insertId,'stock_in',qty,'purchase_order',po.id,`Received from ${po.po_number}`]);await conn.execute('UPDATE purchase_order_items SET received_quantity=received_quantity+?,batch_number=?,manufacturing_date=?,expiry_date=? WHERE id=?',[qty,batch,input.manufacturingDate||it.manufacturing_date||null,expiry,it.id])}const [[counts]]=await conn.query('SELECT COALESCE(SUM(quantity),0) ordered,COALESCE(SUM(received_quantity),0) received FROM purchase_order_items WHERE purchase_order_id=?',[po.id]);const status=Number(counts.received)>=Number(counts.ordered)?'received':'partially_received';await conn.execute("UPDATE purchase_orders SET status=?,received_at=IF(?='received',NOW(),received_at) WHERE id=?",[status,status,po.id]);await conn.commit();await audit(req,'receive','purchase_order',po.id,null,{status,items});res.json({success:true,message:'Inventory received',data:{status}})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));

r.get('/payments',requirePermission('orders.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT p.*,o.order_number,o.payment_method,o.payment_status,o.payment_sender_last4,o.payment_transaction_id,CONCAT(u.first_name,' ',u.last_name) customer,u.email,(SELECT COALESCE(SUM(amount),0) FROM refunds rf WHERE rf.payment_id=p.id AND rf.status='completed') refunded_amount FROM payments p JOIN orders o ON o.id=p.order_id JOIN users u ON u.id=o.user_id ORDER BY p.id DESC LIMIT 500`)})));

r.get('/refunds',requirePermission('orders.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT rf.*,o.order_number,p.provider,CONCAT(u.first_name,' ',u.last_name) customer,CONCAT(a.first_name,' ',a.last_name) processed_by_name FROM refunds rf JOIN orders o ON o.id=rf.order_id JOIN users u ON u.id=o.user_id LEFT JOIN payments p ON p.id=rf.payment_id LEFT JOIN users a ON a.id=rf.processed_by ORDER BY rf.id DESC LIMIT 500`)})));

r.post('/payments/:id/refund',requirePermission('orders.update'),asyncHandler(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [[p]]=await conn.query('SELECT * FROM payments WHERE id=? FOR UPDATE',[req.params.id]);if(!p)throw Object.assign(new Error('Payment not found'),{status:404});if(!['paid','partially_refunded'].includes(p.status))throw Object.assign(new Error('Only paid payments can be refunded'),{status:400});const [[sum]]=await conn.query("SELECT COALESCE(SUM(amount),0) n FROM refunds WHERE payment_id=? AND status='completed'",[p.id]);const available=Number(p.amount)-Number(sum.n||0);const amount=num(req.body.amount);if(amount<=0||amount>available)throw Object.assign(new Error(`Refund amount must be between 0 and ${available}`),{status:400});const status=amount>=available?'refunded':'partially_refunded';const ref=`RF-${Date.now()}`;const [x]=await conn.execute("INSERT INTO refunds(order_id,payment_id,amount,method,status,reference,note,processed_by) VALUES(?,?,?,?,?,?,?,?)",[p.order_id,p.id,amount,p.provider,'completed',ref,req.body.note||'',req.user.id]);await conn.execute('UPDATE payments SET status=? WHERE id=?',[status,p.id]);await conn.execute("UPDATE orders SET payment_status=?,status=IF(?='refunded','refunded',status) WHERE id=?",[status,status,p.order_id]);await conn.commit();await audit(req,'refund','payment',p.id,null,{refundId:x.insertId,amount,status});res.status(201).json({success:true,data:{id:x.insertId,reference:ref,status}})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
r.get('/prescriptions',requirePermission('prescriptions.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT p.*,CONCAT(u.first_name,' ',u.last_name) customer,u.email,u.phone,CONCAT(a.first_name,' ',a.last_name) reviewer FROM prescriptions p JOIN users u ON u.id=p.user_id LEFT JOIN users a ON a.id=p.reviewed_by ORDER BY p.id DESC LIMIT 300`)})));
r.get('/prescriptions/:id/file',requirePermission('prescriptions.view'),asyncHandler(async(req,res)=>{const p=(await query('SELECT file_path FROM prescriptions WHERE id=?',[req.params.id]))[0];if(!p)return res.status(404).json({success:false,message:'Prescription not found'});let fp=String(p.file_path||'').replaceAll('\\','/');if(fp.startsWith('uploads/'))fp=path.join(path.dirname(uploadsRoot),fp);else if(!path.isAbsolute(fp))fp=path.join(path.dirname(uploadsRoot),fp);if(!fs.existsSync(fp))return res.status(404).json({success:false,message:'Prescription file is missing'});res.sendFile(path.resolve(fp))}));
r.patch('/prescriptions/:id',requirePermission('prescriptions.review'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM prescriptions WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Prescription not found'});const status=['approved','rejected','under_review','expired'].includes(req.body.status)?req.body.status:'under_review';await query('UPDATE prescriptions SET status=?,admin_notes=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?',[status,req.body.adminNotes??old.admin_notes,req.user.id,req.params.id]);await audit(req,'review','prescription',req.params.id,old,{status,adminNotes:req.body.adminNotes});res.json({success:true})}));

r.get('/customers',requirePermission('customers.view'),asyncHandler(async(req,res)=>{const q=String(req.query.q||'');const p=q?`%${q}%`:null;const rows=await query(`SELECT u.id,u.first_name,u.last_name,u.email,u.phone,u.is_verified,u.is_active,u.created_at,COUNT(DISTINCT o.id) orders_count,COALESCE(SUM(o.total),0) lifetime_value FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.deleted_at IS NULL ${q?'AND (u.first_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ? OR u.phone LIKE ?)':''} GROUP BY u.id ORDER BY u.id DESC LIMIT 500`,q?[p,p,p,p]:[]);res.json({success:true,data:rows})}));
r.get('/customers/:id',requirePermission('customers.view'),asyncHandler(async(req,res)=>{const u=(await query('SELECT id,first_name,last_name,email,phone,is_verified,is_active,created_at FROM users WHERE id=?',[req.params.id]))[0];if(!u)return res.status(404).json({success:false,message:'Customer not found'});u.orders=await query('SELECT id,order_number,total,status,payment_status,created_at FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 50',[u.id]);u.addresses=await query('SELECT * FROM user_addresses WHERE user_id=?',[u.id]);u.prescriptions=await query('SELECT id,status,created_at FROM prescriptions WHERE user_id=? ORDER BY id DESC',[u.id]);res.json({success:true,data:u})}));
r.patch('/customers/:id',requirePermission('customers.update'),asyncHandler(async(req,res)=>{const old=(await query('SELECT id,is_active FROM users WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Customer not found'});await query('UPDATE users SET is_active=? WHERE id=?',[bool(req.body.active)?1:0,req.params.id]);await audit(req,'update_status','customer',req.params.id,old,{active:bool(req.body.active)});res.json({success:true})}));

r.get('/reviews',requirePermission('customers.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT r.*,p.name product_name,CONCAT(u.first_name,' ',u.last_name) customer FROM reviews r JOIN products p ON p.id=r.product_id JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 500`)})));
r.patch('/reviews/:id',requirePermission('customers.update'),asyncHandler(async(req,res)=>{const status=['approved','rejected','pending'].includes(req.body.status)?req.body.status:'pending';await query('UPDATE reviews SET status=? WHERE id=?',[status,req.params.id]);await query(`UPDATE products p SET rating_avg=COALESCE((SELECT AVG(rating) FROM reviews r WHERE r.product_id=p.id AND r.status='approved'),0),review_count=(SELECT COUNT(*) FROM reviews r WHERE r.product_id=p.id AND r.status='approved') WHERE p.id=(SELECT product_id FROM reviews WHERE id=?)`,[req.params.id]);await audit(req,'moderate','review',req.params.id,null,{status});res.json({success:true})}));
r.delete('/reviews/:id',requirePermission('customers.update'),asyncHandler(async(req,res)=>{const x=(await query('SELECT product_id FROM reviews WHERE id=?',[req.params.id]))[0];if(x){await query('DELETE FROM reviews WHERE id=?',[req.params.id]);await query(`UPDATE products SET rating_avg=COALESCE((SELECT AVG(rating) FROM reviews WHERE product_id=? AND status='approved'),0),review_count=(SELECT COUNT(*) FROM reviews WHERE product_id=? AND status='approved') WHERE id=?`,[x.product_id,x.product_id,x.product_id])}res.json({success:true})}));

r.get('/returns',requirePermission('orders.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT r.*,o.order_number,o.total,CONCAT(u.first_name,' ',u.last_name) customer,u.email FROM returns r JOIN orders o ON o.id=r.order_id JOIN users u ON u.id=r.user_id ORDER BY r.id DESC LIMIT 300`)})));
r.patch('/returns/:id',requirePermission('orders.update'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM returns WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Return not found'});const allowed=['requested','approved','rejected','received','refunded','closed'];const status=allowed.includes(req.body.status)?req.body.status:old.status;await query('UPDATE returns SET status=?,admin_note=?,refund_amount=? WHERE id=?',[status,req.body.adminNote??old.admin_note,num(req.body.refundAmount??old.refund_amount),req.params.id]);if(status==='refunded'){const amount=num(req.body.refundAmount??old.refund_amount);const payment=(await query('SELECT * FROM payments WHERE order_id=? ORDER BY id DESC LIMIT 1',[old.order_id]))[0];await query("UPDATE orders SET status='refunded',payment_status='refunded' WHERE id=?",[old.order_id]);if(payment){const exists=(await query("SELECT id FROM refunds WHERE return_id=? AND status='completed' LIMIT 1",[old.id]))[0];if(!exists&&amount>0){await query("INSERT INTO refunds(order_id,return_id,payment_id,amount,method,status,reference,note,processed_by) VALUES(?,?,?,?,?,'completed',?,?,?)",[old.order_id,old.id,payment.id,amount,payment.provider,`RF-${Date.now()}`,req.body.adminNote||'',req.user.id]);await query("UPDATE payments SET status='refunded' WHERE id=?",[payment.id])}}}await audit(req,'update','return',req.params.id,old,req.body);res.json({success:true})}));

r.get('/service-bookings',requirePermission('orders.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT b.*,s.name service_name,CONCAT(u.first_name,' ',u.last_name) customer,u.email FROM service_bookings b LEFT JOIN services s ON s.id=b.service_id LEFT JOIN users u ON u.id=b.user_id ORDER BY b.id DESC LIMIT 300`)})));
r.patch('/service-bookings/:id',requirePermission('orders.update'),asyncHandler(async(req,res)=>{await query('UPDATE service_bookings SET status=?,notes=? WHERE id=?',[req.body.status||'pending',req.body.notes||'',req.params.id]);await audit(req,'update','service_booking',req.params.id,null,req.body);res.json({success:true})}));

r.get('/reports/sales',requirePermission('reports.view'),asyncHandler(async(req,res)=>{const days=Math.min(365,Math.max(7,+req.query.days||30));res.json({success:true,data:await query("SELECT DATE(created_at) day,COUNT(*) orders,COALESCE(SUM(total),0) revenue,COALESCE(SUM(discount),0) discounts FROM orders WHERE status<>'cancelled' AND created_at>=DATE_SUB(CURDATE(),INTERVAL ? DAY) GROUP BY DATE(created_at) ORDER BY day DESC",[days])})}));
r.get('/reports/inventory',requirePermission('reports.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT p.id,p.name,p.sku,p.cost_price,p.sale_price,COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) stock,COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity*ib.purchase_price ELSE 0 END),0) stock_value FROM products p LEFT JOIN inventory_batches ib ON ib.product_id=p.id WHERE p.deleted_at IS NULL GROUP BY p.id ORDER BY stock_value DESC`)})));
r.get('/reports/customers',requirePermission('reports.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT u.id,CONCAT(u.first_name,' ',u.last_name) customer,u.email,COUNT(o.id) orders,COALESCE(SUM(o.total),0) spend FROM users u LEFT JOIN orders o ON o.user_id=u.id AND o.status<>'cancelled' WHERE u.deleted_at IS NULL GROUP BY u.id ORDER BY spend DESC LIMIT 500`)})));
r.get('/reports/prescriptions',requirePermission('reports.view'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT status,COUNT(*) total FROM prescriptions GROUP BY status ORDER BY total DESC`)})));

export default r;
