import {Router} from 'express';
import bcrypt from 'bcryptjs';
import {query} from '../../config/db.js';
import {asyncHandler} from '../../utils/asyncHandler.js';
import {audit} from '../../utils/audit.js';
import {sanitizeRichHtml} from '../../utils/richText.js';
import {getSettingsMap,setSettings} from '../../services/settings.js';
import {requirePermission} from '../../middleware/admin.js';

const r=Router();
const bool=v=>v===true||v===1||v==='1'||v==='true'||v==='on';
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;

r.get('/settings',requirePermission('settings.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await getSettingsMap()})));
r.put('/settings/:key',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{await setSettings({[req.params.key]:req.body.value??''});await audit(req,'update_setting','setting',null,null,{key:req.params.key,value:req.body.value});res.json({success:true})}));
r.put('/settings',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{const values={...(req.body.values||req.body)};if(values['admin.panel_slug']&&!/^[a-z0-9-]{3,50}$/i.test(values['admin.panel_slug']))return res.status(400).json({success:false,message:'Admin slug can only use letters, numbers and hyphens'});for(const key of ['footer.about','payment.bkash.instructions','payment.nagad.instructions'])if(values[key]!==undefined)values[key]=sanitizeRichHtml(values[key]);await setSettings(values);await audit(req,'bulk_update','settings',null,null,Object.keys(values));res.json({success:true,data:await getSettingsMap()})}));

r.get('/profile',asyncHandler(async(req,res)=>{const u=(await query('SELECT id,first_name,last_name,email,phone,is_active,created_at FROM users WHERE id=?',[req.user.id]))[0];const roles=await query('SELECT r.id,r.name FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=?',[req.user.id]);res.json({success:true,data:{...u,roles}})}));
r.put('/profile',asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM users WHERE id=?',[req.user.id]))[0];if(!old)return res.status(404).json({success:false,message:'Admin account not found'});const email=String(req.body.email??old.email).trim().toLowerCase(),phone=String(req.body.phone??old.phone).trim();const sensitive=email!==old.email||phone!==old.phone||Boolean(req.body.newPassword);if(sensitive){if(!req.body.currentPassword||!(await bcrypt.compare(req.body.currentPassword,old.password_hash)))return res.status(400).json({success:false,message:'Current password is required and must be correct'});}const exists=(await query('SELECT id FROM users WHERE (email=? OR phone=?) AND id<>?',[email,phone,req.user.id]))[0];if(exists)return res.status(409).json({success:false,message:'Email or phone is already used by another account'});let hash=old.password_hash;if(req.body.newPassword){if(String(req.body.newPassword).length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters'});hash=await bcrypt.hash(String(req.body.newPassword),12)}await query('UPDATE users SET first_name=?,last_name=?,email=?,phone=?,password_hash=?,updated_at=NOW() WHERE id=?',[req.body.firstName??old.first_name,req.body.lastName??old.last_name,email,phone,hash,req.user.id]);if(req.body.newPassword)await query('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=?',[req.user.id]);await audit(req,'update_profile','admin',req.user.id,{email:old.email,phone:old.phone},{email,phone,passwordChanged:Boolean(req.body.newPassword)});res.json({success:true,message:req.body.newPassword?'Profile and password updated. Please sign in again.':'Profile updated'})}));

r.get('/permissions',requirePermission('staff.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM permissions ORDER BY code')})));
r.get('/roles',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{const roles=await query(`SELECT r.id,r.name,r.description,r.is_active,GROUP_CONCAT(p.code ORDER BY p.code SEPARATOR ',') permission_codes FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id GROUP BY r.id ORDER BY r.id`);roles.forEach(x=>x.permissions=x.permission_codes?x.permission_codes.split(','):[]);res.json({success:true,data:roles})}));
r.post('/roles',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{const x=await query('INSERT INTO roles(name,description,is_active) VALUES(?,?,?)',[req.body.name,req.body.description||'',req.body.active===false?0:1]);for(const code of req.body.permissions||[]){const p=(await query('SELECT id FROM permissions WHERE code=?',[code]))[0];if(p)await query('INSERT IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)',[x.insertId,p.id])}await audit(req,'create','role',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/roles/:id',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{const old=(await query('SELECT * FROM roles WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Role not found'});if(old.name==='Super Admin'&&req.body.active===false)return res.status(400).json({success:false,message:'Super Admin role cannot be disabled'});await query('UPDATE roles SET name=?,description=?,is_active=? WHERE id=?',[req.body.name??old.name,req.body.description??old.description,bool(req.body.active??old.is_active)?1:0,req.params.id]);if(Array.isArray(req.body.permissions)){await query('DELETE FROM role_permissions WHERE role_id=?',[req.params.id]);for(const code of req.body.permissions){const p=(await query('SELECT id FROM permissions WHERE code=?',[code]))[0];if(p)await query('INSERT IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)',[req.params.id,p.id])}}await audit(req,'update','role',req.params.id,old,req.body);res.json({success:true})}));

r.get('/staff',requirePermission('staff.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT u.id,u.first_name,u.last_name,u.email,u.phone,u.is_active,u.created_at,r.id role_id,r.name role_name FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.deleted_at IS NULL ORDER BY u.id DESC`)})));
r.post('/staff',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{const d=req.body;if(!d.email||!d.phone||!d.password||String(d.password).length<8)return res.status(400).json({success:false,message:'Name, email, phone and password (8+ chars) are required'});if((await query('SELECT id FROM users WHERE email=? OR phone=?',[String(d.email).toLowerCase(),d.phone]))[0])return res.status(409).json({success:false,message:'Email or phone already exists'});const hash=await bcrypt.hash(String(d.password),12);const x=await query('INSERT INTO users(first_name,last_name,email,phone,password_hash,is_verified,is_active) VALUES(?,?,?,?,?,1,?)',[d.firstName||'Staff',d.lastName||'User',String(d.email).toLowerCase(),d.phone,hash,d.active===false?0:1]);await query('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[x.insertId,d.roleId]);await audit(req,'create','staff',x.insertId,null,{...d,password:'[redacted]'});res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/staff/:id',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{if(+req.params.id===+req.user.id&&req.body.active===false)return res.status(400).json({success:false,message:'You cannot disable your own account'});const old=(await query('SELECT * FROM users WHERE id=?',[req.params.id]))[0];if(!old)return res.status(404).json({success:false,message:'Staff not found'});let hash=old.password_hash;if(req.body.password){if(String(req.body.password).length<8)return res.status(400).json({success:false,message:'Password must be at least 8 characters'});hash=await bcrypt.hash(String(req.body.password),12)}await query('UPDATE users SET first_name=?,last_name=?,email=?,phone=?,is_active=?,password_hash=? WHERE id=?',[req.body.firstName??old.first_name,req.body.lastName??old.last_name,String(req.body.email??old.email).toLowerCase(),req.body.phone??old.phone,bool(req.body.active??old.is_active)?1:0,hash,req.params.id]);if(req.body.roleId){await query('DELETE FROM user_roles WHERE user_id=?',[req.params.id]);await query('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[req.params.id,req.body.roleId])}await audit(req,'update','staff',req.params.id,{email:old.email},{...req.body,password:req.body.password?'[redacted]':undefined});res.json({success:true})}));
r.delete('/staff/:id',requirePermission('staff.manage'),asyncHandler(async(req,res)=>{if(+req.params.id===+req.user.id)return res.status(400).json({success:false,message:'You cannot disable your own account'});await query('UPDATE users SET is_active=0 WHERE id=?',[req.params.id]);await query('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=?',[req.params.id]);await audit(req,'disable','staff',req.params.id);res.json({success:true})}));

r.get('/shipping-zones',requirePermission('settings.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM shipping_zones ORDER BY sort_order,id')})));
r.post('/shipping-zones',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{const x=await query('INSERT INTO shipping_zones(name,division,district,fee,estimated_days,free_shipping_threshold,is_active,sort_order) VALUES(?,?,?,?,?,?,?,?)',[req.body.name,req.body.division||null,req.body.district||null,num(req.body.fee),req.body.estimatedDays||'',req.body.freeShippingThreshold===''?null:num(req.body.freeShippingThreshold),req.body.active===false?0:1,num(req.body.sortOrder)]);await audit(req,'create','shipping_zone',x.insertId,null,req.body);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/shipping-zones/:id',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM shipping_zones WHERE id=?',[req.params.id]))[0];if(!o)return res.status(404).json({success:false,message:'Shipping zone not found'});await query('UPDATE shipping_zones SET name=?,division=?,district=?,fee=?,estimated_days=?,free_shipping_threshold=?,is_active=?,sort_order=? WHERE id=?',[req.body.name??o.name,req.body.division??o.division,req.body.district??o.district,num(req.body.fee??o.fee),req.body.estimatedDays??o.estimated_days,req.body.freeShippingThreshold===''?null:num(req.body.freeShippingThreshold??o.free_shipping_threshold),bool(req.body.active??o.is_active)?1:0,num(req.body.sortOrder??o.sort_order),req.params.id]);res.json({success:true})}));
r.delete('/shipping-zones/:id',requirePermission('settings.manage'),asyncHandler(async(req,res)=>{await query('DELETE FROM shipping_zones WHERE id=?',[req.params.id]);res.json({success:true})}));

r.get('/audit-logs',requirePermission('staff.manage'),asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT a.*,CONCAT(u.first_name,' ',u.last_name) admin_name,u.email admin_email FROM audit_logs a LEFT JOIN users u ON u.id=a.admin_id ORDER BY a.id DESC LIMIT 500`)})));

export default r;
