import PaymentResult from './pages/PaymentResult';
import IntegrationSettings,{QuantityOffers} from './pages/admin/IntegrationSettings';
import Analytics from './pages/admin/Analytics';
import Tracking from './components/Tracking';
import { Navigate, Route, Routes, useLocation } from 'react-router-dom';
import { useEffect } from 'react';
import Header from './components/Header'; import Footer from './components/Footer'; import WhatsAppFloat from './components/WhatsAppFloat';
import Home from './pages/Home'; import Offers from './pages/Offers'; import ForgotPassword from './pages/ForgotPassword'; import Invoice from './pages/Invoice'; import Products from './pages/Products'; import ProductDetail from './pages/ProductDetail'; import Login from './pages/Login'; import Register from './pages/Register'; import Cart from './pages/Cart'; import Checkout from './pages/Checkout'; import Track from './pages/Track'; import Account from './pages/Account'; import CmsPage from './pages/CmsPage'; import ServiceDetail from './pages/ServiceDetail'; import NotFound from './pages/NotFound';
import AccountDashboard from './pages/account/Dashboard'; import Orders from './pages/account/Orders'; import Prescriptions from './pages/account/Prescriptions'; import Wishlist from './pages/account/Wishlist'; import Addresses from './pages/account/Addresses'; import Profile from './pages/account/Profile'; import Notifications from './pages/account/Notifications'; import Reviews from './pages/account/Reviews'; import Returns from './pages/account/Returns'; import Bookings from './pages/account/Bookings';
import AdminLogin from './pages/admin/AdminLogin'; import AdminOffers from './pages/admin/Offers'; import EmailCenter from './pages/admin/EmailCenter'; import EmailTemplates from './pages/admin/EmailTemplates'; import AdminLayout from './pages/admin/AdminLayout'; import AdminDashboard from './pages/admin/Dashboard'; import AdminProducts from './pages/admin/Products'; import ProductForm from './pages/admin/ProductForm'; import AdminOrders from './pages/admin/Orders'; import AdminPrescriptions from './pages/admin/Prescriptions'; import Inventory from './pages/admin/Inventory'; import HomepageManager from './pages/admin/HomepageManager'; import Settings from './pages/admin/Settings'; import Procurement from './pages/admin/Procurement'; import Payments from './pages/admin/Payments';
import { CategoriesPage, BrandsPage, ManufacturersPage, SuppliersPage, CouponsPage, BannersPage, ServicesPage, CmsPagesPage, ShippingZonesPage, NavigationPage } from './pages/admin/Resources';
import { CustomersPage, ReviewsPage, ReturnsPage, BookingsPage, NewsletterPage, ContactMessagesPage, AuditLogsPage, ReportsPage } from './pages/admin/OperationalPages';
import { StaffPage, RolesPage } from './pages/admin/SystemPages';
import { useAuthStore } from './store/auth';
function ScrollTop() { const l = useLocation(); useEffect(() => { window.scrollTo({ top: 0, behavior: 'smooth' }) }, [l.pathname, l.search]); return null } function Site({ children }) { return <><ScrollTop /><Header />{children}<Footer /><WhatsAppFloat /></> }
function Guard({ children }) { const user = useAuthStore(s => s.user); const hydrated = useAuthStore(s => s.hydrated); return !hydrated ? <div className="min-h-screen" /> : user ? children : <Navigate to="/login" replace /> }
function AdminGuard({ children }) { const user = useAuthStore(s => s.user); const hydrated = useAuthStore(s => s.hydrated); return !hydrated ? <div className="min-h-screen" /> : user?.isAdmin ? children : <Navigate to="/admin/login" replace /> }
export default function App() {
  const initialize = useAuthStore(s => s.initialize); useEffect(() => { initialize() }, [initialize]); return <><Tracking/><Routes><Route path="/payment-result" element={<Guard><Site><PaymentResult/></Site></Guard>}/>
    <Route path="/" element={<Site><Home /></Site>} /><Route path="/products" element={<Site><Products /></Site>} /><Route path="/product/:slug" element={<Site><ProductDetail /></Site>} /><Route path="/page/:slug" element={<Site><CmsPage /></Site>} /><Route path="/service/:slug" element={<Site><ServiceDetail /></Site>} /><Route path="/login" element={<Site><Login /></Site>} /><Route path="/forgot-password" element={<Site><ForgotPassword /></Site>} /><Route path="/register" element={<Site><Register /></Site>} /><Route path="/offers" element={<Site><Offers /></Site>} /><Route path="/track" element={<Site><Track /></Site>} /><Route path="/not-found" element={<Site><NotFound /></Site>} />
    <Route path="/invoice/:id" element={<Guard><Invoice /></Guard>} /><Route path="/admin-invoice/:id" element={<AdminGuard><Invoice admin /></AdminGuard>} /><Route path="/cart" element={<Guard><Site><Cart /></Site></Guard>} /><Route path="/checkout" element={<Guard><Site><Checkout /></Site></Guard>} /><Route path="/account" element={<Guard><Site><Account /></Site></Guard>}><Route index element={<AccountDashboard />} /><Route path="profile" element={<Profile />} /><Route path="orders" element={<Orders />} /><Route path="prescriptions" element={<Prescriptions />} /><Route path="wishlist" element={<Wishlist />} /><Route path="addresses" element={<Addresses />} /><Route path="reviews" element={<Reviews />} /><Route path="returns" element={<Returns />} /><Route path="bookings" element={<Bookings />} /><Route path="notifications" element={<Notifications />} /></Route>
    <Route path="/admin/login" element={<AdminLogin />} /><Route path="/:adminSlug/login" element={<AdminLogin dynamic />} />
    <Route path="/admin" element={<AdminGuard><AdminLayout /></AdminGuard>}><Route index element={<AdminDashboard />} /><Route path="products" element={<AdminProducts />} /><Route path="products/new" element={<ProductForm />} /><Route path="products/:id/edit" element={<ProductForm />} /><Route path="categories" element={<CategoriesPage />} /><Route path="brands" element={<BrandsPage />} /><Route path="manufacturers" element={<ManufacturersPage />} /><Route path="inventory" element={<Inventory />} /><Route path="purchase-orders" element={<Procurement />} /><Route path="suppliers" element={<SuppliersPage />} /><Route path="shipping-zones" element={<ShippingZonesPage />} /><Route path="orders" element={<AdminOrders />} /><Route path="payments" element={<Payments />} /><Route path="returns" element={<ReturnsPage />} /><Route path="prescriptions" element={<AdminPrescriptions />} /><Route path="customers" element={<CustomersPage />} /><Route path="reviews" element={<ReviewsPage />} /><Route path="coupons" element={<CouponsPage />} /><Route path="offers" element={<AdminOffers />} /><Route path="banners" element={<BannersPage />} /><Route path="newsletter" element={<NewsletterPage />} /><Route path="services" element={<ServicesPage />} /><Route path="bookings" element={<BookingsPage />} /><Route path="homepage" element={<HomepageManager />} /><Route path="navigation" element={<NavigationPage />} /><Route path="pages" element={<CmsPagesPage />} /><Route path="messages" element={<ContactMessagesPage />} /><Route path="email-center" element={<EmailCenter />} /><Route path="email-templates" element={<EmailTemplates />} /><Route path="reports" element={<ReportsPage />} /><Route path="staff" element={<StaffPage />} /><Route path="roles" element={<RolesPage />} /><Route path="audit-logs" element={<AuditLogsPage />} /><Route path="settings" element={<Settings />} /><Route path="settings/payment" element={<IntegrationSettings kind="payment"/>}/><Route path="settings/email" element={<IntegrationSettings kind="email"/>}/><Route path="settings/sms" element={<IntegrationSettings kind="sms"/>}/><Route path="settings/notification" element={<IntegrationSettings kind="notification"/>}/><Route path="settings/analytics" element={<IntegrationSettings kind="analytics"/>}/><Route path="analytics" element={<Analytics/>}/><Route path="quantity-offers" element={<QuantityOffers/>}/></Route>
    <Route path="*" element={<Site><NotFound /></Site>} />
  </Routes></>
}
