import {useState} from 'react';
import {useParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {Mail,MapPin,Phone} from 'lucide-react';
import http from '../api/http';
import RichContent from '../components/RichContent';
import {useSiteConfig,setting} from '../hooks/useSiteConfig';
export default function CmsPage(){const {slug}=useParams();const {data:cfg}=useSiteConfig();const q=useQuery({queryKey:['page',slug],queryFn:()=>http.get('/pages/'+slug).then(r=>r.data.data)});if(q.isLoading)return <main className="container-app py-16">Loading page...</main>;if(q.isError)return <main className="container-app py-16 text-center"><h1 className="text-3xl font-black">Page not found</h1></main>;const p=q.data;return <main className="container-app py-12"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold text-brand-700">{setting(cfg,'brand.name','ShasthoCare')}</p><h1 className="mt-2 text-4xl font-black">{p.title}</h1><div className="mt-7 card p-6 md:p-8"><RichContent html={p.content} className="rich-content text-slate-700"/></div>{slug==='contact'&&<ContactForm cfg={cfg}/>}</div></main>}
function ContactForm({cfg}){const [f,setF]=useState({name:'',email:'',phone:'',subject:'',message:''});const [msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();try{const r=await http.post('/contact',f);setMsg(r.data.message);setF({name:'',email:'',phone:'',subject:'',message:''})}catch(e){setMsg(e.response?.data?.message||'Could not send message')}};return <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1.4fr]"><div className="card p-6"><h2 className="text-xl font-black">Contact details</h2><div className="mt-5 space-y-4 text-sm"><Line icon={Mail} text={setting(cfg,'contact.email','')}/><Line icon={Phone} text={setting(cfg,'contact.phone','')}/><Line icon={MapPin} text={setting(cfg,'contact.address','')}/><p className="text-slate-500">{setting(cfg,'contact.hours','')}</p></div></div><form onSubmit={submit} className="card p-6"><h2 className="text-xl font-black">Send a message</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><input required className="input" placeholder="Your name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required type="email" className="input" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input className="input" placeholder="Phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><input className="input" placeholder="Subject" value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/><textarea required className="input min-h-32 sm:col-span-2" placeholder="How can we help?" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></div><button className="btn-primary mt-4">Send message</button>{msg&&<p className="mt-3 text-sm text-slate-500">{msg}</p>}</form></div>}
function Line({icon:Icon,text}){return <div className="flex items-center gap-3"><Icon size={18} className="text-brand-600"/><span>{text||'Not configured'}</span></div>}
