import {useEffect,useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import {ArrowRight,Bell,ClipboardCheck,FlaskConical,Headphones,HeartPulse,Pill,RotateCcw,ShieldCheck,Stethoscope,Truck,Upload} from 'lucide-react';
import http,{assetUrl} from '../api/http';
import ProductCard from '../components/ProductCard';
import RichContent from '../components/RichContent';

const iconFor=(name,index=0)=>{
  const map={Stethoscope,FlaskConical,Bell,ClipboardCheck,HeartPulse,Pill,Truck,ShieldCheck,RotateCcw,Headphones,Upload};
  return map[name]||[Stethoscope,FlaskConical,Bell,ClipboardCheck,HeartPulse][index%5];
};

export default function Home(){
  const {data}=useQuery({queryKey:['home'],queryFn:()=>http.get('/home').then(r=>r.data.data)});
  const d=data||{categories:[],banners:[],services:[],bestSellers:[],newArrivals:[],featuredProducts:[],sections:[],brands:[],settings:{}};
  const s=d.settings||{};
  const sections=useMemo(()=>new Map((d.sections||[]).map(x=>[x.section_key,x])),[d.sections]);
  const banner=(position)=>d.banners?.find(x=>x.position===position);const banners=(position)=>(d.banners||[]).filter(x=>x.position===position);
  const visible=(key)=>sections.size===0||sections.has(key);
  const renderers={
    hero:()=> <Hero banners={banners('hero')} settings={s}/> ,
    trust:()=> <Trust section={sections.get('trust')} settings={s}/> ,
    categories:()=> <CategorySection section={sections.get('categories')} rows={d.categories||[]}/> ,
    best_sellers:()=> <ProductSection section={sections.get('best_sellers')} rows={d.bestSellers||[]}/> ,
    prescription:()=> <PrescriptionBanner section={sections.get('prescription')} banner={banner('prescription')}/> ,
    services:()=> <Services section={sections.get('services')} rows={d.services||[]}/> ,
    featured:()=> <ProductSection section={sections.get('featured')} rows={d.featuredProducts||[]}/> ,
    brands:()=> <Brands section={sections.get('brands')} rows={d.brands||[]}/> ,
    new_arrivals:()=> <ProductSection section={sections.get('new_arrivals')} rows={d.newArrivals||[]}/> ,
    newsletter:()=> <Newsletter section={sections.get('newsletter')}/> 
  };
  const ordered=(d.sections||[]).length?d.sections.map(x=>x.section_key):Object.keys(renderers);
  return <main>{ordered.filter(k=>visible(k)&&renderers[k]).map(k=><div key={k}>{renderers[k]()}</div>)}{(d.banners||[]).filter(x=>x.position==='promotion').map(x=><Promotion key={x.id} banner={x}/>)}</main>;
}

function Hero({banners=[],settings}){
  const slides=banners.length?banners:[null];const [index,setIndex]=useState(0);
  useEffect(()=>{setIndex(0)},[banners.length]);
  useEffect(()=>{if(slides.length<2)return;const id=setInterval(()=>setIndex(i=>(i+1)%slides.length),5000);return()=>clearInterval(id)},[slides.length]);
  const banner=slides[index];const title=banner?.title||'Better Health, Delivered Daily.';const subtitle=banner?.subtitle||'<p>Genuine healthcare products, trusted service and convenient delivery from one modern storefront.</p>';const cta=banner?.button_text||'Shop Medicines';const ctaUrl=banner?.button_url||'/products';
  return <section className="hero-surface overflow-hidden"><div className="container-app grid min-h-[520px] items-center gap-10 py-12 lg:grid-cols-2"><div><span className="badge bg-white text-brand-700 shadow">✦ {settings['home.hero_badge']||'Your Health, Our Priority'}</span><h1 className="mt-5 max-w-2xl text-5xl font-black leading-[1.04] tracking-tight md:text-6xl">{title}</h1><RichContent html={subtitle} className="rich-content mt-5 max-w-xl text-lg text-slate-600"/><div className="mt-7 flex flex-wrap gap-3"><Link to={ctaUrl} className="btn-primary">{cta} <ArrowRight size={18}/></Link><Link to="/account/prescriptions" className="btn-secondary"><Upload size={18}/>Upload Prescription</Link></div><p className="mt-7 text-sm font-semibold text-slate-600">{settings['home.hero_note']||'100% genuine products • Secure checkout • Professional support'}</p>{banner?.content&&<RichContent html={banner.content} className="rich-content mt-5 max-w-xl text-sm text-slate-500"/>}</div><div className="relative min-h-[390px]">{banner?.image?<picture key={banner.id}><source media="(max-width: 640px)" srcSet={assetUrl(banner.mobile_image||banner.image)}/><img src={assetUrl(banner.image)} alt={banner.title||'Healthcare promotion'} className="absolute inset-0 h-full w-full rounded-[2.5rem] object-cover shadow-2xl transition-opacity duration-500"/></picture>:<HeroIllustration/>}{slides.length>1&&<div className="absolute bottom-4 left-1/2 z-10 flex -translate-x-1/2 gap-2">{slides.map((x,i)=><button aria-label={`Show hero slide ${i+1}`} key={x?.id||i} onClick={()=>setIndex(i)} className={`h-2.5 rounded-full bg-white shadow transition-all ${i===index?'w-8':'w-2.5 opacity-70'}`}/>)}</div>}</div></div></section>;
}
function HeroIllustration(){return <div className="relative h-full min-h-[390px]"><div className="absolute inset-8 rounded-[3rem] bg-brand-100/70 blur-3xl"/><div className="card absolute left-1/2 top-4 w-64 -translate-x-1/2 rounded-[2.5rem] border-8 border-slate-900 p-3 shadow-2xl"><div className="rounded-[1.8rem] bg-brand-600 p-5 text-white"><div className="text-xs">Healthcare, simplified</div><div className="mt-3 rounded-xl bg-white/95 p-3 text-xs text-slate-500">Search medicines...</div><div className="mt-5 grid grid-cols-2 gap-3">{['Medicines','Upload Rx','Lab Tests','Orders'].map(x=><div className="rounded-xl bg-white/10 p-3 text-center text-xs" key={x}>{x}</div>)}</div><div className="mt-5 rounded-2xl bg-white p-4 text-ink"><div className="text-sm font-black">Store offers</div><div className="text-xs text-slate-500">Admin-controlled promotions</div></div></div></div><div className="absolute bottom-10 left-2 h-44 w-36 rounded-3xl bg-white p-5 shadow-xl"><Pill className="text-brand-600" size={40}/><div className="mt-7 font-black">Healthcare</div><div className="text-xs text-slate-500">Everyday essentials</div></div><div className="absolute bottom-6 right-2 h-48 w-40 rounded-3xl bg-white p-5 shadow-xl"><ShieldCheck className="text-brand-600" size={42}/><div className="mt-8 font-black">Secure Care</div><div className="text-xs text-slate-500">Trusted workflow</div></div></div>}
function Trust({section,settings}){const rows=[[Truck,settings['home.trust_1_title']||'Express Delivery',settings['home.trust_1_text']||'Reliable delivery updates'],[ShieldCheck,settings['home.trust_2_title']||'Secure Payments',settings['home.trust_2_text']||'Protected checkout'],[RotateCcw,settings['home.trust_3_title']||'Easy Returns',settings['home.trust_3_text']||'Policy-based support'],[Headphones,settings['home.trust_4_title']||'Customer Support',settings['home.trust_4_text']||'Help when you need it']];return <section className="container-app relative z-10 -mt-5"><div className="card grid grid-cols-2 divide-x divide-slate-100 md:grid-cols-4">{rows.map(([I,t,sub])=><div className="flex items-center gap-3 p-5" key={t}><I className="text-brand-600"/><div><div className="text-sm font-bold">{t}</div><div className="text-xs text-slate-500">{sub}</div></div></div>)}</div>{section?.subtitle&&<RichContent html={section.subtitle} className="rich-content mt-4 text-sm text-slate-500"/>}</section>}
function SectionHead({section,fallback,viewAll=true}){return <div className="mb-6 flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{section?.title||fallback}</h2>{section?.subtitle&&<RichContent html={section.subtitle} className="rich-content mt-2 max-w-2xl text-sm text-slate-500"/>}</div>{viewAll&&<Link className="shrink-0 text-sm font-bold text-brand-700" to="/products">View all →</Link>}</div>}
function CategorySection({section,rows}){return <section className="container-app py-10"><SectionHead section={section} fallback="Shop by Category"/><div className="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">{rows.map(c=><Link key={c.id} to={'/products?category='+c.slug+'#products-top'} className="card p-5 text-center transition hover:-translate-y-1 hover:border-brand-200"><div className="mx-auto grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-brand-50 text-2xl">{c.image?<img src={assetUrl(c.image)} alt="" className="h-full w-full object-cover"/>:'✚'}</div><div className="mt-3 text-sm font-bold">{c.name}</div></Link>)}</div></section>}
function ProductSection({section,rows}){if(!rows.length)return null;return <section className="container-app py-10"><SectionHead section={section} fallback="Products"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{rows.slice(0,10).map(p=><ProductCard key={p.id} p={p}/>)}</div></section>}
function PrescriptionBanner({section,banner}){return <section className="container-app my-8"><div className="overflow-hidden rounded-3xl bg-gradient-to-r from-brand-700 to-brand-500 p-8 text-white md:p-10"><div className="grid items-center gap-8 md:grid-cols-2"><div><div className="text-3xl font-black">{banner?.title||section?.title||'Upload Prescription & Get Medicines Delivered'}</div>{banner?.subtitle?<RichContent html={banner.subtitle} className="rich-content mt-3 text-white/85"/>:<p className="mt-3 max-w-xl text-white/80">Upload securely. A pharmacist can review prescription-required items before fulfillment.</p>}<Link to={banner?.button_url||'/account/prescriptions'} className="mt-6 inline-flex rounded-xl bg-white px-5 py-3 font-bold text-brand-700">{banner?.button_text||'Upload Now'}</Link></div>{banner?.image?<img src={assetUrl(banner.image)} className="mx-auto max-h-56 rounded-2xl object-contain" alt="Prescription service"/>:<div className="flex justify-center gap-6 text-white/90"><Upload size={72}/><ShieldCheck size={72}/><Pill size={72}/></div>}</div></div></section>}
function Services({section,rows}){return <section className="container-app py-10"><SectionHead section={section} fallback="Healthcare Services" viewAll={false}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{rows.map((s,i)=>{const I=iconFor(s.icon,i);return <div className="card overflow-hidden p-6" key={s.id}>{s.image?<img src={assetUrl(s.image)} alt="" className="mb-4 h-28 w-full rounded-xl object-cover"/>:<I className="text-brand-600" size={32}/>}<h3 className="font-black">{s.name}</h3><RichContent html={s.description} className="rich-content mt-2 line-clamp-4 text-sm text-slate-500"/><div className="mt-4 flex items-center justify-between"><span className="text-sm font-black text-brand-700">{Number(s.price)>0?`৳${Number(s.price).toLocaleString()}`:'Contact us'}</span><Link to={s.slug?`/service/${s.slug}`:'/'} className="text-sm font-bold text-brand-700">Explore →</Link></div></div>})}</div></section>}
function Brands({section,rows}){if(!rows.length)return null;return <section className="container-app py-10"><SectionHead section={section} fallback="Featured Brands"/><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-6">{rows.map(b=><Link to={'/products?brand='+b.slug} key={b.id} className="card grid min-h-24 place-items-center p-4 text-center font-black hover:border-brand-200">{b.logo?<img src={assetUrl(b.logo)} alt={b.name} className="max-h-12 object-contain"/>:b.name}</Link>)}</div></section>}
function Promotion({banner}){return <section className="container-app py-6"><div className="card overflow-hidden bg-brand-50"><div className="grid items-center md:grid-cols-2"><div className="p-8"><h2 className="text-3xl font-black">{banner.title}</h2><RichContent html={banner.subtitle} className="rich-content mt-3 text-slate-600"/>{banner.button_text&&<Link className="btn-primary mt-5" to={banner.button_url||'/products'}>{banner.button_text}</Link>}</div>{banner.image&&<img src={assetUrl(banner.image)} alt={banner.title} className="h-full max-h-72 w-full object-cover"/>}</div></div></section>}
function Newsletter({section}){const [email,setEmail]=useState('');const [message,setMessage]=useState('');const submit=async e=>{e.preventDefault();try{const r=await http.post('/newsletter',{email});setMessage(r.data.message);setEmail('')}catch(err){setMessage(err.response?.data?.message||'Could not subscribe')}};return <section className="container-app py-10"><div className="card bg-slate-950 p-8 text-white md:p-10"><div className="grid items-center gap-6 md:grid-cols-2"><div><h2 className="text-2xl font-black">{section?.title||'Stay in the loop'}</h2>{section?.subtitle?<RichContent html={section.subtitle} className="rich-content mt-2 text-slate-300"/>:<p className="mt-2 text-sm text-slate-300">Receive store news, service updates and selected promotions.</p>}</div><form onSubmit={submit} className="flex gap-2"><input className="input text-ink" type="email" required placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn-primary">Subscribe</button></form></div>{message&&<div className="mt-3 text-xs text-brand-200">{message}</div>}</div></section>}
