import {Router} from 'express';
import {z} from 'zod';
import rateLimit from 'express-rate-limit';
import {query} from '../config/db.js';
import {auth,optionalAuth} from '../middleware/auth.js';
import {isAdmin,requirePermission} from '../middleware/admin.js';
import {asyncHandler} from '../utils/asyncHandler.js';
const r=Router();
const events=['page_view','view_item','add_to_cart','remove_from_cart','begin_checkout','add_payment_info','purchase','add_to_wishlist','search','heartbeat'];
r.get('/tracking-config',asyncHandler(async(req,res)=>{const [s]=await query('SELECT * FROM analytics_settings WHERE id=1');res.set('Cache-Control','no-store').json({success:true,data:s?.status?s:{status:0}})}));
r.get('/quantity-offers',asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT q.id,q.name,q.product_id,q.price_type,q.minimum_quantity,q.bundle_price,q.end_date,p.name product_name,p.slug,p.unit_price,p.strip_price,p.box_price,p.sale_price,p.prescription_required,p.units_per_strip,p.units_per_box,(SELECT image_url FROM product_images WHERE product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image,(SELECT COALESCE(SUM(remaining_quantity),0) FROM inventory_batches WHERE product_id=p.id AND expiry_date>CURDATE()) stock FROM quantity_offers q JOIN products p ON p.id=q.product_id WHERE q.is_active=1 AND q.start_date<=NOW() AND q.end_date>=NOW() AND p.is_active=1 AND p.deleted_at IS NULL ORDER BY q.end_date,q.id`)})));
r.post('/activity',rateLimit({windowMs:60000,limit:90}),optionalAuth,asyncHandler(async(req,res)=>{
 const d=z.object({consent:z.literal(true),event_id:z.string().uuid(),visitor_id:z.string().uuid(),session_id:z.string().uuid(),event_name:z.enum(events),page_url:z.string().max(500).regex(/^\/(?!\/)[^?#]*$/),product_id:z.number().int().positive().optional(),order_id:z.number().int().positive().optional(),search_term:z.string().max(120).optional()}).parse(req.body);
 const [s]=await query('SELECT status FROM analytics_settings WHERE id=1');if(!s?.status)return res.status(204).end();
 if(/^\/(admin|account|invoice|admin-invoice|reset-password|forgot-password|login|register)(\/|$)/.test(d.page_url))return res.status(204).end();
 let purchaseKey=null;
 if(d.event_name==='purchase'){if(!req.user||!d.order_id)return res.status(400).json({success:false,message:'Verified order required'});const [o]=await query("SELECT id FROM orders WHERE id=? AND user_id=? AND status<>'cancelled' AND (payment_method='cod' OR payment_status='paid')",[d.order_id,req.user.id]);if(!o)return res.status(409).json({success:false,message:'Order is not eligible for purchase tracking'});purchaseKey=String(o.id)}
 const ua=req.get('user-agent')||'',device=/mobile|android|iphone/i.test(ua)?'mobile':/ipad|tablet/i.test(ua)?'tablet':'desktop',browser=/edg/i.test(ua)?'Edge':/firefox/i.test(ua)?'Firefox':/chrome/i.test(ua)?'Chrome':/safari/i.test(ua)?'Safari':'Other';
 const result=await query('INSERT IGNORE INTO user_activity_logs(event_id,user_id,visitor_id,session_id,event_name,page_url,product_id,order_id,search_term,device_type,browser,purchase_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[d.event_id,req.user?.id||null,d.visitor_id,d.session_id,d.event_name,d.page_url,d.product_id||null,d.order_id||null,d.search_term||null,device,browser,purchaseKey]);res.status(201).json({success:true,data:{accepted:Boolean(result.affectedRows)}})
}));
r.get('/admin/analytics/:section',auth,isAdmin,requirePermission('reports.view'),asyncHandler(async(req,res)=>{
 const days=Math.min(365,Math.max(1,parseInt(req.query.days)||30)),params=[days];
 const where='created_at>=DATE_SUB(NOW(),INTERVAL ? DAY)';let data;
 switch(req.params.section){
 case 'traffic':{const [summary]=await query(`SELECT COUNT(DISTINCT visitor_id) unique_visitors,COUNT(DISTINCT session_id) sessions,SUM(event_name='page_view') page_views,COUNT(DISTINCT CASE WHEN event_name='purchase' THEN visitor_id END) purchasing_visitors FROM user_activity_logs WHERE ${where}`,params);summary.conversion_rate=Number(summary.unique_visitors)?Number(summary.purchasing_visitors)/Number(summary.unique_visitors)*100:0;data={summary,pages:await query(`SELECT page_url,COUNT(*) views FROM user_activity_logs WHERE ${where} AND event_name='page_view' GROUP BY page_url ORDER BY views DESC LIMIT 30`,params),daily:await query(`SELECT DATE(created_at) day,COUNT(DISTINCT visitor_id) visitors,SUM(event_name='page_view') page_views FROM user_activity_logs WHERE ${where} GROUP BY DATE(created_at) ORDER BY day`,params)};break}
 case 'funnel':{const rows=await query(`WITH product AS (SELECT session_id,MIN(created_at) t FROM user_activity_logs WHERE ${where} AND event_name='view_item' GROUP BY session_id), cart AS (SELECT p.session_id,MIN(l.created_at) t FROM product p JOIN user_activity_logs l ON l.session_id=p.session_id AND l.created_at>=p.t AND l.event_name='add_to_cart' GROUP BY p.session_id), checkout AS (SELECT c.session_id,MIN(l.created_at) t FROM cart c JOIN user_activity_logs l ON l.session_id=c.session_id AND l.created_at>=c.t AND l.event_name='begin_checkout' GROUP BY c.session_id), purchase AS (SELECT c.session_id,MIN(l.created_at) t FROM checkout c JOIN user_activity_logs l ON l.session_id=c.session_id AND l.created_at>=c.t AND l.event_name='purchase' GROUP BY c.session_id) SELECT 'Product viewed' stage,COUNT(*) sessions FROM product UNION ALL SELECT 'Added to cart',COUNT(*) FROM cart UNION ALL SELECT 'Checkout',COUNT(*) FROM checkout UNION ALL SELECT 'Purchase',COUNT(*) FROM purchase`,params);data=rows.map((x,i)=>({...x,drop_off:i?Math.max(0,Number(rows[i-1].sessions)-Number(x.sessions)):0}));break}
 case 'products':data={activity:await query(`SELECT l.product_id,p.name,SUM(l.event_name='view_item') views,SUM(l.event_name='add_to_cart') add_to_cart FROM user_activity_logs l LEFT JOIN products p ON p.id=l.product_id WHERE l.${where} AND l.product_id IS NOT NULL GROUP BY l.product_id,p.name ORDER BY views DESC LIMIT 50`,params),searches:await query(`SELECT search_term,COUNT(*) searches FROM user_activity_logs WHERE ${where} AND event_name='search' AND search_term IS NOT NULL GROUP BY search_term ORDER BY searches DESC LIMIT 30`,params),abandoned:await query(`SELECT l.product_id,p.name,COUNT(DISTINCT l.session_id) sessions FROM user_activity_logs l LEFT JOIN products p ON p.id=l.product_id WHERE l.${where} AND l.created_at<DATE_SUB(NOW(),INTERVAL 30 MINUTE) AND l.event_name='add_to_cart' AND NOT EXISTS(SELECT 1 FROM user_activity_logs x WHERE x.session_id=l.session_id AND x.event_name IN ('purchase','remove_from_cart') AND x.created_at>=l.created_at AND (x.event_name='purchase' OR x.product_id=l.product_id)) GROUP BY l.product_id,p.name ORDER BY sessions DESC LIMIT 30`,params),sales:await query(`SELECT oi.product_id,oi.product_name,SUM(oi.quantity) quantity,SUM(oi.subtotal) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.${where} AND o.status NOT IN ('cancelled','refunded') AND (o.payment_status='paid' OR o.status='delivered') GROUP BY oi.product_id,oi.product_name ORDER BY revenue DESC LIMIT 30`,params)};break;
 case 'customers':{const [summary]=await query(`SELECT (SELECT COUNT(*) FROM users WHERE ${where}) new_users,COUNT(DISTINCT user_id) active_users,COUNT(DISTINCT CASE WHEN visitor_id IN (SELECT visitor_id FROM user_activity_logs GROUP BY visitor_id HAVING COUNT(DISTINCT session_id)>1) THEN visitor_id END) returning_visitors FROM user_activity_logs WHERE ${where}`,[days,days]);data={summary,customers:await query(`SELECT user_id,COUNT(DISTINCT page_url) pages_visited,SUM(event_name='view_item') products_viewed,SUM(event_name='add_to_cart') cart_additions,COUNT(DISTINCT CASE WHEN event_name='purchase' THEN order_id END) orders FROM user_activity_logs WHERE ${where} AND user_id IS NOT NULL GROUP BY user_id ORDER BY pages_visited DESC LIMIT 50`,params)};break}
 case 'behavior':data=await query(`SELECT session_id,event_name,page_url,product_id,order_id,created_at FROM user_activity_logs WHERE ${where} AND event_name<>'heartbeat' ORDER BY id DESC LIMIT 300`,params);break;
 case 'realtime':data=await query("SELECT l.session_id,l.page_url,l.device_type,l.browser,l.country,l.created_at FROM user_activity_logs l JOIN (SELECT session_id,MAX(id) id FROM user_activity_logs WHERE created_at>=DATE_SUB(NOW(),INTERVAL 2 MINUTE) GROUP BY session_id) x ON x.id=l.id ORDER BY l.id DESC LIMIT 200");break;
 default:return res.status(404).json({success:false,message:'Unknown analytics section'});
 }res.json({success:true,data})
}));
export default r;
