import {Router} from 'express';
import {query,pool} from '../config/db.js';
import {auth} from '../middleware/auth.js';
import {asyncHandler} from '../utils/asyncHandler.js';
import {prescriptionUpload} from '../middleware/upload.js';
import {getSettingsMap} from '../services/settings.js';

const r=Router();r.use(auth);
const bool=v=>v===true||v===1||v==='1'||v==='true';
const money=n=>Number(Number(n||0).toFixed(2));
const safeType=v=>['unit','strip','box'].includes(v)?v:'unit';
const priceFor=(p,type)=>type==='box'?Number(p.box_price||p.sale_price||0):type==='strip'?Number(p.strip_price||p.sale_price||0):Number(p.unit_price||p.sale_price||0);
const multiplierFor=(p,type)=>type==='box'?Math.max(1,Number(p.units_per_box||1)):type==='strip'?Math.max(1,Number(p.units_per_strip||1)):1;

r.get('/dashboard',asyncHandler(async(req,res)=>{
  const [orderStats,prescriptionStats,wishlistStats,addressStats,notificationStats,recentOrders]=await Promise.all([
    query(`SELECT COUNT(*) total, SUM(status IN ('pending','prescription_review','confirmed','processing','packed','shipped','out_for_delivery')) active, SUM(status='delivered') delivered, COALESCE(SUM(total),0) spent FROM orders WHERE user_id=?`,[req.user.id]),
    query(`SELECT COUNT(*) total, SUM(status='approved') approved, SUM(status IN ('uploaded','under_review')) pending FROM prescriptions WHERE user_id=?`,[req.user.id]),
    query('SELECT COUNT(*) total FROM wishlist_items WHERE user_id=?',[req.user.id]),
    query('SELECT COUNT(*) total FROM user_addresses WHERE user_id=?',[req.user.id]),
    query('SELECT COUNT(*) total, SUM(is_read=0) unread FROM notifications WHERE user_id=?',[req.user.id]),
    query('SELECT id,order_number,total,status,payment_status,payment_method,created_at FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 5',[req.user.id])
  ]);
  res.json({success:true,data:{orders:orderStats[0]||{},prescriptions:prescriptionStats[0]||{},wishlist:Number(wishlistStats[0]?.total||0),addresses:Number(addressStats[0]?.total||0),notifications:notificationStats[0]||{},recentOrders}});
}));

r.get('/profile',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT id,first_name,last_name,email,phone,is_verified,created_at FROM users WHERE id=?',[req.user.id]).then(x=>x[0])})));
r.patch('/profile',asyncHandler(async(req,res)=>{const u=(await query('SELECT * FROM users WHERE id=?',[req.user.id]))[0];if(!u)return res.status(404).json({success:false,message:'User not found'});await query('UPDATE users SET first_name=?,last_name=?,phone=? WHERE id=?',[req.body.firstName??u.first_name,req.body.lastName??u.last_name,req.body.phone??u.phone,req.user.id]);res.json({success:true})}));

r.get('/addresses',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM user_addresses WHERE user_id=? ORDER BY is_default DESC,id DESC',[req.user.id])})));
r.post('/addresses',asyncHandler(async(req,res)=>{const d=req.body;if(bool(d.isDefault))await query('UPDATE user_addresses SET is_default=0 WHERE user_id=?',[req.user.id]);const x=await query('INSERT INTO user_addresses(user_id,label,full_name,phone,division,district,area,postal_code,address_line,landmark,is_default) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[req.user.id,d.label||'Home',d.fullName,d.phone,d.division,d.district,d.area,d.postalCode||'',d.addressLine,d.landmark||'',bool(d.isDefault)?1:0]);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.patch('/addresses/:id',asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM user_addresses WHERE id=? AND user_id=?',[req.params.id,req.user.id]))[0];if(!o)return res.status(404).json({success:false,message:'Address not found'});if(bool(req.body.isDefault))await query('UPDATE user_addresses SET is_default=0 WHERE user_id=?',[req.user.id]);await query('UPDATE user_addresses SET label=?,full_name=?,phone=?,division=?,district=?,area=?,postal_code=?,address_line=?,landmark=?,is_default=? WHERE id=? AND user_id=?',[req.body.label??o.label,req.body.fullName??o.full_name,req.body.phone??o.phone,req.body.division??o.division,req.body.district??o.district,req.body.area??o.area,req.body.postalCode??o.postal_code,req.body.addressLine??o.address_line,req.body.landmark??o.landmark,bool(req.body.isDefault??o.is_default)?1:0,req.params.id,req.user.id]);res.json({success:true})}));
r.delete('/addresses/:id',asyncHandler(async(req,res)=>{await query('DELETE FROM user_addresses WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({success:true})}));

r.get('/wishlist',asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT p.id,p.name,p.slug,p.pack_size,p.sale_price,p.regular_price,p.discount_percent,p.unit_price,p.strip_price,p.box_price,p.units_per_strip,p.units_per_box,p.rating_avg,p.review_count,p.prescription_required,(SELECT image_url FROM product_images WHERE product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image,(SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id) stock FROM wishlist_items w JOIN products p ON p.id=w.product_id WHERE w.user_id=? AND p.deleted_at IS NULL AND p.is_active=1`,[req.user.id])})));
r.post('/wishlist/:id',asyncHandler(async(req,res)=>{await query('INSERT IGNORE INTO wishlist_items(user_id,product_id) VALUES(?,?)',[req.user.id,req.params.id]);res.status(201).json({success:true,message:'Added to wishlist'})}));
r.delete('/wishlist/:id',asyncHandler(async(req,res)=>{await query('DELETE FROM wishlist_items WHERE user_id=? AND product_id=?',[req.user.id,req.params.id]);res.json({success:true,message:'Removed from wishlist'})}));

r.get('/cart',asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT ci.id cart_item_id,ci.quantity,ci.price_type,ci.unit_multiplier,p.id,p.name,p.slug,p.pack_size,p.unit_label,p.unit_price,p.units_per_strip,p.strip_price,p.strips_per_box,p.units_per_box,p.box_price,p.sale_price,p.regular_price,p.prescription_required,(CASE ci.price_type WHEN 'box' THEN COALESCE(NULLIF(p.box_price,0),p.sale_price) WHEN 'strip' THEN COALESCE(NULLIF(p.strip_price,0),p.sale_price) ELSE COALESCE(NULLIF(p.unit_price,0),p.sale_price) END) effective_price,(SELECT image_url FROM product_images WHERE product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image,(SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id) stock FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.user_id=? AND p.deleted_at IS NULL AND p.is_active=1 ORDER BY ci.id DESC`,[req.user.id])})));
r.post('/cart/items',asyncHandler(async(req,res)=>{const qty=Math.max(1,Math.round(Number(req.body.quantity||1))),type=safeType(req.body.priceType);const p=(await query(`SELECT p.*,(SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id) stock FROM products p WHERE p.id=? AND p.is_active=1 AND p.deleted_at IS NULL`,[req.body.productId]))[0];if(!p)return res.status(404).json({success:false,message:'Product unavailable'});const mult=multiplierFor(p,type),needed=qty*mult;if(Number(p.stock)<needed)return res.status(409).json({success:false,message:`Requested ${type} quantity needs ${needed} units but only ${p.stock} are available`});await query(`INSERT INTO cart_items(user_id,product_id,quantity,price_type,unit_multiplier) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity),unit_multiplier=VALUES(unit_multiplier)`,[req.user.id,req.body.productId,qty,type,mult]);res.status(201).json({success:true})}));
r.patch('/cart/items/:id',asyncHandler(async(req,res)=>{const qv=Math.max(1,Math.round(Number(req.body.quantity||1)));const item=(await query(`SELECT ci.*,p.unit_price,p.strip_price,p.box_price,p.sale_price,p.units_per_strip,p.units_per_box,(SELECT COALESCE(SUM(CASE WHEN ib.expiry_date>CURDATE() THEN ib.remaining_quantity ELSE 0 END),0) FROM inventory_batches ib WHERE ib.product_id=p.id) stock FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.id=? AND ci.user_id=?`,[req.params.id,req.user.id]))[0];if(!item)return res.status(404).json({success:false,message:'Cart item not found'});const needed=qv*Math.max(1,Number(item.unit_multiplier||1));if(Number(item.stock)<needed)return res.status(409).json({success:false,message:'Not enough stock for this quantity'});await query('UPDATE cart_items SET quantity=? WHERE id=? AND user_id=?',[qv,req.params.id,req.user.id]);res.json({success:true})}));
r.delete('/cart/items/:id',asyncHandler(async(req,res)=>{await query('DELETE FROM cart_items WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({success:true})}));
r.delete('/cart',asyncHandler(async(req,res)=>{await query('DELETE FROM cart_items WHERE user_id=?',[req.user.id]);res.json({success:true})}));

r.post('/prescriptions',prescriptionUpload.single('file'),asyncHandler(async(req,res)=>{if(!req.file)return res.status(400).json({success:false,message:'Valid prescription file required'});const x=await query('INSERT INTO prescriptions(user_id,doctor_name,clinic_name,prescription_date,notes,file_path,status) VALUES(?,?,?,?,?,?,?)',[req.user.id,req.body.doctorName||null,req.body.clinicName||null,req.body.date||null,req.body.notes||null,req.file.path.replaceAll('\\','/'),'uploaded']);res.status(201).json({success:true,data:{id:x.insertId,status:'uploaded'}})}));
r.get('/prescriptions',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT id,doctor_name,clinic_name,prescription_date,notes,status,reviewed_at,admin_notes,created_at FROM prescriptions WHERE user_id=? ORDER BY id DESC',[req.user.id])})));

r.get('/orders',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT id,order_number,total,status,payment_status,payment_method,payment_sender_last4,payment_transaction_id,tracking_code,courier_name,created_at FROM orders WHERE user_id=? ORDER BY id DESC',[req.user.id])})));
r.get('/orders/:id',asyncHandler(async(req,res)=>{const o=(await query('SELECT * FROM orders WHERE id=? AND user_id=?',[req.params.id,req.user.id]))[0];if(!o)return res.status(404).json({success:false,message:'Order not found'});o.items=await query('SELECT * FROM order_items WHERE order_id=?',[o.id]);o.history=await query('SELECT status,note,created_at FROM order_status_history WHERE order_id=? ORDER BY id',[o.id]);res.json({success:true,data:o})}));
r.get('/orders/:id/invoice',asyncHandler(async(req,res)=>{const o=(await query(`SELECT o.*,u.first_name,u.last_name,u.email,u.phone FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=? AND o.user_id=?`,[req.params.id,req.user.id]))[0];if(!o)return res.status(404).json({success:false,message:'Invoice not found'});o.items=await query('SELECT * FROM order_items WHERE order_id=? ORDER BY id',[o.id]);const settings=await getSettingsMap();res.json({success:true,data:{order:o,settings}})}));

r.post('/coupons/validate',asyncHandler(async(req,res)=>{const c=(await query('SELECT * FROM coupons WHERE code=? AND is_active=1 AND start_date<=NOW() AND end_date>=NOW()',[String(req.body.code||'').toUpperCase()]))[0];if(!c)return res.status(404).json({success:false,message:'Invalid or expired coupon'});if(c.usage_limit){const used=(await query('SELECT COUNT(*) n FROM coupon_usages WHERE coupon_id=?',[c.id]))[0].n;if(used>=c.usage_limit)return res.status(400).json({success:false,message:'Coupon usage limit reached'})}if(c.usage_per_user){const used=(await query('SELECT COUNT(*) n FROM coupon_usages WHERE coupon_id=? AND user_id=?',[c.id,req.user.id]))[0].n;if(used>=c.usage_per_user)return res.status(400).json({success:false,message:'You have already used this coupon'})}res.json({success:true,data:c})}));

async function getCheckoutItems(userId,conn=null,lock=false){const q=conn?async(s,p)=>{const [rows]=await conn.execute(s,p);return rows}:query;return q(`SELECT ci.quantity,ci.price_type,ci.unit_multiplier,p.id,p.name,p.sku,p.unit_price,p.strip_price,p.box_price,p.sale_price,p.discount_percent,p.units_per_strip,p.units_per_box,p.prescription_required,(SELECT image_url FROM product_images WHERE product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.user_id=? AND p.is_active=1 AND p.deleted_at IS NULL ${lock?'FOR UPDATE':''}`,[userId])}

r.post('/checkout/preview',asyncHandler(async(req,res)=>{const items=await getCheckoutItems(req.user.id);const subtotal=items.reduce((a,x)=>a+priceFor(x,x.price_type)*Number(x.quantity),0);const {shipping,discount,total}=await calculateTotals(req,subtotal);res.json({success:true,data:{subtotal:money(subtotal),shipping:money(shipping),discount:money(discount),total:money(total)}})}));

async function calculateTotals(req,subtotal,conn=null){
  const q=conn?async(s,p)=>{const [rows]=await conn.execute(s,p);return rows}:query;const settings=await getSettingsMap();let shipping=Number(settings['shipping.default_fee']||80);
  let address=req.body.address||{};
  if(req.body.addressId){const saved=(await q('SELECT * FROM user_addresses WHERE id=? AND user_id=?',[req.body.addressId,req.user.id]))[0];if(!saved)throw Object.assign(new Error('Saved delivery address not found'),{status:404});address={fullName:saved.full_name,phone:saved.phone,division:saved.division,district:saved.district,area:saved.area,postalCode:saved.postal_code,addressLine:saved.address_line,landmark:saved.landmark,label:saved.label};}
  if(!String(address.fullName||'').trim()||!String(address.phone||'').trim()||!String(address.addressLine||'').trim())throw Object.assign(new Error('Full name, phone and delivery address are required'),{status:400});
  const zone=(await q(`SELECT * FROM shipping_zones WHERE is_active=1 AND (division IS NULL OR LOWER(division)=LOWER(?)) AND (district IS NULL OR LOWER(district)=LOWER(?)) ORDER BY (district IS NOT NULL) DESC,(division IS NOT NULL) DESC,sort_order,id LIMIT 1`,[address.division||'',address.district||'']))[0];
  if(zone)shipping=Number(zone.fee||0);const threshold=Number(zone?.free_shipping_threshold??settings['shipping.free_threshold']??1500);if(threshold>0&&subtotal>=threshold)shipping=0;
  let discount=0,coupon=null;if(req.body.couponCode){coupon=(await q('SELECT * FROM coupons WHERE code=? AND is_active=1 AND start_date<=NOW() AND end_date>=NOW()',[String(req.body.couponCode).toUpperCase()]))[0];if(coupon&&subtotal>=Number(coupon.minimum_order||0)){if(coupon.usage_limit){const used=(await q('SELECT COUNT(*) n FROM coupon_usages WHERE coupon_id=?',[coupon.id]))[0].n;if(used>=coupon.usage_limit)coupon=null}if(coupon&&coupon.usage_per_user){const used=(await q('SELECT COUNT(*) n FROM coupon_usages WHERE coupon_id=? AND user_id=?',[coupon.id,req.user.id]))[0].n;if(used>=coupon.usage_per_user)coupon=null}if(coupon)discount=coupon.discount_type==='percentage'?Math.min(subtotal*Number(coupon.value)/100,Number(coupon.maximum_discount||999999999)):Number(coupon.value)}}
  return {shipping,discount,total:Math.max(0,subtotal+shipping-discount),coupon,address,zone};
}

r.post('/checkout',asyncHandler(async(req,res)=>{
  const settings=await getSettingsMap();const method=req.body.paymentMethod||'cod';
  const allowed={cod:settings['payment.cod']!=='0',bkash:settings['payment.bkash']!=='0',nagad:settings['payment.nagad']!=='0',rocket:settings['payment.rocket']!=='0',sslcommerz:settings['payment.sslcommerz']!=='0'};
  if(!allowed[method])return res.status(400).json({success:false,message:'Selected payment method is currently unavailable'});
  const last4=String(req.body.senderLast4||'').replace(/\D/g,'').slice(-4),trx=String(req.body.transactionId||'').trim();
  if(['bkash','nagad'].includes(method)&&last4.length!==4&&!trx)return res.status(400).json({success:false,message:'Enter the sender account last 4 digits or a transaction ID'});
  const conn=await pool.getConnection();
  try{
    await conn.beginTransaction();const items=await getCheckoutItems(req.user.id,conn,true);if(!items.length)throw Object.assign(new Error('Cart is empty'),{status:400});
    let subtotal=0;const allocations=new Map();
    for(const it of items){const needed=Number(it.quantity)*Math.max(1,Number(it.unit_multiplier||1));const [batches]=await conn.execute('SELECT id,remaining_quantity,expiry_date FROM inventory_batches WHERE product_id=? AND expiry_date>CURDATE() AND remaining_quantity>0 ORDER BY expiry_date ASC,id ASC FOR UPDATE',[it.id]);const stock=batches.reduce((sum,b)=>sum+Number(b.remaining_quantity||0),0);if(stock<needed)throw Object.assign(new Error(`Insufficient stock: ${it.name}`),{status:409});allocations.set(it.id+'-'+it.price_type,{batches,needed});if(it.prescription_required){const [[p]]=await conn.query("SELECT id FROM prescriptions WHERE user_id=? AND status='approved' ORDER BY id DESC LIMIT 1",[req.user.id]);if(!p)throw Object.assign(new Error(`Approved prescription required for ${it.name}`),{status:400});}subtotal+=priceFor(it,it.price_type)*Number(it.quantity)}
    const totals=await calculateTotals(req,subtotal,conn);const num=`ORD-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Date.now().toString().slice(-6)}`;const initial=items.some(x=>x.prescription_required)?'prescription_review':'confirmed';
    const [ox]=await conn.execute('INSERT INTO orders(user_id,order_number,subtotal,discount,shipping_fee,total,payment_method,payment_sender_last4,payment_transaction_id,payment_status,status,address_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[req.user.id,num,money(subtotal),money(totals.discount),money(totals.shipping),money(totals.total),method,last4||null,trx||null,method==='cod'?'pending':'processing',initial,JSON.stringify(totals.address||{})]);
    await conn.execute('INSERT INTO payments(order_id,provider,transaction_ref,amount,status,payload_json) VALUES(?,?,?,?,?,?)',[ox.insertId,method,trx||null,money(totals.total),method==='cod'?'pending':'processing',JSON.stringify({mode:method==='cod'?'cod':'manual_mobile_payment',senderLast4:last4||null})]);
    for(const it of items){const unitPrice=priceFor(it,it.price_type),mult=Math.max(1,Number(it.unit_multiplier||1)),totalUnits=Number(it.quantity)*mult,pct=Math.max(0,Math.min(99.99,Number(it.discount_percent||0))),listPrice=pct>0?unitPrice/(1-pct/100):unitPrice,itemSaving=Math.max(0,(listPrice-unitPrice)*Number(it.quantity));await conn.execute('INSERT INTO order_items(order_id,product_id,product_name,sku,image_url,unit_price,discount,price_type,units_per_pack,total_units,quantity,subtotal) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[ox.insertId,it.id,it.name,it.sku,it.image,money(unitPrice),money(itemSaving),it.price_type,mult,totalUnits,it.quantity,money(unitPrice*Number(it.quantity))]);let remain=totalUnits;for(const b of allocations.get(it.id+'-'+it.price_type)?.batches||[]){if(remain<=0)break;const take=Math.min(remain,Number(b.remaining_quantity||0));if(take<=0)continue;await conn.execute('UPDATE inventory_batches SET remaining_quantity=remaining_quantity-? WHERE id=?',[take,b.id]);await conn.execute('INSERT INTO inventory_movements(product_id,batch_id,type,quantity,reference_type,reference_id,note) VALUES(?,?,?,?,?,?,?)',[it.id,b.id,'sale',-take,'order',ox.insertId,`Checkout (${it.price_type})`]);remain-=take}if(remain!==0)throw Object.assign(new Error(`Unable to allocate stock safely for ${it.name}`),{status:409});}
    if(totals.coupon)await conn.execute('INSERT INTO coupon_usages(coupon_id,user_id,order_id) VALUES(?,?,?)',[totals.coupon.id,req.user.id,ox.insertId]);await conn.execute('INSERT INTO order_status_history(order_id,status,note) VALUES(?,?,?)',[ox.insertId,initial,'Order placed']);await conn.execute('DELETE FROM cart_items WHERE user_id=?',[req.user.id]);await conn.execute('INSERT INTO notifications(user_id,type,title,message) VALUES(?,?,?,?)',[req.user.id,'order','Order placed',`Your order ${num} has been placed.`]);await conn.commit();res.status(201).json({success:true,data:{id:ox.insertId,orderNumber:num,total:money(totals.total),paymentMode:method,status:initial}});
  }catch(e){await conn.rollback();throw e}finally{conn.release()}
}));

r.get('/notifications',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 100',[req.user.id])})));
r.patch('/notifications/:id/read',asyncHandler(async(req,res)=>{await query('UPDATE notifications SET is_read=1 WHERE id=? AND user_id=?',[req.params.id,req.user.id]);res.json({success:true})}));
r.patch('/notifications/read-all',asyncHandler(async(req,res)=>{await query('UPDATE notifications SET is_read=1 WHERE user_id=?',[req.user.id]);res.json({success:true})}));
r.get('/reviews',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT r.*,p.name product_name FROM reviews r JOIN products p ON p.id=r.product_id WHERE r.user_id=? ORDER BY r.id DESC',[req.user.id])})));
r.post('/products/:id/reviews',asyncHandler(async(req,res)=>{const rating=Math.max(1,Math.min(5,Number(req.body.rating||0)));const delivered=(await query("SELECT 1 FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.user_id=? AND oi.product_id=? AND o.status='delivered' LIMIT 1",[req.user.id,req.params.id]))[0];await query("INSERT INTO reviews(user_id,product_id,rating,title,review,status,verified_purchase) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),title=VALUES(title),review=VALUES(review),status='pending'",[req.user.id,req.params.id,rating,req.body.title||'',req.body.review||'','pending',delivered?1:0]);res.status(201).json({success:true,message:'Review submitted for moderation'})}));
r.post('/orders/:id/returns',asyncHandler(async(req,res)=>{const o=(await query("SELECT id FROM orders WHERE id=? AND user_id=? AND status='delivered'",[req.params.id,req.user.id]))[0];if(!o)return res.status(400).json({success:false,message:'Only delivered orders can be returned'});if((await query("SELECT id FROM returns WHERE order_id=? AND status NOT IN ('rejected','closed')",[o.id]))[0])return res.status(409).json({success:false,message:'A return request already exists'});const x=await query('INSERT INTO returns(order_id,user_id,reason,comments,status) VALUES(?,?,?,?,?)',[o.id,req.user.id,req.body.reason||'Other',req.body.comments||'','requested']);await query("UPDATE orders SET status='return_requested' WHERE id=?",[o.id]);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.get('/returns',asyncHandler(async(req,res)=>res.json({success:true,data:await query('SELECT * FROM returns WHERE user_id=? ORDER BY id DESC',[req.user.id])})));
r.post('/service-bookings',asyncHandler(async(req,res)=>{const x=await query('INSERT INTO service_bookings(user_id,service_id,booking_date,booking_time,contact_phone,notes,status) VALUES(?,?,?,?,?,?,?)',[req.user.id,req.body.serviceId,req.body.date,req.body.time,req.body.phone||req.user.phone,req.body.notes||'','pending']);res.status(201).json({success:true,data:{id:x.insertId}})}));
r.get('/service-bookings',asyncHandler(async(req,res)=>res.json({success:true,data:await query(`SELECT b.*,s.name service_name FROM service_bookings b LEFT JOIN services s ON s.id=b.service_id WHERE b.user_id=? ORDER BY b.id DESC`,[req.user.id])})));

export default r;
