import {useMemo,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Plus,Search,Pencil,Trash2,X,Save,Image as ImageIcon} from 'lucide-react';
import http,{assetUrl} from '../../api/http';
import RichTextEditor from './RichTextEditor';

const bool=v=>v===1||v===true||v==='1'||v==='true';
const display=(row,col)=>{const v=row[col.key];if(col.render)return col.render(row);if(col.type==='boolean')return <span className={`badge ${bool(v)?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{bool(v)?'Active':'Inactive'}</span>;if(col.type==='image')return v?<img src={assetUrl(v)} className="h-12 w-12 rounded-xl object-cover"/>:<span className="text-slate-300">—</span>;return v??'—'};

export default function AdminResourcePage({title,description,endpoint,fields=[],columns=[],idKey='id',canDelete=true,createLabel='Add New',readOnly=false,onEditTransform,onSubmitTransform}){
  const qc=useQueryClient();const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const query=useQuery({queryKey:['admin-resource',endpoint],queryFn:()=>http.get(endpoint).then(r=>r.data.data||[])});const rows=query.data||[];
  const filtered=useMemo(()=>{const s=q.trim().toLowerCase();if(!s)return rows;return rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(s)))},[rows,q]);
  const sourceValue=(row,f)=>row?.[f.source||f.key]??f.defaultValue??(f.type==='checkbox'?false:'');
  const startCreate=()=>{const next={};for(const f of fields)next[f.key]=f.defaultValue??(f.type==='checkbox'?true:'');setForm(next);setEditing(null);setError('');setOpen(true)};
  const startEdit=row=>{let next={};for(const f of fields)next[f.key]=sourceValue(row,f);if(onEditTransform)next=onEditTransform(row,next)||next;setForm(next);setEditing(row);setError('');setOpen(true)};
  const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  const save=async()=>{setBusy(true);setError('');try{let payload={...form};if(onSubmitTransform)payload=onSubmitTransform(payload,editing)||payload;const hasFile=fields.some(f=>f.type==='file'&&payload[f.key] instanceof File);let body=payload;if(hasFile){body=new FormData();for(const [k,v] of Object.entries(payload)){if(v===undefined||v===null)continue;body.append(k,v instanceof File?v:(typeof v==='boolean'?(v?'1':'0'):v))}}if(editing)await http.patch(`${endpoint}/${editing[idKey]}`,body);else await http.post(endpoint,body);setOpen(false);await qc.invalidateQueries({queryKey:['admin-resource',endpoint]});await qc.invalidateQueries({queryKey:['home']});await qc.invalidateQueries({queryKey:['site-config']});localStorage.setItem('sc-site-refresh',String(Date.now()));window.dispatchEvent(new Event('sc-site-refresh'))}catch(e){setError(e.response?.data?.message||e.message||'Could not save')}finally{setBusy(false)}};
  const remove=async row=>{if(!window.confirm(`Delete/deactivate “${row.name||row.title||row.code||row[idKey]}”?`))return;try{await http.delete(`${endpoint}/${row[idKey]}`);await qc.invalidateQueries({queryKey:['admin-resource',endpoint]});await qc.invalidateQueries({queryKey:['home']});await qc.invalidateQueries({queryKey:['site-config']});localStorage.setItem('sc-site-refresh',String(Date.now()))}catch(e){alert(e.response?.data?.message||'Could not delete')}};
  return <>
    <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="admin-page-title">{title}</h1>{description&&<p className="mt-1 max-w-3xl text-sm text-slate-500">{description}</p>}</div>{!readOnly&&<button className="btn-primary" onClick={startCreate}><Plus size={18}/>{createLabel}</button>}</div>
    <div className="admin-section mt-6 p-0 overflow-hidden"><div className="flex items-center gap-3 border-b p-4"><Search size={18} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-transparent text-sm" placeholder={`Search ${title.toLowerCase()}...`}/><span className="text-xs text-slate-400">{filtered.length} records</span></div><div className="overflow-x-auto"><table className="admin-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}{!readOnly&&<th className="text-right">Actions</th>}</tr></thead><tbody>{filtered.map(row=><tr key={row[idKey]}>{columns.map(c=><td key={c.key}>{display(row,c)}</td>)}{!readOnly&&<td><div className="flex justify-end gap-1"><button onClick={()=>startEdit(row)} className="btn-ghost"><Pencil size={16}/>Edit</button>{canDelete&&<button onClick={()=>remove(row)} className="btn-ghost text-rose-600"><Trash2 size={16}/></button>}</div></td>}</tr>)}{!filtered.length&&<tr><td colSpan={columns.length+1} className="py-12 text-center text-slate-400">No records found.</td></tr>}</tbody></table></div></div>
    {open&&<div className="fixed inset-0 z-[80] overflow-y-auto bg-slate-50"><div className="min-h-screen"><div className="sticky top-0 z-10 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6 lg:px-8"><div><h2 className="text-2xl font-black">{editing?'Edit':'Add'} {title.replace(/s$/,'')}</h2><p className="text-sm text-slate-500">Full-page editor. Changes are saved to MySQL and reflected on the website.</p></div><button onClick={()=>setOpen(false)} className="btn-ghost"><X/></button></div></div><div className="mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6 lg:px-8"><div className="admin-section grid gap-5 md:grid-cols-2">{fields.map(f=><div key={f.key} className={f.full?'md:col-span-2':''}><Field f={f} value={form[f.key]} set={v=>set(f.key,v)} form={form}/></div>)}</div>{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}<div className="sticky bottom-4 flex justify-end gap-3 rounded-2xl border bg-white/95 p-4 shadow-lg backdrop-blur"><button className="btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn-primary" disabled={busy} onClick={save}><Save size={17}/>{busy?'Saving...':'Save Changes'}</button></div></div></div></div>}
  </>;
}

function Field({f,value,set,form}){
  if(f.hidden)return null;const options=typeof f.options==='function'?f.options(form):f.options;
  return <div className={f.full?'':'max-w-full'}><label className="label">{f.label}{f.required&&<span className="text-rose-500"> *</span>}</label>
    {f.type==='rich'?<RichTextEditor value={value||''} onChange={set} placeholder={f.placeholder||`Write ${f.label.toLowerCase()}...`} minHeight={f.minHeight||140}/>
    :f.type==='checkbox'?<label className="inline-flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><input type="checkbox" checked={bool(value)} onChange={e=>set(e.target.checked)} className="h-4 w-4 accent-[rgb(var(--brand-600))]"/><span className="text-sm font-semibold">{f.checkboxLabel||f.label}</span></label>
    :f.type==='select'?<select className="input" value={value??''} onChange={e=>set(e.target.value)}><option value="">{f.placeholder||'Select...'}</option>{(options||[]).map(o=>{const x=typeof o==='string'?{value:o,label:o}:o;return <option key={x.value} value={x.value}>{x.label}</option>})}</select>
    :f.type==='file'?<div><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 hover:border-brand-400"><ImageIcon className="text-brand-600"/><span className="text-sm">{value instanceof File?value.name:'Choose image'}</span><input type="file" accept={f.accept||'image/*'} className="hidden" onChange={e=>set(e.target.files?.[0]||null)}/></label>{typeof value==='string'&&value&&<img src={assetUrl(value)} className="mt-3 h-24 rounded-xl border object-cover"/>}</div>
    :f.type==='textarea'?<textarea className="input min-h-28" value={value??''} onChange={e=>set(e.target.value)} placeholder={f.placeholder}/>
    :<input className="input" type={f.type||'text'} value={value??''} onChange={e=>set(e.target.value)} placeholder={f.placeholder}/>} {f.help&&<p className="admin-field-help">{f.help}</p>}
  </div>;
}
