import { useEffect, useState } from 'react';
import { Navigate, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Eye, EyeOff, LockKeyhole, ShieldCheck } from 'lucide-react';
import http from '../../api/http';
import { useAuthStore } from '../../store/auth';
import { useSiteConfig, setting } from '../../hooks/useSiteConfig';

export default function AdminLogin({ dynamic = false }) {
  const { adminSlug } = useParams(); const loc = useLocation(); const nav = useNavigate(); const { data: cfg, isLoading } = useSiteConfig(); const setSession = useAuthStore(s => s.setSession); const user = useAuthStore(s => s.user); const hydrated = useAuthStore(s => s.hydrated);
  const [f, setF] = useState({ identifier: 'admin@shasthocare.local', password: 'Admin@12345' }); const [show, setShow] = useState(false); const [err, setErr] = useState(''); const [busy, setBusy] = useState(false);
  const configured = setting(cfg, 'admin.panel_slug', 'control-center');
  useEffect(() => { setErr('') }, [loc.pathname]);
  if (dynamic && !isLoading && adminSlug !== configured) return <Navigate to="/not-found" replace />;
  if (hydrated && user?.isAdmin) return <Navigate to="/admin" replace />;
  const submit = async e => { e.preventDefault(); setBusy(true); setErr(''); try { const r = await http.post('/auth/login', f); if (!r.data.data.user?.isAdmin) { useAuthStore.getState().logoutLocal(); setErr('This account does not have admin access.'); return } setSession(r.data.data); nav('/admin', { replace: true }) } catch (e) { setErr(e.response?.data?.message || 'Admin sign in failed') } finally { setBusy(false) } };
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-4"><div className="w-full max-w-md"><div className="mb-5 text-center text-white"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-brand-600 text-2xl font-black shadow-xl">+</span><h1 className="mt-4 text-3xl font-black">{setting(cfg, 'brand.name', 'ShasthoCare')} Admin</h1><p className="mt-1 text-sm text-slate-400">Secure control center</p></div><form onSubmit={submit} className="rounded-3xl bg-white p-7 shadow-2xl"><div className="mb-5 flex items-start gap-3 rounded-2xl bg-brand-50 p-4 text-brand-900"><ShieldCheck className="mt-0.5 shrink-0" size={20} /><div><div className="font-black">Administrator sign in</div><div className="mt-1 text-xs leading-5 text-slate-600">Roles are checked on the server. The configurable alias is <b>/{configured}/login</b>; <b>/admin/login</b> always remains available as a recovery path.</div></div></div><label className="label">Email / Gmail or phone</label><input autoComplete="username" className="input" value={f.identifier} onChange={e => setF({ ...f, identifier: e.target.value })} /><label className="label mt-4">Password</label><div className="relative"><input autoComplete="current-password" className="input pr-12" type={show ? 'text' : 'password'} value={f.password} onChange={e => setF({ ...f, password: e.target.value })} /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{err && <div className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{err}</div>}<button disabled={busy} className="btn-primary mt-5 w-full"><LockKeyhole size={18} />{busy ? 'Signing in...' : 'Sign in to Admin'}</button><p className="mt-5 text-center text-xs text-slate-400">Development seed: admin@shasthocare.local / Admin@12345. Change it immediately from Admin → Settings.</p></form></div></main>;
}
