import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'react-router-dom';
import http from '../../api/http';
export default function EmailSettings(){
 const qc=useQueryClient(),[form,setForm]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const settings=useQuery({queryKey:['integration-settings','email'],queryFn:()=>http.get('/admin/email-settings').then(r=>r.data.data)});
 const health=useQuery({queryKey:['integration-health'],queryFn:()=>http.get('/admin/integration-health').then(r=>r.data.data)});
 const flags=useQuery({queryKey:['integration-settings','notification'],queryFn:()=>http.get('/admin/notification-settings').then(r=>r.data.data)});
 useEffect(()=>{if(settings.data)setForm({...settings.data,password:''})},[settings.data]);
 const set=(key,value)=>setForm(old=>({...old,[key]:value}));
 const run=async task=>{setBusy(true);setMessage('');try{await task()}catch(e){setMessage(e.response?.data?.message||'Request failed. Check server and database configuration.')}finally{setBusy(false)}};
 const save=e=>{e.preventDefault();run(async()=>{const r=await http.put('/admin/email-settings',{...form,driver:'smtp'});setForm({...r.data.data,password:''});qc.invalidateQueries({queryKey:['integration-settings','email']});setMessage('Saved in the database. No SMTP or IMAP values need to be copied to .env.')})};
 const test=type=>run(async()=>{if(type==='delivery'){await http.post('/admin/notification-test',{channel:'email'});setMessage('SMTP accepted the test email for your signed-in admin email address. Check Inbox and Spam.')}else{await http.post('/admin/email-settings/test-'+type);setMessage(type.toUpperCase()+' connection successful.')}});
 const field=(key,label,type='text',hint='')=><label><span className="label">{label}</span><input type={type} className="input" autoComplete={type==='password'?'new-password':'off'} value={form[key]??''} onChange={e=>set(key,e.target.value)} placeholder={key==='password'&&form.password_configured?'Saved — leave blank to keep':''}/>{hint&&<span className="mt-1 block text-xs text-slate-500">{hint}</span>}</label>;
 return <><h1 className="admin-page-title">Email Settings</h1><div className="admin-section mt-5 text-sm leading-6"><b>cPanel mailbox setup</b><p>Open cPanel → Email Accounts → Connect Devices. Copy the secure outgoing server, full email address and mailbox password below. Save once here; do not add SMTP or IMAP settings to .env.</p><p className="mt-2">Use the mailbox password, not your cPanel login password. Port 465 uses SSL/TLS; port 587 uses STARTTLS when supported by your host.</p></div>
 {health.data?.encryption_ready===false&&<div role="alert" className="mt-4 rounded-xl bg-amber-50 p-4 text-sm">Server encryption key is missing. Run <code>npm --prefix server run setup:key</code> from the project folder, then restart the Node app. This is a one-time server setup; keep the key backed up.</div>}
 {flags.data&&!Number(flags.data.email_enabled)&&<p role="alert" className="mt-4 rounded-xl bg-amber-50 p-4">The notification email channel is off. <Link className="underline" to="/admin/settings/notification">Enable Email there</Link> to send messages.</p>}
 {settings.isError?<p role="alert" className="mt-5 text-red-600">Could not load settings. Apply database migrations and check your admin permission.</p>:!form?<p className="mt-5">Loading…</p>:<form onSubmit={save} className="admin-section mt-5 space-y-5"><label className="flex gap-3 font-bold"><input type="checkbox" checked={Boolean(Number(form.status))} onChange={e=>set('status',e.target.checked)}/>Enable outgoing email</label><div className="grid gap-5 md:grid-cols-2">{field('smtp_host','Outgoing server (SMTP)','text','Use the exact hostname displayed by cPanel.')}{field('smtp_port','SMTP port','number')}
 <label><span className="label">Connection security</span><select className="input" value={form.encryption} onChange={e=>{set('encryption',e.target.value);set('smtp_port',e.target.value==='tls'?465:587)}}><option value="tls">SSL/TLS — port 465 (cPanel)</option><option value="starttls">STARTTLS — port 587</option></select></label>{field('username','Mailbox email / username','email')}{field('password','Mailbox password','password')}{field('sender_name','Sender display name')}{field('sender_email','Sender email','email','Usually the same address as your mailbox username.')}</div>
 <div className="border-t pt-5"><label className="flex gap-3 font-bold"><input type="checkbox" checked={Boolean(Number(form.imap_enabled))} onChange={e=>set('imap_enabled',e.target.checked)}/>Enable inbox in Email Center (optional)</label><p className="mt-2 text-sm text-slate-500">Only needed to read/reply to mailbox messages in the admin panel. Uses the same mailbox username and password above.</p>{Boolean(Number(form.imap_enabled))&&<div className="mt-4 grid gap-5 md:grid-cols-2">{field('imap_host','Incoming server (IMAP)')}{field('imap_port','Secure IMAP port','number','Normally 993; SSL/TLS is required.')}{field('imap_sent_mailbox','Sent folder name','text','Use your mailbox’s exact folder name, usually Sent.')}</div>}</div>
 <p className="text-xs text-slate-500">Existing secrets are retained when the password is blank. Save changes before testing.</p>{message&&<p role="status" className="rounded-xl bg-slate-100 p-4">{message}</p>}<div className="flex flex-wrap gap-3"><button disabled={busy} className="btn-primary">{busy?'Please wait…':'Save Settings'}</button><button type="button" disabled={busy} className="btn-secondary" onClick={()=>test('smtp')}>Test SMTP connection</button><button type="button" disabled={busy} className="btn-secondary" onClick={()=>test('delivery')}>Send test to my admin email</button>{Boolean(Number(form.imap_enabled))&&<button type="button" disabled={busy} className="btn-secondary" onClick={()=>test('imap')}>Test inbox connection</button>}</div></form>}</>
}
