import EmailSettings from './EmailSettings';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import http from '../../api/http';
import AdminResourcePage from '../../components/admin/AdminResourcePage';
const definitions={
 payment:[['gateway_name','Gateway name'],['gateway_type','Gateway type','readonly'],['status','Enable gateway','checkbox'],['mode','Mode','select',['sandbox','live']],['api_url','API URL (blank uses official endpoint)'],['merchant_id','Merchant / Store ID'],['api_key','API key','password'],['secret_key','Secret / Store password','password'],['success_url','Success return URL'],['fail_url','Failed return URL'],['cancel_url','Cancel return URL']],
 sms:[['status','Enable SMS','checkbox'],['provider_name','Provider adapter','select',['generic_json']],['api_url','API URL'],['api_key','API key','password'],['secret_key','Secret key','password'],['sender_id','Sender ID'],['country_code','Country code']],
 notification:[['email_enabled','Enable email channel','checkbox'],['sms_enabled','Enable SMS channel','checkbox'],['in_app_enabled','Enable in-app notifications','checkbox'],['admin_email','New-order admin email','email'],['admin_phone','New-order admin phone']],
 analytics:[['status','Enable analytics and tracking','checkbox'],['meta_pixel_status','Enable Meta Pixel','checkbox'],['meta_pixel_id','Meta Pixel ID'],['google_analytics_status','Enable Google Analytics','checkbox'],['ga_measurement_id','GA4 measurement ID'],['gtm_status','Enable Google Tag Manager','checkbox'],['gtm_container_id','GTM container ID'],['custom_header_script','Custom header scripts','textarea'],['custom_footer_script','Custom footer scripts','textarea'],['retention_days','Activity retention days','number']]
};
export default function IntegrationSettings({kind}){return kind==='email'?<EmailSettings/>:<GenericSettings kind={kind}/>};
function GenericSettings({kind}){const qc=useQueryClient();const [form,setForm]=useState(null),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const result=useQuery({queryKey:['integration-settings',kind],queryFn:()=>http.get('/admin/'+kind+'-settings').then(r=>r.data.data)});useEffect(()=>{const d=result.data;setForm(kind==='payment'?(d?.find(x=>String(x.id)===selected)||d?.[0]):d)},[result.data,kind,selected]);
 const save=async e=>{e.preventDefault();setBusy(true);try{const d=(await http.put('/admin/'+kind+'-settings'+(kind==='payment'?'/'+form.id:''),form)).data.data;setForm(d);setMessage('Settings saved');qc.invalidateQueries({queryKey:['integration-settings',kind]});qc.invalidateQueries({queryKey:['payment-methods']})}catch(e){setMessage(e.response?.data?.message||'Could not save settings')}finally{setBusy(false)}};
 const test=async()=>{setBusy(true);try{await http.post('/admin/notification-test',{channel:kind});setMessage('Provider accepted the test message sent to your account contact.')}catch(e){setMessage(e.response?.data?.message||'Test delivery failed')}finally{setBusy(false)}};
 return <><h1 className="admin-page-title capitalize">{kind==='analytics'?'Analytics & Pixel':kind} Settings</h1>{kind==='payment'&&<p className="mt-2 text-sm text-slate-500">SSLCOMMERZ supports online checkout. Stripe, PayPal, bKash and Nagad are reserved adapter configurations and cannot be activated yet. Existing manual mobile payments remain in Website Settings.</p>}{kind==='sms'&&<p className="mt-2 text-sm text-slate-500">Generic JSON adapter: your provider endpoint must accept the documented request and return success: true. Allowlist its host on the server.</p>}{kind==='analytics'&&<p className="mt-2 text-sm text-slate-500">Tracking runs only after visitor consent. Custom scripts execute with storefront privileges; use trusted code. Avoid installing the same pixel directly and through GTM.</p>}{result.isError&&<p role="alert">Could not load settings.</p>}{!form?<p className="mt-6">Loading…</p>:<form onSubmit={save} className="admin-section mt-6 space-y-5">{kind==='payment'&&<select aria-label="Gateway" className="input" value={form.id} onChange={e=>setSelected(e.target.value)}>{result.data?.map(x=><option key={x.id} value={x.id}>{x.gateway_name}</option>)}</select>}<div className="grid gap-5 md:grid-cols-2">{definitions[kind].map(([key,label,type='text',options])=><label className={type==='textarea'?'md:col-span-2':''} key={key}><span className="label">{label}</span>{type==='checkbox'?<input type="checkbox" checked={Boolean(Number(form[key]))} onChange={e=>setForm({...form,[key]:e.target.checked})}/>:type==='select'?<select className="input" value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}>{options.map(o=><option key={o}>{o}</option>)}</select>:type==='textarea'?<textarea className="input min-h-32 font-mono text-sm" value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input className="input" readOnly={type==='readonly'} type={type==='readonly'?'text':type} autoComplete={type==='password'?'new-password':'off'} placeholder={type==='password'&&form[key+'_configured']?'Configured — leave blank to keep':''} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div>{message&&<p role="status" className="rounded-xl bg-slate-100 p-3">{message}</p>}<div className="flex gap-3"><button className="btn-primary" disabled={busy}>Save Settings</button>{['email','sms'].includes(kind)&&<button type="button" className="btn-secondary" disabled={busy} onClick={test}>Send Test to My Account</button>}</div></form>}{kind==='notification'&&<div className="mt-8"><Templates/><Deliveries/></div>}</>}
function Templates(){return <AdminResourcePage title="Message Templates" description="Variables: {{name}}, {{email}}, {{order_id}}, {{amount}}, {{status}}, {{otp}}. Plain text keeps customer values safe. Welcome and account security emails remain under Email Templates." endpoint="/admin/message-templates" canDelete={false} createLabel="" columns={[{key:'event_name',label:'Event'},{key:'channel',label:'Channel'},{key:'subject',label:'Subject'}]} fields={[{key:'subject',label:'Subject'},{key:'body',label:'Message body',type:'textarea',full:true},{key:'status',label:'Enabled',type:'checkbox'}]}/>}
function Deliveries(){const {data=[]}=useQuery({queryKey:['deliveries'],queryFn:()=>http.get('/admin/notification-deliveries').then(r=>r.data.data),refetchInterval:15000});return <div className="admin-section mt-6 overflow-x-auto"><h2 className="text-xl font-bold">Recent Deliveries</h2><table className="admin-table"><thead><tr><th>Event</th><th>Channel</th><th>Status</th><th>Attempts</th><th>Details</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.event_key}</td><td>{x.channel}</td><td>{x.status}</td><td>{x.attempts}</td><td>{x.last_error}</td></tr>)}</tbody></table></div>}
export function QuantityOffers(){const {data}=useQuery({queryKey:['offer-product-options'],queryFn:async()=>{let page=1,rows=[],result;do{result=(await http.get('/admin/products',{params:{limit:100,page}})).data;rows.push(...result.data);page++}while(page<=result.pagination.pages);return rows}});const products=Array.isArray(data)?data:data?.items||data?.products||[];return <AdminResourcePage title="Quantity Offers" description="Choose a product and pack size. Example: 3 strips for ৳240. Complete bundles receive the offer price; leftovers use the usual pack price. The cheapest eligible single offer is applied automatically, then any valid coupon." endpoint="/admin/quantity-offers" columns={[{key:'name',label:'Offer'},{key:'product_name',label:'Product'},{key:'price_type',label:'Pack'},{key:'minimum_quantity',label:'Bundle quantity'},{key:'bundle_price',label:'Bundle price'},{key:'is_active',label:'Active',type:'boolean'}]} onEditTransform={(row,f)=>({...f,start_date:String(row.start_date).slice(0,16),end_date:String(row.end_date).slice(0,16)})} fields={[{key:'name',label:'Offer name',required:true},{key:'product_id',label:'Product',type:'select',options:products.map(p=>({value:p.id,label:p.name}))},{key:'price_type',label:'Pack type',type:'select',options:['unit','strip','box'],defaultValue:'unit'},{key:'minimum_quantity',label:'Quantity per bundle',type:'number',defaultValue:3},{key:'bundle_price',label:'Total price per bundle',type:'number'},{key:'start_date',label:'Starts (UTC)',type:'datetime-local'},{key:'end_date',label:'Ends (UTC)',type:'datetime-local'},{key:'is_active',label:'Enabled',type:'checkbox',defaultValue:true}]}/>}
