import {useEffect,useMemo,useState} from 'react';
import {useNavigate,useParams,Link} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,Save,Upload,Star,Trash2,Braces,FileText,RefreshCw} from 'lucide-react';
import http,{assetUrl} from '../../api/http';
import RichTextEditor from '../../components/admin/RichTextEditor';

const slugify=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9\u0980-\u09ff]+/g,'-').replace(/^-+|-+$/g,'');
const empty={name:'',slug:'',sku:'',barcode:'',genericName:'',brandId:'',manufacturerId:'',categoryId:'',productType:'Medicine',dosageForm:'Tablet',strength:'',packSize:'',unitLabel:'Tablet',unitPrice:'',unitsPerStrip:10,stripPrice:'',stripsPerBox:10,unitsPerBox:100,boxPrice:'',discountPercent:20,shortDescription:'',description:'',ingredients:'',usageInfo:'',warnings:'',storageInfo:'',regularPrice:'',salePrice:'',costPrice:'',taxRate:0,lowStockThreshold:10,seoTitle:'',seoDescription:'',prescriptionRequired:false,featured:false,bestSeller:false,newArrival:false,active:true};
const fromDb=p=>({name:p.name||'',slug:p.slug||'',sku:p.sku||'',barcode:p.barcode||'',genericName:p.generic_name||'',brandId:p.brand_id||'',manufacturerId:p.manufacturer_id||'',categoryId:p.category_id||'',productType:p.product_type||'',dosageForm:p.dosage_form||'',strength:p.strength||'',packSize:p.pack_size||'',unitLabel:p.unit_label||'Tablet',unitPrice:p.unit_price??'',unitsPerStrip:p.units_per_strip??10,stripPrice:p.strip_price??'',stripsPerBox:p.strips_per_box??10,unitsPerBox:p.units_per_box??100,boxPrice:p.box_price??'',discountPercent:p.discount_percent??20,shortDescription:p.short_description||'',description:p.description||'',ingredients:p.ingredients||'',usageInfo:p.usage_info||'',warnings:p.warnings||'',storageInfo:p.storage_info||'',regularPrice:p.regular_price??'',salePrice:p.sale_price??'',costPrice:p.cost_price??'',taxRate:p.tax_rate??0,lowStockThreshold:p.low_stock_threshold??10,seoTitle:p.seo_title||'',seoDescription:p.seo_description||'',prescriptionRequired:Boolean(p.prescription_required),featured:Boolean(p.is_featured),bestSeller:Boolean(p.is_best_seller),newArrival:Boolean(p.is_new_arrival),active:Boolean(p.is_active)});

export default function ProductForm(){
  const {id}=useParams();const editing=Boolean(id);const nav=useNavigate();const qc=useQueryClient();const [tab,setTab]=useState('form');const [f,setF]=useState(empty);const [cover,setCover]=useState(null);const [extras,setExtras]=useState([]);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const [json,setJson]=useState(JSON.stringify({name:'Demo Product',slug:'demo-product',sku:'DEMO-JSON-001',genericName:'Demo ingredient',categoryId:1,brandId:1,manufacturerId:1,productType:'Medicine',dosageForm:'Tablet',strength:'500 mg',packSize:'10 tablets',shortDescription:'<p>Short formatted description.</p>',description:'<p><strong>Full product description</strong> can contain formatted text.</p>',ingredients:'<p>Ingredient information.</p>',usageInfo:'<p>Use according to the package label or professional guidance.</p>',warnings:'<p>Safety and warning information.</p>',storageInfo:'<p>Store according to the package label.</p>',regularPrice:120,discountPercent:20,salePrice:96,costPrice:70,unitLabel:'Tablet',unitPrice:9.6,unitsPerStrip:10,stripPrice:96,stripsPerBox:10,unitsPerBox:100,boxPrice:900,prescriptionRequired:false,featured:true,bestSeller:false,newArrival:true,active:true,images:[{url:'https://example.com/product-cover.jpg',isPrimary:true,altText:'Demo product cover'}],batches:[{batchNumber:'JSON-BATCH-001',manufacturingDate:'2026-01-01',expiryDate:'2028-01-01',purchasePrice:70,sellingPrice:100,quantity:50}]},null,2));
  const refs=useQuery({queryKey:['admin-product-refs'],queryFn:async()=>{const [c,b,m]=await Promise.all([http.get('/admin/categories'),http.get('/admin/brands'),http.get('/admin/manufacturers')]);return {categories:c.data.data,brands:b.data.data,manufacturers:m.data.data}}});
  const product=useQuery({queryKey:['admin-product',id],enabled:editing,queryFn:()=>http.get('/admin/products/'+id).then(r=>r.data.data)});
  useEffect(()=>{if(product.data)setF(fromDb(product.data))},[product.data]);
  const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const save=async()=>{setBusy(true);setErr('');try{let productId=id;if(editing){await http.patch('/admin/products/'+id,f)}else{const r=await http.post('/admin/products',f);productId=r.data.data.id}if((cover||extras.length)&&productId){const fd=new FormData();if(cover)fd.append('cover',cover);for(const x of extras)fd.append('images',x);await http.post(`/admin/products/${productId}/images`,fd)}await qc.invalidateQueries({queryKey:['adminProducts']});nav('/admin/products')}catch(e){setErr(e.response?.data?.message||e.message||'Could not save product')}finally{setBusy(false)}};
  const formatJson=()=>{try{setJson(JSON.stringify(JSON.parse(json),null,2));setErr('')}catch(e){setErr('Invalid JSON: '+e.message)}};
  const importJson=async()=>{setBusy(true);setErr('');try{const parsed=JSON.parse(json);const payload=Array.isArray(parsed)?{products:parsed}:Array.isArray(parsed?.products)?parsed:parsed?.product?parsed:{product:parsed};await http.post('/admin/products/import-json',payload);await qc.invalidateQueries({queryKey:['adminProducts']});nav('/admin/products')}catch(e){setErr(e.response?.data?.message||e.message||'Invalid JSON or import failed')}finally{setBusy(false)}};
  const imageAction=async(imageId,action)=>{if(action==='delete'&&!window.confirm('Delete this product image?'))return;if(action==='primary')await http.patch(`/admin/products/${id}/images/${imageId}`,{isPrimary:true});else await http.delete(`/admin/products/${id}/images/${imageId}`);await product.refetch()};
  if(editing&&product.isLoading)return <div className="admin-section">Loading product...</div>;
  return <div className="w-full max-w-none"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link to="/admin/products" className="btn-ghost"><ArrowLeft size={18}/></Link><div><h1 className="admin-page-title">{editing?'Edit Product':'Add Product'}</h1><p className="mt-1 text-sm text-slate-500">Complete medicine/product data, images, SEO, pricing and visibility.</p></div></div><div className="flex rounded-xl border bg-white p-1"><button onClick={()=>setTab('form')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab==='form'?'bg-brand-600 text-white':''}`}><FileText className="mr-1 inline" size={15}/>Form</button>{!editing&&<button onClick={()=>setTab('json')} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab==='json'?'bg-brand-600 text-white':''}`}><Braces className="mr-1 inline" size={15}/>JSON</button>}</div></div>
    {tab==='json'&&!editing?<div className="admin-section mt-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Add product from JSON</h2><p className="mt-1 text-sm text-slate-500">Paste one product object or an array of up to 100 products. External image URLs can be supplied through an <code>images</code> array, and initial FEFO stock can be created with an optional <code>batches</code> array.</p></div><button className="btn-secondary" onClick={formatJson}><RefreshCw size={16}/>Format</button></div><textarea value={json} onChange={e=>setJson(e.target.value)} className="mt-5 min-h-[520px] w-full rounded-xl bg-slate-950 p-5 font-mono text-sm leading-6 text-emerald-200 outline-none" spellCheck="false"/>{err&&<ErrorBox>{err}</ErrorBox>}<button disabled={busy} onClick={importJson} className="btn-primary mt-5"><Braces size={17}/>{busy?'Importing...':'Validate & Import JSON'}</button></div>
    :<div className="mt-6 space-y-6"><Section title="Basic Information" note="Names, slugs and catalog identifiers are fully editable."><Grid><Input label="Product name" value={f.name} set={v=>set('name',v)} required/><div><label className="label">Slug</label><div className="flex gap-2"><input className="input" value={f.slug} onChange={e=>set('slug',e.target.value)}/><button type="button" className="btn-secondary px-3" onClick={()=>set('slug',slugify(f.name))}>Generate</button></div></div><Input label="SKU" value={f.sku} set={v=>set('sku',v)} help="Leave blank on new product to auto-generate."/><Input label="Barcode" value={f.barcode} set={v=>set('barcode',v)}/><Input label="Generic name" value={f.genericName} set={v=>set('genericName',v)}/><Input label="Product type" value={f.productType} set={v=>set('productType',v)}/></Grid></Section>
    <Section title="Classification"><Grid><Select label="Category" value={f.categoryId} set={v=>set('categoryId',v)} options={refs.data?.categories||[]}/><Select label="Brand" value={f.brandId} set={v=>set('brandId',v)} options={refs.data?.brands||[]}/><Select label="Manufacturer" value={f.manufacturerId} set={v=>set('manufacturerId',v)} options={refs.data?.manufacturers||[]}/><Input label="Dosage form" value={f.dosageForm} set={v=>set('dosageForm',v)} placeholder="Tablet, capsule, cream, device..."/><Input label="Strength" value={f.strength} set={v=>set('strength',v)} placeholder="500 mg"/><Input label="Pack size" value={f.packSize} set={v=>set('packSize',v)} placeholder="10 tablets"/></Grid></Section>
    <Section title="Product Content" note="Every long text field includes Bold, Italic, Underline, color, heading, lists, alignment and link controls."><Editor label="Short description" value={f.shortDescription} set={v=>set('shortDescription',v)} minHeight={110}/><Editor label="Full description" value={f.description} set={v=>set('description',v)} minHeight={190}/><div className="grid gap-5 lg:grid-cols-2"><Editor label="Ingredients / Composition" value={f.ingredients} set={v=>set('ingredients',v)}/><Editor label="Usage / Catalog Information" value={f.usageInfo} set={v=>set('usageInfo',v)}/><Editor label="Warnings" value={f.warnings} set={v=>set('warnings',v)}/><Editor label="Storage Information" value={f.storageInfo} set={v=>set('storageInfo',v)}/></div></Section>
    <Section title="Pricing & Inventory" note="Default medicine discount is 20%. You can change the percentage per product. Unit/strip/box quantities control how stock is deducted."><Grid><Input label="Regular / MRP price" type="number" value={f.regularPrice} set={v=>{set('regularPrice',v);const n=Number(v||0),d=Number(f.discountPercent||0);if(n>=0)set('salePrice',(n*(1-d/100)).toFixed(2))}} required/><Input label="Discount (%)" type="number" value={f.discountPercent} set={v=>{set('discountPercent',v);const n=Number(f.regularPrice||0),d=Math.max(0,Math.min(100,Number(v||0)));if(n>=0)set('salePrice',(n*(1-d/100)).toFixed(2))}} help="Default 20% for medicines. Sale price is calculated automatically but can still be edited."/><Input label="Sale price" type="number" value={f.salePrice} set={v=>set('salePrice',v)} required/><Input label="Cost price" type="number" value={f.costPrice} set={v=>set('costPrice',v)}/><Input label="Single unit label" value={f.unitLabel} set={v=>set('unitLabel',v)} placeholder="Tablet / Capsule / Sachet"/><Input label="Single unit price" type="number" value={f.unitPrice} set={v=>set('unitPrice',v)}/><Input label="Units per strip" type="number" value={f.unitsPerStrip} set={v=>set('unitsPerStrip',v)}/><Input label="Strip price" type="number" value={f.stripPrice} set={v=>set('stripPrice',v)}/><Input label="Strips per box" type="number" value={f.stripsPerBox} set={v=>{set('stripsPerBox',v);set('unitsPerBox',Math.max(1,Number(v||1))*Math.max(1,Number(f.unitsPerStrip||1)))}}/><Input label="Units per box" type="number" value={f.unitsPerBox} set={v=>set('unitsPerBox',v)} help="Total physical units deducted when one box is ordered."/><Input label="Box price" type="number" value={f.boxPrice} set={v=>set('boxPrice',v)}/><Input label="Tax rate (%)" type="number" value={f.taxRate} set={v=>set('taxRate',v)}/><Input label="Low-stock threshold" type="number" value={f.lowStockThreshold} set={v=>set('lowStockThreshold',v)} help="Stock is tracked in physical units."/></Grid><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Check label="Active" value={f.active} set={v=>set('active',v)}/><Check label="Prescription required" value={f.prescriptionRequired} set={v=>set('prescriptionRequired',v)}/><Check label="Featured" value={f.featured} set={v=>set('featured',v)}/><Check label="Best seller" value={f.bestSeller} set={v=>set('bestSeller',v)}/><Check label="New arrival" value={f.newArrival} set={v=>set('newArrival',v)}/></div></Section>
    <Section title="Product Images" note="Upload one cover image and multiple extra gallery images. Images are optimized to WebP on the server."><div className="grid gap-5 md:grid-cols-2"><FileBox label="Cover / Primary image" file={cover} set={setCover}/><div><label className="label">Extra images</label><label className="flex min-h-28 cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 p-5 text-sm font-semibold hover:border-brand-400"><Upload size={18}/>Choose multiple images<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setExtras(Array.from(e.target.files||[]))}/></label>{extras.length>0&&<p className="mt-2 text-xs text-slate-500">{extras.length} extra image(s) selected</p>}</div></div>{editing&&product.data?.images?.length>0&&<div className="mt-6"><div className="mb-3 font-bold">Current gallery</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{product.data.images.map(img=><div className="relative rounded-xl border p-2" key={img.id}><img src={assetUrl(img.image_url)} className="aspect-square w-full rounded-lg object-contain bg-slate-50"/>{img.is_primary?<span className="badge absolute left-3 top-3 bg-amber-100 text-amber-700"><Star size={12}/>Cover</span>:<button onClick={()=>imageAction(img.id,'primary')} className="mt-2 w-full rounded-lg bg-slate-100 py-1.5 text-xs font-bold hover:bg-brand-50">Set cover</button>}<button onClick={()=>imageAction(img.id,'delete')} className="mt-1 flex w-full items-center justify-center gap-1 rounded-lg py-1.5 text-xs font-bold text-rose-600 hover:bg-rose-50"><Trash2 size={13}/>Delete</button></div>)}</div></div>}</Section>
    <Section title="SEO"><Grid><Input label="SEO title" value={f.seoTitle} set={v=>set('seoTitle',v)}/><div className="md:col-span-2"><label className="label">SEO description</label><textarea className="input min-h-24" value={f.seoDescription} onChange={e=>set('seoDescription',e.target.value)} maxLength={255}/><p className="admin-field-help">{f.seoDescription.length}/255 characters</p></div></Grid></Section>
    {err&&<ErrorBox>{err}</ErrorBox>}<div className="sticky bottom-4 z-20 flex justify-end gap-3 rounded-2xl border bg-white/95 p-4 shadow-panel backdrop-blur"><Link to="/admin/products" className="btn-secondary">Cancel</Link><button disabled={busy} onClick={save} className="btn-primary"><Save size={18}/>{busy?'Saving...':editing?'Update Product':'Create Product'}</button></div></div>}
  </div>;
}
function Section({title,note,children}){return <section className="admin-section"><h2 className="text-lg font-black">{title}</h2>{note&&<p className="mt-1 text-sm text-slate-500">{note}</p>}<div className="mt-5">{children}</div></section>}
function Grid({children}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Input({label,value,set,type='text',required,placeholder,help}){return <div><label className="label">{label}{required&&<span className="text-rose-500"> *</span>}</label><input className="input" type={type} value={value??''} placeholder={placeholder} onChange={e=>set(e.target.value)}/>{help&&<p className="admin-field-help">{help}</p>}</div>}
function Select({label,value,set,options}){return <div><label className="label">{label}</label><select className="input" value={value??''} onChange={e=>set(e.target.value)}><option value="">Not selected</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>}
function Editor({label,value,set,minHeight}){return <div className="mb-5"><label className="label">{label}</label><RichTextEditor value={value} onChange={set} minHeight={minHeight||145}/></div>}
function Check({label,value,set}){return <label className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-bold"><input className="h-4 w-4 accent-[rgb(var(--brand-600))]" type="checkbox" checked={Boolean(value)} onChange={e=>set(e.target.checked)}/>{label}</label>}
function FileBox({label,file,set}){const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);return <div><label className="label">{label}</label><label className="flex min-h-28 cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 p-5 text-sm font-semibold hover:border-brand-400"><Upload size={18}/>{file?file.name:'Choose image'}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>set(e.target.files?.[0]||null)}/></label>{preview&&<img src={preview} className="mt-3 h-32 rounded-xl border object-contain"/>}</div>}
function ErrorBox({children}){return <div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{children}</div>}
