import {useQuery} from '@tanstack/react-query';
import AdminResourcePage from '../../components/admin/AdminResourcePage';
import http,{assetUrl} from '../../api/http';

const statusCol={key:'is_active',label:'Status',type:'boolean'};
const richStrip=html=>String(html||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const dt=v=>{if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v).slice(0,16);const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};

export function CategoriesPage(){const {data=[]}=useQuery({queryKey:['cat-options'],queryFn:()=>http.get('/admin/categories').then(r=>r.data.data)});return <AdminResourcePage title="Categories" description="Control public navigation and category browsing. Categories can be featured, reordered and nested." endpoint="/admin/categories" columns={[{key:'image',label:'Image',type:'image'},{key:'name',label:'Name'},{key:'slug',label:'Slug'},{key:'parent_name',label:'Parent'},{key:'sort_order',label:'Order'},statusCol]} fields={[{key:'name',label:'Category name',required:true},{key:'slug',label:'Slug',help:'Leave blank to generate from name.'},{key:'parentId',source:'parent_id',label:'Parent category',type:'select',options:data.map(x=>({value:x.id,label:x.name}))},{key:'icon',label:'Icon name',placeholder:'Pill, Baby, Activity...'},{key:'image',label:'Category image',type:'file'},{key:'description',label:'Description',type:'rich'},{key:'sortOrder',source:'sort_order',label:'Sort order',type:'number',defaultValue:0},{key:'featured',source:'is_featured',label:'Featured',type:'checkbox'},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}

export function BrandsPage(){return <AdminResourcePage title="Brands" description="Manage brands displayed on products and the featured-brand section." endpoint="/admin/brands" columns={[{key:'logo',label:'Logo',type:'image'},{key:'name',label:'Brand'},{key:'slug',label:'Slug'},statusCol]} fields={[{key:'name',label:'Brand name',required:true},{key:'slug',label:'Slug'},{key:'logo',label:'Logo',type:'file'},{key:'description',label:'Brand description',type:'rich'},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}

export function ManufacturersPage(){return <AdminResourcePage title="Manufacturers" description="Maintain manufacturer records used by the medicine catalog." endpoint="/admin/manufacturers" columns={[{key:'logo',label:'Logo',type:'image'},{key:'name',label:'Manufacturer'},{key:'slug',label:'Slug'},statusCol]} fields={[{key:'name',label:'Manufacturer name',required:true},{key:'slug',label:'Slug'},{key:'logo',label:'Logo',type:'file'},{key:'description',label:'Description',type:'rich'},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}

export function SuppliersPage(){return <AdminResourcePage title="Suppliers" description="Manage suppliers connected to inventory batches." endpoint="/admin/suppliers" columns={[{key:'name',label:'Supplier'},{key:'company',label:'Company'},{key:'phone',label:'Phone'},{key:'email',label:'Email'},statusCol]} fields={[{key:'name',label:'Supplier name',required:true},{key:'company',label:'Company'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'address',label:'Address',type:'textarea'},{key:'notes',label:'Notes',type:'textarea'},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}

export function CouponsPage(){return <AdminResourcePage title="Coupons" description="Create percentage or fixed promotions with date and usage limits." endpoint="/admin/coupons" columns={[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'discount_type',label:'Type'},{key:'value',label:'Value'},{key:'end_date',label:'Ends',render:r=>r.end_date?new Date(r.end_date).toLocaleDateString():'—'},statusCol]} fields={[{key:'code',label:'Coupon code',required:true},{key:'name',label:'Name',required:true},{key:'description',label:'Description',type:'rich'},{key:'discountType',source:'discount_type',label:'Discount type',type:'select',options:['percentage','fixed'],defaultValue:'percentage'},{key:'value',label:'Discount value',type:'number',required:true},{key:'minimumOrder',source:'minimum_order',label:'Minimum order',type:'number',defaultValue:0},{key:'maximumDiscount',source:'maximum_discount',label:'Maximum discount',type:'number'},{key:'startDate',source:'start_date',label:'Start date/time',type:'datetime-local',required:true},{key:'endDate',source:'end_date',label:'End date/time',type:'datetime-local',required:true},{key:'usageLimit',source:'usage_limit',label:'Total usage limit',type:'number'},{key:'usagePerUser',source:'usage_per_user',label:'Usage per user',type:'number',defaultValue:1},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]} onEditTransform={(row,f)=>({...f,startDate:dt(row.start_date),endDate:dt(row.end_date)})}/>}

export function BannersPage(){return <AdminResourcePage title="Banners" description="Control hero and promotional banners shown on the public website. Rich text, CTA and responsive images are supported." endpoint="/admin/banners" columns={[{key:'image',label:'Image',type:'image'},{key:'title',label:'Title'},{key:'position',label:'Position'},{key:'sort_order',label:'Order'},statusCol]} fields={[{key:'title',label:'Banner title',required:true},{key:'subtitle',label:'Subtitle',type:'rich'},{key:'content',label:'Additional rich content',type:'rich'},{key:'buttonText',source:'button_text',label:'Button text'},{key:'buttonUrl',source:'button_url',label:'Button URL',placeholder:'/products'},{key:'position',label:'Position',type:'select',options:['hero','promotion','prescription','footer'],defaultValue:'hero'},{key:'image',label:'Desktop image',type:'file'},{key:'mobileImage',source:'mobile_image',label:'Mobile image',type:'file'},{key:'sortOrder',source:'sort_order',label:'Sort order',type:'number',defaultValue:0},{key:'startAt',source:'start_at',label:'Start date/time',type:'datetime-local'},{key:'endAt',source:'end_at',label:'End date/time',type:'datetime-local'},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]} onEditTransform={(row,f)=>({...f,startAt:dt(row.start_at),endAt:dt(row.end_at),image:row.image||'',mobileImage:row.mobile_image||''})}/>}

export function ServicesPage(){return <AdminResourcePage title="Healthcare Services" description="Manage services shown on the homepage and available for customer booking." endpoint="/admin/services" columns={[{key:'image',label:'Image',type:'image'},{key:'name',label:'Service'},{key:'slug',label:'Slug'},{key:'price',label:'Price',render:r=>'৳'+Number(r.price||0).toLocaleString()},{key:'sort_order',label:'Order'},statusCol]} fields={[{key:'name',label:'Service name',required:true},{key:'slug',label:'Slug'},{key:'description',label:'Description',type:'rich'},{key:'icon',label:'Icon name',placeholder:'Stethoscope'},{key:'image',label:'Service image',type:'file'},{key:'price',label:'Price',type:'number',defaultValue:0},{key:'sortOrder',source:'sort_order',label:'Sort order',type:'number',defaultValue:0},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}

export function CmsPagesPage(){return <AdminResourcePage title="CMS Pages" description="Edit About, Contact, FAQ, policies and other public website pages with formatting controls." endpoint="/admin/pages" columns={[{key:'title',label:'Page'},{key:'slug',label:'Slug'},{key:'content',label:'Preview',render:r=><span className="line-clamp-2 max-w-md text-slate-500">{richStrip(r.content)}</span>},statusCol]} fields={[{key:'title',label:'Page title',required:true},{key:'slug',label:'Slug',help:'Public URL: /page/your-slug'},{key:'content',label:'Page content',type:'rich',minHeight:260},{key:'seoTitle',source:'seo_title',label:'SEO title'},{key:'seoDescription',source:'seo_description',label:'SEO description',type:'textarea'},{key:'active',source:'is_active',label:'Published',type:'checkbox'}]}/>}

export function ShippingZonesPage(){return <AdminResourcePage title="Shipping Zones" description="Configure delivery fees, regional matching and free-shipping thresholds used by checkout." endpoint="/admin/shipping-zones" columns={[{key:'name',label:'Zone'},{key:'division',label:'Division'},{key:'district',label:'District'},{key:'fee',label:'Fee',render:r=>'৳'+Number(r.fee||0).toLocaleString()},{key:'estimated_days',label:'Estimate'},statusCol]} fields={[{key:'name',label:'Zone name',required:true},{key:'division',label:'Division',help:'Leave blank as a fallback zone.'},{key:'district',label:'District',help:'Leave blank to match all districts in the division.'},{key:'fee',label:'Delivery fee',type:'number',defaultValue:80},{key:'estimatedDays',source:'estimated_days',label:'Estimated delivery',placeholder:'1-2 business days'},{key:'freeShippingThreshold',source:'free_shipping_threshold',label:'Free shipping threshold',type:'number'},{key:'sortOrder',source:'sort_order',label:'Match priority/order',type:'number',defaultValue:0},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}


export function NavigationPage(){const {data=[]}=useQuery({queryKey:['navigation-options'],queryFn:()=>http.get('/admin/navigation').then(r=>r.data.data)});return <AdminResourcePage title="Navigation & Footer Links" description="Control the public header menu and footer columns without editing React code. Internal paths such as /products or /page/about and full external URLs are supported." endpoint="/admin/navigation" columns={[{key:'label',label:'Label'},{key:'url',label:'URL'},{key:'location',label:'Location'},{key:'parent_label',label:'Parent'},{key:'sort_order',label:'Order'},statusCol]} fields={[{key:'label',label:'Link label',required:true},{key:'url',label:'URL',required:true,placeholder:'/products or https://example.com'},{key:'location',label:'Location',type:'select',options:[{value:'header',label:'Header menu'},{value:'footer_company',label:'Footer — Company'},{value:'footer_shop',label:'Footer — Shop'},{value:'footer_help',label:'Footer — Help'},{value:'footer_legal',label:'Footer — Legal'}],defaultValue:'header'},{key:'parentId',source:'parent_id',label:'Parent link (optional)',type:'select',options:data.map(x=>({value:x.id,label:x.label+' — '+x.location}))},{key:'openNewTab',source:'open_new_tab',label:'Open in new tab',type:'checkbox',defaultValue:false},{key:'sortOrder',source:'sort_order',label:'Sort order',type:'number',defaultValue:0},{key:'active',source:'is_active',label:'Active',type:'checkbox'}]}/>}
