import {Link} from 'react-router-dom';
import {adminConfirm,adminPrompt,adminAlert} from '../../components/admin/AdminDialogs';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {KeyRound,Palette,Phone,Save,ShieldCheck,Store,Truck,Upload} from 'lucide-react';
import http,{assetUrl} from '../../api/http';
import {useAuthStore} from '../../store/auth';
import RichTextEditor from '../../components/admin/RichTextEditor';

const themes=[
  {key:'clinical-teal',name:'Clinical Teal',desc:'Clean pharmacy teal',swatches:['rgb(15 157 145)','rgb(7 133 123)','rgb(7 107 100)']},
  {key:'ocean-blue',name:'Ocean Blue',desc:'Professional blue healthcare',swatches:['rgb(30 136 229)','rgb(20 108 199)','rgb(18 84 156)']},
  {key:'emerald-care',name:'Emerald Care',desc:'Fresh green wellness',swatches:['rgb(16 185 129)','rgb(5 150 105)','rgb(4 120 87)']},
  {key:'violet-wellness',name:'Violet Wellness',desc:'Modern premium violet',swatches:['rgb(124 92 214)','rgb(103 72 190)','rgb(82 59 151)']}
];
export default function Settings(){
  const qc=useQueryClient();const q=useQuery({queryKey:['admin-settings'],queryFn:()=>http.get('/admin/settings').then(r=>r.data.data)});const profile=useQuery({queryKey:['admin-profile'],queryFn:()=>http.get('/admin/profile').then(r=>r.data.data)});const [s,setS]=useState({});const [p,setP]=useState({firstName:'',lastName:'',email:'',phone:'',currentPassword:'',newPassword:'',confirmPassword:''});const [busy,setBusy]=useState(false);const logoutLocal=useAuthStore(x=>x.logoutLocal);
  useEffect(()=>{if(q.data)setS(q.data)},[q.data]);useEffect(()=>{if(profile.data)setP(x=>({...x,firstName:profile.data.first_name||'',lastName:profile.data.last_name||'',email:profile.data.email||'',phone:profile.data.phone||''}))},[profile.data]);
  const set=(k,v)=>setS(x=>({...x,[k]:v}));
  const saveSettings=async()=>{setBusy(true);try{const r=await http.put('/admin/settings',{values:s});setS(r.data.data);document.documentElement.dataset.theme=r.data.data['theme.active']||'clinical-teal';await qc.invalidateQueries({queryKey:['site-config']});await qc.invalidateQueries({queryKey:['home']});localStorage.setItem('sc-site-refresh',String(Date.now()));window.dispatchEvent(new Event('sc-site-refresh'));await qc.refetchQueries({queryKey:['site-config']});adminAlert('Website settings saved. Public theme/content has been refreshed.')}catch(e){adminAlert(e.response?.data?.message||'Could not save settings')}finally{setBusy(false)}};
  const broadcast=async()=>{await qc.invalidateQueries({queryKey:['site-config']});await qc.invalidateQueries({queryKey:['home']});localStorage.setItem('sc-site-refresh',String(Date.now()));window.dispatchEvent(new Event('sc-site-refresh'));await qc.refetchQueries({queryKey:['site-config']})};
  const saveOne=async(key,value)=>{const r=await http.put('/admin/settings',{values:{[key]:value}});setS(x=>({...x,[key]:r.data.data[key]??value}));await broadcast();return r.data.data};
  const applyTheme=async(key)=>{set('theme.active',key);document.documentElement.dataset.theme=key;try{await saveOne('theme.active',key)}catch(e){adminAlert(e.response?.data?.message||'Could not apply theme')}};
  const upload=async(key,file)=>{if(!file)return;try{const fd=new FormData();fd.append('file',file);const r=await http.post('/admin/media',fd);const url=r.data.data.url;set(key,url);await saveOne(key,url)}catch(e){adminAlert(e.response?.data?.message||'Upload failed')}};
  const saveProfile=async()=>{if(p.newPassword&&p.newPassword!==p.confirmPassword)return adminAlert('New password confirmation does not match');setBusy(true);try{await http.put('/admin/profile',p);adminAlert(p.newPassword?'Admin account updated. Sign in again with the new password.':'Admin account updated');if(p.newPassword){logoutLocal();window.location.assign('/admin/login')}else{profile.refetch()}}catch(e){adminAlert(e.response?.data?.message||'Could not update admin account')}finally{setBusy(false)}};
  return <><h1 className="admin-page-title">Store & Admin Settings</h1><p className="mt-1 max-w-4xl text-sm text-slate-500">Control website branding, visible text, theme, contact information, checkout, payment visibility, admin URL alias and your admin credentials from one place.</p><div className="mt-6 space-y-6">
    <Group icon={Palette} title="Website Theme" text="Changing theme only changes presentation. Products, orders, customers, content and MySQL data remain exactly the same."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{themes.map(t=><button type="button" key={t.key} onClick={()=>applyTheme(t.key)} className={`rounded-2xl border-2 p-4 text-left transition ${s['theme.active']===t.key?'border-brand-500 bg-brand-50':'border-slate-200 hover:border-slate-300'}`}><div className="flex gap-1">{t.swatches.map(c=><span key={c} className="h-6 w-6 rounded-full" style={{backgroundColor:c}}/>)}</div><div className="mt-3 font-black">{t.name}</div><div className="text-xs text-slate-500">{t.desc}</div></button>)}</div></Group>
    <Group icon={Store} title="Branding & Main Store Content"><div className="grid gap-4 md:grid-cols-2"><Input label="Brand name" value={s['brand.name']} set={v=>set('brand.name',v)}/><Input label="Tagline" value={s['brand.tagline']} set={v=>set('brand.tagline',v)}/><Asset label="Logo" value={s['brand.logo']} setFile={f=>upload('brand.logo',f)}/><Asset label="Favicon / small mark" value={s['brand.favicon']} setFile={f=>upload('brand.favicon',f)}/><Input label="Currency code" value={s.currency} set={v=>set('currency',v)}/><Input label="Currency symbol" value={s['currency.symbol']} set={v=>set('currency.symbol',v)}/><Input label="Header search placeholder" value={s['header.search_placeholder']} set={v=>set('header.search_placeholder',v)}/><Input label="Hero badge" value={s['home.hero_badge']} set={v=>set('home.hero_badge',v)}/><Input label="Hero trust note" value={s['home.hero_note']} set={v=>set('home.hero_note',v)}/><Input label="Announcement text" value={s['announcement.text']} set={v=>set('announcement.text',v)}/><Check label="Show announcement bar" value={s['announcement.enabled']!=='0'} set={v=>set('announcement.enabled',v?'1':'0')}/></div><p className="admin-field-help mt-4">Hero title, formatted subtitle, CTA, images and promotional banners are controlled from Marketing → Banners. Homepage section titles/order/visibility are controlled from Content → Homepage.</p></Group>
    <Group icon={ShieldCheck} title="Homepage Trust Bar" text="All four trust blocks shown below the hero can be edited here."><div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].flatMap(i=>[<Input key={'t'+i} label={`Trust ${i} title`} value={s[`home.trust_${i}_title`]} set={v=>set(`home.trust_${i}_title`,v)}/>,<Input key={'d'+i} label={`Trust ${i} text`} value={s[`home.trust_${i}_text`]} set={v=>set(`home.trust_${i}_text`,v)}/>])}</div></Group>
    <Group icon={Phone} title="Contact, Footer & Social"><div className="grid gap-4 md:grid-cols-2"><Input label="Support email" value={s['contact.email']} set={v=>set('contact.email',v)}/><Input label="Support phone" value={s['contact.phone']} set={v=>set('contact.phone',v)}/><Input label="Address" value={s['contact.address']} set={v=>set('contact.address',v)}/><Input label="Support hours" value={s['contact.hours']} set={v=>set('contact.hours',v)}/><div className="md:col-span-2"><span className="label">Formatted footer about text</span><RichTextEditor value={s['footer.about']||''} onChange={v=>set('footer.about',v)}/></div><Input label="Copyright" value={s['footer.copyright']} set={v=>set('footer.copyright',v)}/><Input label="Facebook URL" value={s['social.facebook']} set={v=>set('social.facebook',v)}/><Input label="Instagram URL" value={s['social.instagram']} set={v=>set('social.instagram',v)}/><Input label="YouTube URL" value={s['social.youtube']} set={v=>set('social.youtube',v)}/><Input label="LinkedIn URL" value={s['social.linkedin']} set={v=>set('social.linkedin',v)}/></div></Group>
    <Group icon={Truck} title="Checkout, Shipping & Payments"><div className="grid gap-4 md:grid-cols-2"><Input label="Default shipping fee" type="number" value={s['shipping.default_fee']} set={v=>set('shipping.default_fee',v)}/><Input label="Default free-shipping threshold" type="number" value={s['shipping.free_threshold']} set={v=>set('shipping.free_threshold',v)}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['payment.cod','Cash on Delivery'],['payment.bkash','bKash'],['payment.nagad','Nagad'],['payment.rocket','Rocket'],['payment.sslcommerz','SSLCommerz / Card']].map(([k,l])=><Check key={k} label={l} value={s[k]!=='0'} set={v=>set(k,v?'1':'0')}/>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border p-4"><h3 className="font-black">bKash checkout instructions</h3><div className="mt-3 space-y-3"><Input label="bKash receiving number" value={s['payment.bkash.number']} set={v=>set('payment.bkash.number',v)} placeholder="01XXXXXXXXX"/><div><span className="label">bKash payment process</span><RichTextEditor value={s['payment.bkash.instructions']||''} onChange={v=>set('payment.bkash.instructions',v)}/></div></div></div><div className="rounded-2xl border p-4"><h3 className="font-black">Nagad checkout instructions</h3><div className="mt-3 space-y-3"><Input label="Nagad receiving number" value={s['payment.nagad.number']} set={v=>set('payment.nagad.number',v)} placeholder="01XXXXXXXXX"/><div><span className="label">Nagad payment process</span><RichTextEditor value={s['payment.nagad.instructions']||''} onChange={v=>set('payment.nagad.instructions',v)}/></div></div></div></div><p className="admin-field-help mt-3">Customers selecting bKash/Nagad will automatically see the configured number and payment instructions, then can submit last 4 digits or a transaction ID.</p></Group>
    <Group icon={Phone} title="WhatsApp Chat" text="Control the floating WhatsApp help button shown on the public website."><div className="grid gap-4 md:grid-cols-2"><Check label="Enable WhatsApp button" value={s['whatsapp.enabled']!=='0'} set={v=>set('whatsapp.enabled',v?'1':'0')}/><Input label="WhatsApp number" value={s['whatsapp.number']} set={v=>set('whatsapp.number',v)} help="Use a Bangladesh number such as +8801XXXXXXXXX."/><Input label="Default WhatsApp message" value={s['whatsapp.message']} set={v=>set('whatsapp.message',v)}/><Input label="Button position" value={s['whatsapp.position']} set={v=>set('whatsapp.position',v)} help="Currently bottom-right is supported."/></div></Group>
    <Group icon={ShieldCheck} title="Email" text="Manage sending and optional inbox access in one place."><Link to="/admin/settings/email" className="btn-secondary">Open Email Settings</Link></Group>
    <Group icon={KeyRound} title="Admin Panel URL Alias"><Input label="Admin panel/login slug" value={s['admin.panel_slug']} set={v=>set('admin.panel_slug',v)} help={`After saving, /${s['admin.panel_slug']||'control-center'}/login opens the admin login. /admin/login always remains available so you cannot lock yourself out.`}/></Group>
    <button disabled={busy} onClick={saveSettings} className="btn-primary"><Save size={17}/>{busy?'Saving...':'Save All Website Settings'}</button>
    <Group icon={ShieldCheck} title="My Admin Account" text="Change the signed-in administrator name, Gmail/email, phone or password. Current password is required for email, phone or password changes."><div className="grid gap-4 md:grid-cols-2"><Input label="First name" value={p.firstName} set={v=>setP({...p,firstName:v})}/><Input label="Last name" value={p.lastName} set={v=>setP({...p,lastName:v})}/><Input label="Admin email / Gmail" type="email" value={p.email} set={v=>setP({...p,email:v})}/><Input label="Phone" value={p.phone} set={v=>setP({...p,phone:v})}/><Input label="Current password" type="password" value={p.currentPassword} set={v=>setP({...p,currentPassword:v})}/><div/><Input label="New password" type="password" value={p.newPassword} set={v=>setP({...p,newPassword:v})}/><Input label="Confirm new password" type="password" value={p.confirmPassword} set={v=>setP({...p,confirmPassword:v})}/></div><button disabled={busy} onClick={saveProfile} className="btn-primary mt-5"><KeyRound size={17}/>Update Admin Account</button></Group>
  </div></>;
}
function Group({icon:Icon,title,text,children}){return <section className="admin-section"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Icon size={19}/></span><div><h2 className="text-lg font-black">{title}</h2>{text&&<p className="mt-1 text-sm text-slate-500">{text}</p>}</div></div><div className="mt-5">{children}</div></section>}
function Input({label,value,set,type='text',help}){return <label><span className="label">{label}</span><input className="input" type={type} value={value??''} onChange={e=>set(e.target.value)}/>{help&&<span className="admin-field-help block">{help}</span>}</label>}
function Check({label,value,set}){return <label className="flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input type="checkbox" checked={Boolean(value)} onChange={e=>set(e.target.checked)} className="h-4 w-4"/>{label}</label>}
function Asset({label,value,setFile}){return <div><label className="label">{label}</label><div className="flex items-center gap-3">{value?<img src={assetUrl(value)} className="h-14 w-20 rounded-xl border object-contain" alt=""/>:<div className="grid h-14 w-20 place-items-center rounded-xl bg-slate-100 text-xs text-slate-400">No image</div>}<label className="btn-secondary cursor-pointer"><Upload size={16}/>Upload<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>setFile(e.target.files?.[0])}/></label></div></div>}
