import {useAuthStore} from '../store/auth';
const api=(import.meta.env.VITE_API_URL||'/api/v1').replace(/\/+$/,'');
let config=null;const pending=[];
export function configureTracking(value){config=value;const events=pending.splice(0);if(value?.status)for(const item of events)if(item.path===location.pathname)track(item.name,item.detail)}
export function consent(){try{return localStorage.getItem('sc-tracking-consent')==='accepted'}catch{return false}}
export function eligiblePath(path=location.pathname){return !/^\/(admin|account|invoice|admin-invoice|reset-password|forgot-password|login|register)(\/|$)/.test(path)}
function identity(){let visitor=localStorage.getItem('sc-visitor');if(!visitor){visitor=crypto.randomUUID();localStorage.setItem('sc-visitor',visitor)}let session;try{session=JSON.parse(sessionStorage.getItem('sc-session'))}catch{}if(!session||Date.now()-session.time>1800000)session={id:crypto.randomUUID()};session.time=Date.now();sessionStorage.setItem('sc-session',JSON.stringify(session));return {visitor_id:visitor,session_id:session.id}}
export async function track(event_name,detail={}){if(config===null&&consent()&&eligiblePath()){if(pending.length<30)pending.push({name:event_name,detail,path:location.pathname});return}if(!config?.status||!consent()||!eligiblePath())return;try{const user=useAuthStore.getState();const body={consent:true,event_id:crypto.randomUUID(),...identity(),event_name,page_url:location.pathname,...Object.fromEntries(['product_id','order_id','search_term'].filter(k=>detail[k]!=null).map(k=>[k,detail[k]]))};const response=await fetch(api+'/activity',{method:'POST',headers:{'Content-Type':'application/json',...(user.accessToken?{Authorization:'Bearer '+user.accessToken}:{})},body:JSON.stringify(body),keepalive:true});if(!response.ok)return;const result=await response.json();if(!result.data?.accepted)return;
 const payload={currency:'BDT',...(detail.product_id?{items:[{item_id:String(detail.product_id)}],content_ids:[String(detail.product_id)],content_type:'product'}:{}),...(detail.order_id?{transaction_id:String(detail.order_id)}:{}),...(detail.value!=null?{value:Number(detail.value)}:{})};
 const meta={page_view:'PageView',view_item:'ViewContent',add_to_cart:'AddToCart',begin_checkout:'InitiateCheckout',purchase:'Purchase',add_to_wishlist:'AddToWishlist',search:'Search',add_payment_info:'AddPaymentInfo'};
 if(config.meta_pixel_status&&window.fbq&&meta[event_name])window.fbq('track',meta[event_name],payload,{eventID:body.event_id});if(config.google_analytics_status&&window.gtag&&event_name!=='heartbeat')window.gtag('event',event_name,payload);if(config.gtm_status&&event_name!=='heartbeat'){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:event_name,ecommerce:payload})}
 }catch{/* Tracking never blocks shopping. */}}
export function installTracking(s){configureTracking(s);if(!s?.status||!consent()||!eligiblePath()||window.__scTrackingInstalled)return;window.__scTrackingInstalled=true;
 const script=(src)=>{const el=document.createElement('script');el.async=true;el.src=src;el.dataset.scTracking='1';document.head.append(el)};
 if(s.google_analytics_status&&/^G-[A-Z0-9]+$/.test(s.ga_measurement_id)){window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){window.dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config',s.ga_measurement_id,{send_page_view:false});script('https://www.googletagmanager.com/gtag/js?id='+s.ga_measurement_id)}
 if(s.gtm_status&&/^GTM-[A-Z0-9]+$/.test(s.gtm_container_id)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({'gtm.start':Date.now(),event:'gtm.js'});script('https://www.googletagmanager.com/gtm.js?id='+s.gtm_container_id)}
 if(s.meta_pixel_status&&/^\d+$/.test(s.meta_pixel_id)){const f=window.fbq=window.fbq||function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments)};f.queue=f.queue||[];f.loaded=true;f.version='2.0';window._fbq=f;f('init',s.meta_pixel_id);script('https://connect.facebook.net/en_US/fbevents.js')}
 for(const [code,target] of [[s.custom_header_script,document.head],[s.custom_footer_script,document.body]]){if(!code)continue;const template=document.createElement('template');template.innerHTML=code;const scripts=template.content.querySelectorAll('script');if(!scripts.length){const el=document.createElement('script');el.textContent=code;target.append(el)}else for(const original of scripts){const el=document.createElement('script');for(const a of original.attributes)el.setAttribute(a.name,a.value);el.textContent=original.textContent;target.append(el)}}
}
