import phoneRoutes from './routes/phone.routes.js';
import paymentRoutes from './routes/payments.routes.js';
import analyticsRoutes from './routes/analytics.routes.js';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import path from 'path';
import {env} from './config/env.js';
import {uploadsRoot} from './config/paths.js';
import authRoutes from './routes/auth.routes.js';
import catalogRoutes from './routes/catalog.routes.js';
import userRoutes from './routes/user.routes.js';
import publicRoutes from './routes/public.routes.js';
import adminRoutes from './routes/admin.routes.js';
import {errorHandler,notFound} from './middleware/error.js';

const app=express();
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:env.clientUrl,credentials:true}));
app.use('/api',rateLimit({windowMs:15*60*1000,limit:500,standardHeaders:true,legacyHeaders:false}));
app.use(express.json({limit:'4mb'}));
app.use(express.urlencoded({extended:true,limit:'4mb'}));
app.use(cookieParser());
app.use('/uploads/products',express.static(path.join(uploadsRoot,'products'),{maxAge:'1d'}));
app.use('/uploads/media',express.static(path.join(uploadsRoot,'media'),{maxAge:'1d'}));
app.get('/health',(req,res)=>res.json({ok:true,time:new Date().toISOString()}));
app.use('/api/v1/auth',phoneRoutes);
app.use('/api/v1/auth',authRoutes);
app.use('/api/v1',paymentRoutes);
app.use('/api/v1',analyticsRoutes);
app.use('/api/v1',catalogRoutes);
app.use('/api/v1',publicRoutes);
app.use('/api/v1/user',userRoutes);
app.use('/api/v1/admin',adminRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
