import {randomUUID} from 'node:crypto';
import {query,pool} from '../config/db.js';
import {readSettings} from './integrationSettings.js';
import {encrypt,decrypt} from './credentials.js';
export function sslBase(s){return s.mode==='live'?'https://securepay.sslcommerz.com':'https://sandbox.sslcommerz.com'}
export function validatePayment(v,session,order){return ['VALID','VALIDATED'].includes(v.status)&&v.tran_id===session.transaction_id&&v.currency==='BDT'&&Math.round(Number(v.amount)*100)===Math.round(Number(order.total)*100)&&String(v.risk_level||'0')==='0'}
export async function activeGateway(type){const [r]=await query('SELECT id FROM payment_settings WHERE gateway_type=? AND status=1',[type]);return r?readSettings('payment',r.id,true):null}
export async function startPayment(orderId,userId){
 const conn=await pool.getConnection();let order,session,settings,existing=false;
 try{await conn.beginTransaction();const [[o]]=await conn.execute('SELECT o.*,u.email,u.phone,u.first_name,u.last_name FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=? AND o.user_id=? FOR UPDATE',[orderId,userId]);order=o;if(!order)throw Object.assign(new Error('Order not found'),{status:404});if(order.payment_status==='paid'||['cancelled','refunded'].includes(order.status))throw Object.assign(new Error('Order cannot be paid'),{status:409});settings=await activeGateway(order.payment_method);if(!settings||settings.gateway_type!=='sslcommerz')throw Object.assign(new Error('Online payment is currently unavailable'),{status:503});
 const [[old]]=await conn.execute('SELECT * FROM payment_sessions WHERE order_id=?',[orderId]);if(old){session=old;existing=true}else{session={transaction_id:'SC'+randomUUID().replaceAll('-','').slice(0,28)};await conn.execute('INSERT INTO payment_sessions(order_id,gateway_id,transaction_id,gateway_snapshot) VALUES(?,?,?,?)',[orderId,settings.id,session.transaction_id,encrypt(JSON.stringify(settings))])}await conn.commit();
 }catch(e){await conn.rollback();throw e}finally{conn.release()}
 if(existing){if(session.checkout_url)return {redirectUrl:session.checkout_url};throw Object.assign(new Error('Payment initiation is pending or could not be confirmed. Contact support before trying again.'),{status:409})}
 const base=sslBase(settings),publicUrl=String(process.env.PUBLIC_API_URL||'').replace(/\/$/,'');if(!/^https:\/\//.test(publicUrl)){await query("UPDATE payment_sessions SET status='failed' WHERE order_id=?",[orderId]);throw Object.assign(new Error('Configure HTTPS PUBLIC_API_URL'),{status:503})}
 const callback=publicUrl+'/api/v1/payments/sslcommerz';let address=order.address_json;try{if(typeof address==='string')address=JSON.parse(address)}catch{address={}}
 const payload={store_id:settings.merchant_id,store_passwd:settings.secret_key,total_amount:Number(order.total).toFixed(2),currency:'BDT',tran_id:session.transaction_id,success_url:callback+'/success',fail_url:callback+'/fail',cancel_url:callback+'/cancel',ipn_url:callback+'/ipn',cus_name:[order.first_name,order.last_name].join(' '),cus_email:order.email,cus_phone:order.phone,cus_add1:address?.addressLine||'Bangladesh',cus_city:address?.district||'Dhaka',cus_country:'Bangladesh',shipping_method:'NO',num_of_item:'1',product_name:'Order '+order.order_number,product_category:'Retail',product_profile:'general'};
 try{const endpoint=settings.api_url||base+'/gwprocess/v4/api.php';if(endpoint!==base+'/gwprocess/v4/api.php')throw new Error('Invalid SSLCOMMERZ API URL for selected mode');const r=await fetch(endpoint,{method:'POST',redirect:'error',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(payload),signal:AbortSignal.timeout(20000)});const data=await r.json();const redirect=new URL(data.GatewayPageURL);if(!r.ok||data.status!=='SUCCESS'||redirect.protocol!=='https:'||!(redirect.hostname==='sslcommerz.com'||redirect.hostname.endsWith('.sslcommerz.com')))throw new Error('Gateway did not return a valid session');await query("UPDATE payment_sessions SET checkout_url=?,status='pending' WHERE order_id=?",[redirect.toString(),orderId]);return {redirectUrl:redirect.toString()}}catch{await query("UPDATE payment_sessions SET status='uncertain' WHERE order_id=?",[orderId]);throw Object.assign(new Error('Gateway session could not be confirmed. Your order is saved; contact support.'),{status:502})}
}
export async function handleSslCallback(input){
 if(typeof input.tran_id!=='string'||input.tran_id.length>40||typeof input.val_id!=='string'||input.val_id.length>100)throw Object.assign(new Error('Missing transaction validation data'),{status:400});
 const [session]=await query('SELECT * FROM payment_sessions WHERE transaction_id=?',[input.tran_id]);if(!session)throw Object.assign(new Error('Unknown transaction'),{status:404});const settings=JSON.parse(decrypt(session.gateway_snapshot));const url=new URL(sslBase(settings)+'/validator/api/validationserverAPI.php');url.search=new URLSearchParams({val_id:input.val_id,store_id:settings.merchant_id,store_passwd:settings.secret_key,format:'json'});const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Object.assign(new Error('Payment verification unavailable'),{status:502});const verified=await response.json();
 const conn=await pool.getConnection();try{await conn.beginTransaction();const [[order]]=await conn.execute('SELECT * FROM orders WHERE id=? FOR UPDATE',[session.order_id]);if(!validatePayment(verified,session,order))throw Object.assign(new Error('Payment verification failed'),{status:400});if(['cancelled','refunded'].includes(order.status))throw Object.assign(new Error('Payment received for closed order; manual reconciliation required'),{status:409});if(order.payment_status!=='paid'){await conn.execute("UPDATE orders SET payment_status='paid',payment_transaction_id=? WHERE id=?",[verified.bank_tran_id||session.transaction_id,order.id]);await conn.execute("UPDATE payments SET status='paid',transaction_ref=? WHERE order_id=?",[verified.bank_tran_id||session.transaction_id,order.id]);await conn.execute("UPDATE payment_sessions SET status='paid' WHERE id=?",[session.id])}await conn.commit();return {orderId:order.id,settings}}catch(e){await conn.rollback();throw e}finally{conn.release()}
}
