import {imageFallback} from '../api/assets';
import {Heart,ShoppingCart,Star,ShieldAlert} from 'lucide-react';
import {Link,useNavigate} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import http,{assetUrl} from '../api/http';
import {useAuthStore} from '../store/auth';
import {useSiteConfig,setting} from '../hooks/useSiteConfig';
export default function ProductCard({p}){
  const user=useAuthStore(s=>s.user),nav=useNavigate(),qc=useQueryClient();const {data:cfg}=useSiteConfig();
  const {data:wishlist=[]}=useQuery({queryKey:['wishlist'],enabled:Boolean(user),queryFn:()=>http.get('/user/wishlist').then(r=>r.data.data),staleTime:15000});
  const wished=wishlist.some(x=>Number(x.id)===Number(p.id));const money=n=>setting(cfg,'currency.symbol','৳')+Number(n||0).toLocaleString();
  const auth=()=>{if(!user){nav('/login');return false}return true};
  const add=async()=>{if(!auth())return;try{await http.post('/user/cart/items',{productId:p.id,quantity:1,priceType:'unit'});qc.invalidateQueries({queryKey:['cart']})}catch(e){alert(e.response?.data?.message||'Could not add to cart')}};
  const wish=async()=>{if(!auth())return;try{if(wished)await http.delete('/user/wishlist/'+p.id);else await http.post('/user/wishlist/'+p.id);await qc.invalidateQueries({queryKey:['wishlist']})}catch(e){alert(e.response?.data?.message||'Could not update wishlist')}};
  const off=Number(p.discount_percent||0);const displayPrice=Number(p.unit_price||p.sale_price||0);const listUnit=off>0&&off<100?displayPrice/(1-off/100):Number(p.regular_price||displayPrice);
  return <article className="card group relative overflow-hidden p-4"><button aria-label={wished?'Remove from wishlist':'Add to wishlist'} onClick={wish} className={`absolute right-3 top-3 z-10 grid h-9 w-9 place-items-center rounded-full bg-white shadow transition ${wished?'text-rose-600':'text-slate-500 hover:text-rose-600'}`}><Heart size={18} fill={wished?'currentColor':'none'}/></button>{p.prescription_required?<span className="badge absolute left-3 top-3 z-10 bg-violet-600 text-white"><ShieldAlert size={12}/>Rx</span>:off>0?<span className="badge absolute left-3 top-3 z-10 bg-emerald-600 text-white">{off}% OFF</span>:null}<Link to={'/product/'+p.slug}><div className="aspect-square rounded-xl bg-gradient-to-br from-brand-50 to-slate-50 p-5"><img onError={imageFallback} src={p.image?assetUrl(p.image):'/product-placeholder.svg'} alt={p.name} className="h-full w-full object-contain transition group-hover:scale-105"/></div><div className="mt-4"><div className="mb-1 flex items-center gap-1 text-xs text-amber-500"><Star size={13} fill="currentColor"/>{Number(p.rating_avg||0).toFixed(1)} <span className="text-slate-400">({p.review_count||0})</span></div><h3 className="line-clamp-2 min-h-12 font-bold">{p.name}</h3><p className="mt-1 text-xs text-slate-500">{p.pack_size||'Healthcare product'}</p><div className="mt-3"><span className="text-lg font-black">{money(displayPrice)}</span><span className="ml-1 text-xs text-slate-500">/{p.unit_label||'unit'}</span>{off>0&&<span className="ml-2 text-xs text-slate-400 line-through">{money(listUnit)}</span>}</div>{Number(p.strip_price||0)>0&&<div className="mt-1 text-[11px] text-slate-500">Strip {money(p.strip_price)} · Box {money(p.box_price||0)}</div>}</div></Link><button onClick={add} disabled={!Number(p.stock)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-50 py-2.5 text-sm font-bold text-brand-700 hover:bg-brand-600 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"><ShoppingCart size={17}/>Add 1 Unit</button></article>
}
