import VerifyPhone from '../../components/VerifyPhone';
import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {KeyRound,Mail,Save,UserRound} from 'lucide-react';
import http from '../../api/http';
import {useAuthStore} from '../../store/auth';
export default function Profile(){
  const qc=useQueryClient(),logoutLocal=useAuthStore(s=>s.logoutLocal);const q=useQuery({queryKey:['user-profile'],queryFn:()=>http.get('/user/profile').then(r=>r.data.data)});const [form,setForm]=useState({fullName:'',phone:''}),[mail,setMail]=useState({email:'',otp:''}),[pw,setPw]=useState({currentPassword:'',newPassword:'',confirmPassword:''}),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[mailStep,setMailStep]=useState(1);
  useEffect(()=>{if(q.data){setForm({fullName:q.data.full_name||[q.data.first_name,q.data.last_name].filter(Boolean).join(' '),phone:q.data.phone||''});setMail(x=>({...x,email:q.data.email||''}))}},[q.data]);
  const run=async fn=>{setBusy(true);setErr('');setMsg('');try{await fn()}catch(e){setErr(e.response?.data?.message||'Request failed')}finally{setBusy(false)}};
  const save=e=>{e.preventDefault();run(async()=>{const r=await http.patch('/user/profile',form);setMsg(r.data.message);qc.invalidateQueries({queryKey:['user-profile']})})};
  const requestEmail=()=>run(async()=>{const r=await http.post('/user/profile/request-email-change',{email:mail.email});setMsg(r.data.message);setMailStep(2)});
  const verifyEmail=()=>run(async()=>{const r=await http.post('/user/profile/verify-email-change',mail);setMsg(r.data.message);setMailStep(1);qc.invalidateQueries({queryKey:['user-profile']})});
  const changePassword=e=>{e.preventDefault();if(pw.newPassword!==pw.confirmPassword)return setErr('New password confirmation does not match');run(async()=>{const r=await http.post('/user/profile/change-password',pw);alert(r.data.message);logoutLocal();window.location.assign('/login')})};
  return <div className="space-y-6">{msg&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{msg}</div>}{err&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-600">{err}</div>}
    <section className="card p-6"><div className="flex items-center gap-3"><UserRound/><div><h1 className="text-2xl font-black">My Profile</h1><p className="text-sm text-slate-500">Manage your personal information securely.</p></div></div><form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="label">Full Name</span><input className="input" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></label><label><span className="label">Phone</span><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></label><label><span className="label">Current Email</span><input className="input bg-slate-50" value={q.data?.email||''} readOnly/></label><div className="md:col-span-2"><button disabled={busy} className="btn-primary"><Save size={17}/>Save Changes</button></div></form></section>
    <section className="card p-6"><div className="flex items-center gap-2"><Mail/><h2 className="text-lg font-black">Change Email</h2></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><input className="input" type="email" value={mail.email} onChange={e=>setMail({...mail,email:e.target.value})} placeholder="New email"/><button type="button" className="btn-secondary" onClick={requestEmail} disabled={busy}>Send Verification OTP</button></div>{mailStep===2&&<div className="mt-3 grid gap-3 md:grid-cols-[1fr_auto]"><input className="input" inputMode="numeric" maxLength={6} value={mail.otp} onChange={e=>setMail({...mail,otp:e.target.value.replace(/\D/g,'')})} placeholder="6-digit OTP"/><button type="button" className="btn-primary" onClick={verifyEmail} disabled={busy}>Verify & Update</button></div>}</section>
    <section className="card p-6"><div className="flex items-center gap-2"><KeyRound/><h2 className="text-lg font-black">Change Password</h2></div><p className="mt-1 text-sm text-slate-500">Your existing password is never displayed or stored in plain text.</p><form onSubmit={changePassword} className="mt-4 grid gap-4 md:grid-cols-2"><input className="input md:col-span-2" type="password" placeholder="Current password" value={pw.currentPassword} onChange={e=>setPw({...pw,currentPassword:e.target.value})} required/><input className="input" type="password" placeholder="New password" value={pw.newPassword} onChange={e=>setPw({...pw,newPassword:e.target.value})} minLength={8} required/><input className="input" type="password" placeholder="Confirm new password" value={pw.confirmPassword} onChange={e=>setPw({...pw,confirmPassword:e.target.value})} required/><button disabled={busy} className="btn-primary md:col-span-2 w-fit">Change Password</button></form></section>
    {!q.data?.phone_verified_at&&<VerifyPhone/>}
  </div>
}
