import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import { query, pool } from '../config/db.js';
import { uploadsRoot } from '../config/paths.js';

if (process.env.NODE_ENV === 'production' && process.env.ALLOW_DEMO_SEED !== '1') {
  throw new Error('Refusing to load development demo seed data in production. Set ALLOW_DEMO_SEED=1 only if you explicitly intend to do this.');
}

const adminHash = await bcrypt.hash('Admin@12345', 12);
const customerHash = await bcrypt.hash('Customer@12345', 12);
await query("INSERT INTO users(id,first_name,last_name,email,phone,password_hash,is_verified,is_active) VALUES(1,'System','Admin','admin@shasthocare.local','01700000001',?,1,1),(2,'Demo','Customer','customer@example.com','01700000002',?,1,1) ON DUPLICATE KEY UPDATE is_active=1", [adminHash, customerHash]);

const permissions = ['*', 'products.view', 'products.create', 'products.update', 'products.delete', 'orders.view', 'orders.update', 'prescriptions.view', 'prescriptions.review', 'inventory.view', 'inventory.adjust', 'customers.view', 'customers.update', 'reports.view', 'content.view', 'content.manage', 'marketing.view', 'marketing.manage', 'settings.manage', 'staff.manage', 'support.view', 'support.manage', 'finance.view', 'finance.manage', 'purchases.view', 'purchases.manage'];
for (let i = 0; i < permissions.length; i++)await query('INSERT INTO permissions(id,code,label) VALUES(?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label)', [i + 1, permissions[i], permissions[i] === '*' ? 'All permissions' : permissions[i].replaceAll('.', ' / ')]);
const roles = [['Super Admin', 'Complete control of the platform'], ['Admin', 'Daily store administration'], ['Pharmacist', 'Prescription review'], ['Inventory Manager', 'Products, stock, batches and suppliers'], ['Order Manager', 'Orders, returns and service bookings'], ['Content Manager', 'Website content, banners, services and marketing'], ['Support Agent', 'Customers and support messages']];
for (let i = 0; i < roles.length; i++)await query('INSERT INTO roles(id,name,description,is_active) VALUES(?,?,?,1) ON DUPLICATE KEY UPDATE description=VALUES(description),is_active=1', [i + 1, ...roles[i]]);
await query('INSERT IGNORE INTO user_roles(user_id,role_id) VALUES(1,1)');
const rolePerms = { 1: ['*'], 2: permissions.filter(x => x !== '*' && x !== 'staff.manage'), 3: ['prescriptions.view', 'prescriptions.review', 'orders.view', 'products.view', 'customers.view'], 4: ['products.view', 'products.create', 'products.update', 'inventory.view', 'inventory.adjust', 'purchases.view', 'purchases.manage', 'reports.view'], 5: ['orders.view', 'orders.update', 'finance.view', 'finance.manage', 'customers.view', 'reports.view'], 6: ['content.view', 'content.manage', 'marketing.view', 'marketing.manage', 'products.view'], 7: ['support.view', 'support.manage', 'customers.view', 'customers.update', 'orders.view'] };
for (const [rid, codes] of Object.entries(rolePerms)) { for (const code of codes) { const p = (await query('SELECT id FROM permissions WHERE code=?', [code]))[0]; if (p) await query('INSERT IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)', [rid, p.id]) } }

const cats = [
  ['Medicines', 'medicines', 'Pill', 'Everyday medicine catalog and pharmacy products.'], ['Vitamins & Supplements', 'vitamins-supplements', 'HeartPulse', 'Vitamins, minerals and nutritional supplements.'], ['Personal Care', 'personal-care', 'Sparkles', 'Daily hygiene and personal care essentials.'], ['Mother & Baby', 'mother-baby', 'Baby', 'Gentle baby and family care products.'], ['Medical Devices', 'medical-devices', 'Activity', 'Home monitoring and healthcare devices.'], ['First Aid', 'first-aid', 'Cross', 'First aid, wound care and basic medical supplies.'], ['Skin & Hair', 'skin-hair', 'Droplets', 'Skin, hair and dermatology-oriented care products.'], ['Nutrition', 'nutrition', 'Apple', 'Nutrition drinks and wellness foods.']
];
for (let i = 0; i < cats.length; i++)await query('INSERT INTO categories(id,name,slug,icon,description,sort_order,is_featured,is_active) VALUES(?,?,?,?,?,?,1,1) ON DUPLICATE KEY UPDATE name=VALUES(name),icon=VALUES(icon),description=VALUES(description),sort_order=VALUES(sort_order),is_active=1', [i + 1, cats[i][0], cats[i][1], cats[i][2], cats[i][3], i + 1]);
const brands = ['CarePlus', 'MediNova', 'Vitalis', 'PureDerm', 'BabyNest', 'HealthTrack', 'NutriWell', 'SafeAid', 'GlowCare', 'HomeMed'];
for (let i = 0; i < brands.length; i++)await query('INSERT INTO brands(id,name,slug,description,is_active) VALUES(?,?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),is_active=1', [i + 1, brands[i], brands[i].toLowerCase(), 'Demo healthcare brand for development and testing.']);
const manufacturers = ['Shastho Labs Ltd.', 'Wellness Formulations Ltd.', 'Nova Healthcare Ltd.', 'Care Devices Ltd.', 'Pure Essentials Ltd.'];
for (let i = 0; i < manufacturers.length; i++)await query('INSERT INTO manufacturers(id,name,slug,description,is_active) VALUES(?,?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),is_active=1', [i + 1, manufacturers[i], manufacturers[i].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), 'Demo manufacturer record used by the sample catalog.']);

const products = [
  { name: 'Paracetamol 500 mg Tablet', generic: 'Paracetamol', cat: 1, type: 'Medicine', form: 'Tablet', strength: '500 mg', pack: '10 tablets', ingredient: 'Paracetamol 500 mg per tablet.', desc: 'A common analgesic and antipyretic product listing used in this demo pharmacy catalog.', usage: 'Use only according to the package label or advice from a qualified healthcare professional.', warn: 'Do not exceed the labeled amount. Check other medicines for paracetamol/acetaminophen to avoid accidental duplication. Seek professional advice if you have liver disease or symptoms persist.', storage: 'Store below 30°C in a dry place, protected from direct light and out of reach of children.', rx: false, price: 25 },
  { name: 'Oral Rehydration Salts Sachet', generic: 'Oral rehydration salts', cat: 1, type: 'Medicine', form: 'Powder for oral solution', strength: 'WHO-style electrolyte blend', pack: '10 sachets', ingredient: 'Glucose and balanced electrolytes in a dry powder sachet.', desc: 'Electrolyte replacement product intended for preparation according to the pack instructions.', usage: 'Prepare exactly with the amount of safe drinking water stated on the product label. Follow professional guidance for children or persistent illness.', warn: 'Discard prepared solution according to the label. Seek medical care for severe dehydration, persistent vomiting, blood in stool, or concerning symptoms.', storage: 'Keep sachets sealed in a cool, dry place away from moisture.', rx: false, price: 120 },
  { name: 'Antacid Chewable Tablet', generic: 'Calcium carbonate blend', cat: 1, type: 'Medicine', form: 'Chewable tablet', strength: 'Demo strength', pack: '20 tablets', ingredient: 'Calcium carbonate-based antacid blend.', desc: 'Demo non-prescription antacid catalog item for short-term relief labeling.', usage: 'Follow the package directions. Separate from other medicines when advised because antacids can affect absorption.', warn: 'Frequent or persistent symptoms should be assessed by a healthcare professional. Review suitability in kidney disease or during pregnancy with a professional.', storage: 'Store in a dry place below 30°C with the container tightly closed.', rx: false, price: 95 },
  { name: 'Allergy Relief Tablet 10 mg', generic: 'Cetirizine hydrochloride', cat: 1, type: 'Medicine', form: 'Tablet', strength: '10 mg', pack: '10 tablets', ingredient: 'Cetirizine hydrochloride 10 mg per tablet.', desc: 'Antihistamine product listing for allergy-related symptoms; demo catalog information only.', usage: 'Use according to the product label or clinician advice.', warn: 'May cause drowsiness in some people. Avoid activities requiring alertness until you know how it affects you. Ask a professional about use with other sedating medicines.', storage: 'Store below 30°C, protected from moisture and light.', rx: false, price: 45 },
  { name: 'Prescription Antibiotic Demo 500 mg', generic: 'Demo antibiotic ingredient', cat: 1, type: 'Prescription Medicine', form: 'Capsule', strength: '500 mg', pack: '14 capsules', ingredient: 'Fictional demonstration antibiotic ingredient, 500 mg.', desc: 'A fictional prescription-only product included solely to demonstrate prescription approval and checkout controls.', usage: 'Prescription required. Use only when prescribed and follow the prescriber and dispensing label exactly.', warn: 'Do not self-start, share, or reuse antibiotics. This is fictional demo data and must not be used for treatment decisions.', storage: 'Store as directed by the dispensing label, away from children.', rx: true, price: 420 },
  { name: 'Vitamin C 1000 mg Effervescent', generic: 'Ascorbic acid', cat: 2, type: 'Supplement', form: 'Effervescent tablet', strength: '1000 mg', pack: '20 tablets', ingredient: 'Ascorbic acid with effervescent base.', desc: 'Vitamin C supplement in effervescent form.', usage: 'Use according to the supplement label and dietary needs advised by a qualified professional.', warn: 'Supplements do not replace a balanced diet. Ask a clinician about high-dose use if you have kidney problems or take regular medicines.', storage: 'Keep tube tightly closed in a cool, dry place away from moisture.', rx: false, price: 390 },
  { name: 'Vitamin D3 2000 IU Softgel', generic: 'Cholecalciferol', cat: 2, type: 'Supplement', form: 'Softgel', strength: '2000 IU', pack: '30 softgels', ingredient: 'Cholecalciferol (vitamin D3).', desc: 'Vitamin D3 dietary supplement product listing.', usage: 'Use only as directed on the label or by a healthcare professional, especially if combining with other vitamin D products.', warn: 'Avoid excessive vitamin D intake. People with high calcium levels, kidney disease, or related conditions should seek professional guidance.', storage: 'Store in a cool, dry place away from direct sunlight.', rx: false, price: 320 },
  { name: 'Calcium + Vitamin D3 Tablet', generic: 'Calcium carbonate + cholecalciferol', cat: 2, type: 'Supplement', form: 'Tablet', strength: 'Calcium/D3 blend', pack: '30 tablets', ingredient: 'Calcium carbonate with vitamin D3.', desc: 'Combined calcium and vitamin D supplement for general nutritional support.', usage: 'Take according to the product label or professional recommendation.', warn: 'Calcium can interact with some medicines. Seek advice if you use thyroid medicine, certain antibiotics, or have kidney stones or kidney disease.', storage: 'Keep in a cool, dry place with lid closed.', rx: false, price: 280 },
  { name: 'Omega-3 Fish Oil 1000 mg', generic: 'Fish oil concentrate', cat: 2, type: 'Supplement', form: 'Softgel', strength: '1000 mg', pack: '60 softgels', ingredient: 'Fish oil concentrate containing omega-3 fatty acids.', desc: 'Omega-3 nutritional supplement for general dietary support.', usage: 'Use according to the label with food if recommended by the manufacturer.', warn: 'Ask a healthcare professional before use if you take blood-thinning medicines, have a bleeding disorder, or have a fish allergy.', storage: 'Store tightly closed away from heat and direct light.', rx: false, price: 720 },
  { name: 'Zinc 20 mg Tablet', generic: 'Zinc', cat: 2, type: 'Supplement', form: 'Tablet', strength: '20 mg', pack: '30 tablets', ingredient: 'Zinc salt providing 20 mg elemental zinc per labeled serving.', desc: 'Zinc nutritional supplement product listing.', usage: 'Follow the supplement label. Long-term high-dose use should be discussed with a professional.', warn: 'Excess zinc may cause adverse effects and can affect copper status or interact with some medicines.', storage: 'Store below 30°C in a dry place.', rx: false, price: 210 },
  { name: 'Daily Multivitamin', generic: 'Multivitamin and mineral blend', cat: 2, type: 'Supplement', form: 'Tablet', strength: 'Multi-nutrient', pack: '30 tablets', ingredient: 'Blend of common vitamins and minerals as listed on the package.', desc: 'General multivitamin supplement for adults.', usage: 'Use according to the nutrition label and avoid unnecessarily combining with duplicate supplements.', warn: 'Not a substitute for a balanced diet. Discuss with a professional if pregnant, breastfeeding, or using long-term medicines.', storage: 'Keep sealed in a cool, dry place.', rx: false, price: 480 },
  { name: 'Gentle Skin Cleanser 250 ml', generic: 'Non-soap cleansing base', cat: 3, type: 'Personal Care', form: 'Liquid cleanser', strength: 'Fragrance-light formula', pack: '250 ml bottle', ingredient: 'Mild surfactant and moisturizing cleansing base.', desc: 'Gentle daily cleanser for face and body.', usage: 'Use externally as directed on the product label and rinse well.', warn: 'For external use only. Stop use if persistent irritation occurs and avoid direct eye contact.', storage: 'Store at room temperature with cap closed.', rx: false, price: 460 },
  { name: 'Alcohol Hand Sanitizer 200 ml', generic: 'Alcohol hand rub', cat: 3, type: 'Personal Care', form: 'Gel', strength: '70% alcohol demo label', pack: '200 ml bottle', ingredient: 'Alcohol-based hand cleansing gel with humectants.', desc: 'Portable hand hygiene product for use when soap and water are not readily available.', usage: 'Apply according to label instructions and allow hands to dry completely.', warn: 'Flammable. Keep away from flame, heat, eyes, and children. For external use only.', storage: 'Keep tightly closed away from heat and ignition sources.', rx: false, price: 160 },
  { name: 'Sensitive Toothpaste 100 g', generic: 'Desensitizing toothpaste', cat: 3, type: 'Personal Care', form: 'Paste', strength: 'Daily use formula', pack: '100 g tube', ingredient: 'Tooth-cleaning base with a desensitizing active ingredient as labeled.', desc: 'Toothpaste formulated for sensitive teeth and routine oral hygiene.', usage: 'Brush according to dental guidance and package directions.', warn: 'Do not swallow. Persistent tooth sensitivity or pain should be evaluated by a dental professional.', storage: 'Keep capped at room temperature.', rx: false, price: 195 },
  { name: 'Mild Body Wash 300 ml', generic: 'Gentle body cleansing base', cat: 3, type: 'Personal Care', form: 'Liquid', strength: 'Mild formula', pack: '300 ml bottle', ingredient: 'Mild cleansing agents and skin-conditioning ingredients.', desc: 'Daily body wash for gentle cleansing.', usage: 'Apply externally and rinse thoroughly.', warn: 'Avoid eye contact. Discontinue if irritation persists.', storage: 'Store at room temperature away from direct sunlight.', rx: false, price: 310 },
  { name: 'Baby Moisturizing Lotion 200 ml', generic: 'Baby emollient lotion', cat: 4, type: 'Baby Care', form: 'Lotion', strength: 'Gentle formula', pack: '200 ml bottle', ingredient: 'Emollient and moisturizing base formulated for delicate skin.', desc: 'Gentle moisturizer designed for baby skin care.', usage: 'Apply externally as directed. Patch test when using a new skin product if advised.', warn: 'Avoid broken skin and eyes. Stop use if irritation or rash develops and seek advice if needed.', storage: 'Keep closed at room temperature and away from direct heat.', rx: false, price: 360 },
  { name: 'Baby Shampoo 200 ml', generic: 'Mild baby shampoo base', cat: 4, type: 'Baby Care', form: 'Liquid shampoo', strength: 'Tear-minimized formula', pack: '200 ml bottle', ingredient: 'Mild cleansing surfactants formulated for baby hair.', desc: 'Gentle shampoo for routine baby hair cleansing.', usage: 'Use a small amount externally and rinse thoroughly according to the label.', warn: 'Adult supervision required. Avoid direct eye contact despite gentle formulation.', storage: 'Store upright with cap closed.', rx: false, price: 290 },
  { name: 'Baby Diapers Medium 32 pcs', generic: 'Disposable absorbent diaper', cat: 4, type: 'Baby Care', form: 'Disposable diaper', strength: 'Medium', pack: '32 pieces', ingredient: 'Absorbent core, soft inner layer, elastic side panels.', desc: 'Disposable baby diapers with absorbent core and soft fit.', usage: 'Change regularly and select the correct size for the child.', warn: 'Stop use if persistent skin irritation develops. Keep packaging away from children.', storage: 'Store clean and dry away from humidity.', rx: false, price: 780 },
  { name: 'Digital Blood Pressure Monitor', generic: 'Automatic upper-arm BP monitor', cat: 5, type: 'Medical Device', form: 'Device', strength: 'Digital', pack: '1 device + cuff', ingredient: 'Electronic monitor, reusable upper-arm cuff and accessories.', desc: 'Home blood pressure monitor with automatic inflation and digital display.', usage: 'Follow the device manual for cuff placement, posture, rest period, and repeated measurements. Home readings do not replace professional assessment.', warn: 'Seek urgent care for concerning symptoms regardless of a device reading. Use the correct cuff size and keep the device calibrated as instructed.', storage: 'Store dry, clean and protected from impact and extreme temperature.', rx: false, price: 3450 },
  { name: 'Digital Glucose Meter Kit', generic: 'Blood glucose monitoring system', cat: 5, type: 'Medical Device', form: 'Device', strength: 'Digital', pack: 'Meter + starter accessories', ingredient: 'Electronic meter with compatible test-strip system.', desc: 'Home glucose meter kit for self-monitoring when directed by a healthcare professional.', usage: 'Use only with compatible strips and follow the device manual. Treatment changes should be made only with qualified medical guidance.', warn: 'Unexpected or very abnormal readings should be confirmed and discussed with a healthcare professional; seek urgent care for severe symptoms.', storage: 'Keep meter and strips dry and within the temperature range stated in the manual.', rx: false, price: 1850 },
  { name: 'Pulse Oximeter', generic: 'Fingertip pulse oximeter', cat: 5, type: 'Medical Device', form: 'Device', strength: 'SpO2/PR display', pack: '1 device', ingredient: 'Optical fingertip sensor and digital display.', desc: 'Portable fingertip pulse oximeter for spot measurements.', usage: 'Use according to the manual, keeping the hand warm and still for a stable reading.', warn: 'Readings can be affected by motion, poor circulation, nail products, skin temperature and device limitations. Symptoms matter more than a single reading.', storage: 'Store dry and remove batteries for long storage when recommended.', rx: false, price: 1650 },
  { name: 'Digital Thermometer', generic: 'Digital clinical thermometer', cat: 5, type: 'Medical Device', form: 'Device', strength: 'Digital', pack: '1 thermometer', ingredient: 'Electronic temperature sensor and display.', desc: 'Reusable digital thermometer for routine temperature measurement.', usage: 'Follow the manual for the selected measurement site and cleaning procedure.', warn: 'Do not rely on temperature alone to judge illness severity. Seek professional care for concerning symptoms or high-risk patients.', storage: 'Keep clean, dry and protected from impact.', rx: false, price: 420 },
  { name: 'Nebulizer Machine', generic: 'Compressor nebulizer', cat: 5, type: 'Medical Device', form: 'Device', strength: 'Home compressor', pack: 'Machine + mask/tubing kit', ingredient: 'Compressor unit with medication cup, tubing and masks.', desc: 'Home compressor nebulizer device for medications prescribed or recommended for nebulization.', usage: 'Use only with medicines or saline intended for nebulization and follow the device and prescription instructions.', warn: 'Do not put oils or unapproved liquids in the nebulizer. Clean parts carefully to reduce contamination risk.', storage: 'Store clean and dry with tubing and accessories protected from contamination.', rx: false, price: 2950 },
  { name: 'First Aid Kit 24 Pieces', generic: 'Basic first aid supplies', cat: 6, type: 'First Aid', form: 'Kit', strength: '24-piece', pack: '1 kit', ingredient: 'Assorted plasters, gauze, tape, wipes, gloves and basic accessories.', desc: 'Compact first aid kit for minor cuts, scrapes and common household needs.', usage: 'Use individual components according to their labels and replace used or expired items.', warn: 'Serious bleeding, deep wounds, burns, bites or signs of infection require medical attention.', storage: 'Keep the case clean, dry and accessible to responsible adults.', rx: false, price: 650 },
  { name: 'Sterile Gauze Pads 10 pcs', generic: 'Sterile cotton gauze', cat: 6, type: 'First Aid', form: 'Dressing', strength: '10 cm x 10 cm', pack: '10 sterile pads', ingredient: 'Sterile woven gauze pads.', desc: 'Individually packed sterile gauze for wound dressing.', usage: 'Use clean technique and follow first-aid or clinician guidance for wound care.', warn: 'Do not use if the sterile pack is damaged. Seek medical attention for deep, heavily contaminated or infected wounds.', storage: 'Keep unopened packs clean and dry.', rx: false, price: 140 },
  { name: 'Elastic Crepe Bandage', generic: 'Elastic support bandage', cat: 6, type: 'First Aid', form: 'Bandage', strength: '10 cm width', pack: '1 roll', ingredient: 'Stretch cotton-blend support bandage.', desc: 'Reusable elastic bandage for general support and first aid.', usage: 'Wrap with comfortable support; avoid excessive tightness.', warn: 'Loosen immediately if there is numbness, worsening pain, discoloration or swelling below the bandage.', storage: 'Wash and store according to the label, dry before reuse.', rx: false, price: 180 },
  { name: 'Antiseptic Solution 100 ml', generic: 'Topical antiseptic solution', cat: 6, type: 'First Aid', form: 'Solution', strength: 'Demo topical formula', pack: '100 ml bottle', ingredient: 'Topical antiseptic active ingredient in a liquid base as labeled.', desc: 'External antiseptic product for minor first-aid use according to the label.', usage: 'Use externally only and follow dilution/application directions on the specific product label.', warn: 'Avoid eyes, mouth and large/deep wounds unless professionally directed. Stop use if significant irritation occurs.', storage: 'Keep closed, upright and away from direct heat or light.', rx: false, price: 130 },
  { name: 'SPF 50 Broad Spectrum Sunscreen', generic: 'Broad-spectrum sunscreen', cat: 7, type: 'Skin Care', form: 'Cream', strength: 'SPF 50', pack: '50 g tube', ingredient: 'Broad-spectrum UV filters in a moisturizing cream base.', desc: 'High-SPF sunscreen product for routine sun protection.', usage: 'Apply according to the label before sun exposure and reapply as directed, especially after sweating or washing.', warn: 'For external use. Sunscreen is one part of sun protection; clothing and shade are also important.', storage: 'Store below 30°C away from direct sunlight.', rx: false, price: 620 },
  { name: 'Moisturizing Cream 100 g', generic: 'Emollient moisturizer', cat: 7, type: 'Skin Care', form: 'Cream', strength: 'Barrier-support formula', pack: '100 g jar', ingredient: 'Emollients, humectants and occlusive moisturizing ingredients.', desc: 'Daily moisturizer for dry or normal skin.', usage: 'Apply externally to clean skin as needed according to the label.', warn: 'Avoid known allergens and discontinue if persistent irritation occurs.', storage: 'Keep container closed at room temperature.', rx: false, price: 430 },
  { name: 'Acne Care Face Wash 100 ml', generic: 'Cleansing face wash', cat: 7, type: 'Skin Care', form: 'Gel cleanser', strength: 'Oil-control formula', pack: '100 ml tube', ingredient: 'Cleansing base with an acne-care active ingredient as labeled.', desc: 'Face cleanser formulated for oily or acne-prone skin.', usage: 'Use externally according to the label. Avoid over-cleansing irritated skin.', warn: 'Avoid eyes and broken skin. Persistent or severe acne may need assessment by a healthcare professional.', storage: 'Store at room temperature with cap closed.', rx: false, price: 350 },
  { name: 'Hair Nutrition Serum 60 ml', generic: 'Cosmetic hair serum', cat: 7, type: 'Hair Care', form: 'Serum', strength: 'Leave-in formula', pack: '60 ml bottle', ingredient: 'Cosmetic conditioning oils, silicones and vitamins as labeled.', desc: 'Leave-in cosmetic serum for hair conditioning and shine.', usage: 'Use on hair as directed on the label.', warn: 'External use only. Avoid contact with eyes and discontinue if scalp irritation occurs.', storage: 'Keep capped away from heat and direct sunlight.', rx: false, price: 490 },
  { name: 'Nutrition Drink Vanilla 400 g', generic: 'Balanced nutrition powder', cat: 8, type: 'Nutrition', form: 'Powder', strength: 'Vanilla', pack: '400 g tin', ingredient: 'Protein, carbohydrate, fats, vitamins and minerals according to the nutrition label.', desc: 'Powdered nutrition drink for general dietary supplementation.', usage: 'Prepare with safe water according to the label. Individual nutrition needs vary.', warn: 'Not suitable as a sole source of nutrition unless specifically formulated and professionally recommended. Check allergens and sugar content.', storage: 'Keep tin tightly closed in a cool, dry place and use within the period stated after opening.', rx: false, price: 980 },
  { name: 'Protein Nutrition Powder 500 g', generic: 'Protein blend', cat: 8, type: 'Nutrition', form: 'Powder', strength: 'Chocolate', pack: '500 g pouch', ingredient: 'Milk/plant protein blend with flavoring and micronutrients as labeled.', desc: 'Supplemental protein powder for general nutritional use.', usage: 'Use according to the nutrition label and overall dietary requirements.', warn: 'Check milk/soy/nut allergen information. People with kidney disease or medical dietary restrictions should seek professional advice.', storage: 'Seal pouch after opening and store cool and dry.', rx: false, price: 1250 },
  { name: 'Electrolyte Drink Powder', generic: 'Electrolyte beverage mix', cat: 8, type: 'Nutrition', form: 'Powder sachet', strength: 'Lemon flavor', pack: '10 sachets', ingredient: 'Carbohydrate and electrolyte beverage blend.', desc: 'Flavored electrolyte beverage mix for general hydration support.', usage: 'Mix with the amount of water stated on the label.', warn: 'People who must restrict sugar, sodium or potassium should check the label and seek professional advice if needed.', storage: 'Keep sachets sealed and dry.', rx: false, price: 260 },
  { name: 'Iron + Folic Acid Tablet', generic: 'Iron + folic acid', cat: 2, type: 'Supplement', form: 'Tablet', strength: 'Nutritional blend', pack: '30 tablets', ingredient: 'Iron salt with folic acid.', desc: 'Iron and folic acid supplement product listing.', usage: 'Use according to the package label or professional recommendation.', warn: 'Keep iron supplements out of reach of children. Excess iron can be harmful. Ask a professional about use in pregnancy or with chronic conditions.', storage: 'Store dry below 30°C and away from children.', rx: false, price: 240 },
  { name: 'Probiotic Capsules', generic: 'Probiotic culture blend', cat: 2, type: 'Supplement', form: 'Capsule', strength: 'Multi-strain blend', pack: '20 capsules', ingredient: 'Selected probiotic cultures with capsule excipients.', desc: 'Probiotic dietary supplement for general digestive wellness labeling.', usage: 'Follow label storage and use directions because probiotic products vary by strain and formulation.', warn: 'People who are severely immunocompromised or critically ill should seek medical advice before probiotic use.', storage: 'Store according to the package; some products may require cool storage.', rx: false, price: 550 },
  { name: 'Saline Nasal Spray 30 ml', generic: 'Isotonic saline', cat: 1, type: 'Healthcare Product', form: 'Nasal spray', strength: 'Isotonic', pack: '30 ml bottle', ingredient: 'Sterile isotonic saline solution.', desc: 'Non-medicated saline spray for nasal moisture and rinsing.', usage: 'Use according to the label and keep nozzle clean.', warn: 'Do not share the bottle. Seek medical advice for persistent symptoms or after nasal injury/surgery unless already directed.', storage: 'Store capped at room temperature.', rx: false, price: 220 },
  { name: 'Lubricating Eye Drops 10 ml', generic: 'Ophthalmic lubricant', cat: 1, type: 'Healthcare Product', form: 'Eye drops', strength: 'Lubricant formula', pack: '10 ml bottle', ingredient: 'Ophthalmic lubricating ingredients in sterile solution.', desc: 'Lubricating eye drops for temporary dry-eye comfort according to the product label.', usage: 'Use only as labeled and avoid touching the dropper tip to the eye or surfaces.', warn: 'Stop use and seek advice for significant eye pain, injury, discharge, sudden vision change or persistent redness.', storage: 'Store as indicated on the pack and discard after the stated period following opening.', rx: false, price: 310 },
  { name: 'Pain Relief Gel 30 g', generic: 'Topical analgesic gel', cat: 6, type: 'Topical Product', form: 'Gel', strength: 'External use', pack: '30 g tube', ingredient: 'Topical pain-relief active ingredients as listed on the label.', desc: 'External gel product for temporary relief labeling.', usage: 'Apply externally only according to the package directions.', warn: 'Do not use on broken skin or near eyes. Review suitability with a professional if pregnant, allergic to anti-inflammatory medicines, or using similar products.', storage: 'Keep tube closed and away from heat.', rx: false, price: 190 },
  { name: 'Hot Water Bag 2 L', generic: 'Reusable hot water bag', cat: 6, type: 'First Aid', form: 'Reusable device', strength: '2 litre', pack: '1 bag', ingredient: 'Heat-resistant rubber/PVC bag with stopper.', desc: 'Reusable hot water bag for non-medicated warm comfort.', usage: 'Follow product instructions, use water at a safe temperature, and wrap the bag to avoid direct skin burns.', warn: 'Never use boiling water. Check for leaks and avoid prolonged direct contact, especially in children, older adults or people with reduced sensation.', storage: 'Drain, dry and store away from sunlight and sharp objects.', rx: false, price: 450 },
  { name: 'Glucose Test Strips 50 pcs', generic: 'Compatible glucose test strips', cat: 5, type: 'Medical Device', form: 'Test strip', strength: 'Device-specific', pack: '50 strips', ingredient: 'Electrochemical test strips for a compatible glucose meter.', desc: 'Single-use strips for the compatible glucose monitoring system.', usage: 'Use only with the matching meter and follow storage, coding/calibration and sampling instructions.', warn: 'Expired, wet, damaged or incompatible strips can give unreliable results. Do not change treatment based solely on unexpected readings without professional advice.', storage: 'Keep tightly closed in original container and within labeled temperature/humidity limits.', rx: false, price: 950 }
];

const uploadDir = path.join(uploadsRoot, 'products'); fs.mkdirSync(uploadDir, { recursive: true });
function svgFor(name, i) { const hue = (i * 37) % 360; return `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="hsl(${hue} 70% 96%)"/><stop offset="1" stop-color="hsl(${(hue + 40) % 360} 70% 88%)"/></linearGradient></defs><rect width="800" height="800" rx="72" fill="url(#g)"/><rect x="230" y="145" width="340" height="500" rx="42" fill="white" opacity=".97"/><rect x="260" y="205" width="280" height="42" rx="21" fill="hsl(${hue} 55% 42%)"/><circle cx="400" cy="360" r="94" fill="hsl(${hue} 70% 94%)"/><path d="M400 305v110M345 360h110" stroke="hsl(${hue} 55% 42%)" stroke-width="25" stroke-linecap="round"/><text x="400" y="520" text-anchor="middle" font-family="Arial" font-size="28" font-weight="700" fill="#17324d">${name.replace(/[<&]/g, '').slice(0, 28)}</text><text x="400" y="565" text-anchor="middle" font-family="Arial" font-size="18" fill="#64748b">ShasthoCare Demo</text></svg>` }

for (let i = 0; i < products.length; i++) {
  const p = products[i], id = i + 1, slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), brand = (i % brands.length) + 1, manufacturer = (i % manufacturers.length) + 1, regular = p.price + Math.max(20, Math.round(p.price * .12)), sale = p.price;
  await query(`INSERT INTO products(id,name,slug,sku,generic_name,brand_id,manufacturer_id,category_id,product_type,dosage_form,strength,pack_size,short_description,description,ingredients,usage_info,warnings,storage_info,regular_price,sale_price,cost_price,tax_rate,prescription_required,is_featured,is_best_seller,is_new_arrival,is_active,low_stock_threshold,rating_avg,review_count,seo_title,seo_description) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),slug=VALUES(slug),generic_name=VALUES(generic_name),brand_id=VALUES(brand_id),manufacturer_id=VALUES(manufacturer_id),category_id=VALUES(category_id),product_type=VALUES(product_type),dosage_form=VALUES(dosage_form),strength=VALUES(strength),pack_size=VALUES(pack_size),short_description=VALUES(short_description),description=VALUES(description),ingredients=VALUES(ingredients),usage_info=VALUES(usage_info),warnings=VALUES(warnings),storage_info=VALUES(storage_info),regular_price=VALUES(regular_price),sale_price=VALUES(sale_price),cost_price=VALUES(cost_price),prescription_required=VALUES(prescription_required),is_featured=VALUES(is_featured),is_best_seller=VALUES(is_best_seller),is_new_arrival=VALUES(is_new_arrival),is_active=1,seo_title=VALUES(seo_title),seo_description=VALUES(seo_description)`, [
    id, p.name, slug, 'DEMO' + String(id).padStart(4, '0'), p.generic, brand, manufacturer, p.cat, p.type, p.form, p.strength, p.pack, `<p>${p.desc}</p>`, `<p>${p.desc}</p><p><strong>Demo catalog note:</strong> Product information is for ecommerce demonstration and does not replace medical advice or the actual pack label.</p>`, `<p>${p.ingredient}</p>`, `<p>${p.usage}</p>`, `<p>${p.warn}</p>`, `<p>${p.storage}</p>`, regular, sale, Math.round(sale * .68), 0, p.rx ? 1 : 0, i < 12 ? 1 : 0, i < 10 ? 1 : 0, i >= 28 ? 1 : 0, 1, 10, +(4.2 + (i % 7) * 0.1).toFixed(2), 18 + i, `${p.name} | ShasthoCare`, `${p.name} demo product listing with brand, pack, pricing and safety information.`
  ]);
  const batchId = id; await query('INSERT INTO inventory_batches(id,product_id,batch_number,manufacturing_date,expiry_date,purchase_price,selling_price,quantity,remaining_quantity) VALUES(?,?,?,DATE_SUB(CURDATE(),INTERVAL 4 MONTH),DATE_ADD(CURDATE(),INTERVAL ? MONTH),?,?,?) ON DUPLICATE KEY UPDATE expiry_date=VALUES(expiry_date),purchase_price=VALUES(purchase_price),selling_price=VALUES(selling_price)', [batchId, id, 'DEMO-BATCH-' + String(id).padStart(3, '0'), 12 + (i % 18), Math.round(sale * .68), sale, 60 + (i % 25), 60 + (i % 25)]);
  const catalogImage = fs.readdirSync(uploadDir).find(file => file.toLowerCase().endsWith(`-${slug}.png`));
  const fn = catalogImage && fs.existsSync(path.join(uploadDir,catalogImage)) ? catalogImage : `demo-product-${String(id).padStart(2, '0')}.svg`, fp = path.join(uploadDir, fn); if (!fs.existsSync(fp)) fs.writeFileSync(fp, svgFor(p.name, i));
  const imageUrl = `/uploads/products/${fn}`;
  const exists = (await query('SELECT id FROM product_images WHERE product_id=? LIMIT 1', [id]))[0];
  if (!exists) await query('INSERT INTO product_images(product_id,image_url,alt_text,is_primary,sort_order) VALUES(?,?,?,?,?)', [id, imageUrl, p.name, 1, 0]);
  else await query('UPDATE product_images SET image_url=?,alt_text=?,is_primary=1,sort_order=0 WHERE product_id=?', [imageUrl, p.name, id]);
}

await query("INSERT INTO coupons(id,code,name,description,discount_type,value,minimum_order,maximum_discount,start_date,end_date,usage_limit,usage_per_user,is_active) VALUES(1,'WELCOME10','Welcome 10%','<p>10% discount for eligible demo orders.</p>','percentage',10,500,200,DATE_SUB(NOW(),INTERVAL 1 DAY),DATE_ADD(NOW(),INTERVAL 365 DAY),1000,1,1) ON DUPLICATE KEY UPDATE end_date=VALUES(end_date),is_active=1");
const services = [['Doctor Consultation', 'doctor-consultation', '<p>Request an online consultation booking with a qualified clinician.</p>', 'Stethoscope', 500], ['Lab Tests at Home', 'lab-tests-at-home', '<p>Book a home sample collection request for available lab services.</p>', 'FlaskConical', 350], ['Medicine Reminder', 'medicine-reminder', '<p>Create a neutral reminder for medicines you already use.</p>', 'Bell', 0], ['Full Body Checkup', 'full-body-checkup', '<p>Explore configurable preventive health check packages.</p>', 'ClipboardCheck', 2500], ['Pharmacist Support', 'pharmacist-support', '<p>Ask non-diagnostic questions about orders, labels and prescription workflow.</p>', 'MessageCircle', 0]];
for (let i = 0; i < services.length; i++)await query('INSERT INTO services(id,name,slug,description,icon,price,sort_order,is_active) VALUES(?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE description=VALUES(description),icon=VALUES(icon),price=VALUES(price),sort_order=VALUES(sort_order),is_active=1', [i + 1, ...services[i], i + 1]);

await query("INSERT INTO banners(id,title,subtitle,content,button_text,button_url,position,sort_order,is_active) VALUES(1,'Better Health, Delivered Daily.','<p>Genuine healthcare products, trusted service and convenient delivery from one modern storefront.</p>','<p><strong>Easy ordering.</strong> Secure prescription handling. Flexible delivery options.</p>','Shop Medicines','/products','hero',1,1) ON DUPLICATE KEY UPDATE title=VALUES(title),subtitle=VALUES(subtitle),content=VALUES(content),is_active=1");
await query("INSERT INTO banners(id,title,subtitle,content,button_text,button_url,position,sort_order,is_active) VALUES(2,'Prescription upload & pharmacist review','<p>Upload a prescription securely and track its review status from your account.</p>','<p>Private files are served only through authenticated endpoints.</p>','Upload Prescription','/account/prescriptions','prescription',1,1) ON DUPLICATE KEY UPDATE title=VALUES(title),subtitle=VALUES(subtitle),content=VALUES(content),button_text=VALUES(button_text),button_url=VALUES(button_url),position=VALUES(position),is_active=1");
const sections = [['hero', '', 1], ['trust', 'Why customers choose us', 2], ['categories', 'Shop by Category', 3], ['best_sellers', 'Best Sellers', 4], ['prescription', 'Prescription Delivery', 5], ['services', 'Healthcare Services', 6], ['featured', 'Featured Products', 7], ['brands', 'Featured Brands', 8], ['new_arrivals', 'New Arrivals', 9], ['newsletter', 'Stay in the loop', 10]];
for (const [key, title, order] of sections) await query('INSERT INTO homepage_sections(section_key,title,is_enabled,sort_order) VALUES(?,?,1,?) ON DUPLICATE KEY UPDATE title=VALUES(title),sort_order=VALUES(sort_order)', [key, title, order]);

const settings = {
  'brand.name': 'ShasthoCare', 'brand.tagline': 'Care. Delivered. Always.', 'brand.logo': '', 'brand.favicon': '', 'theme.active': 'clinical-teal', 'admin.panel_slug': 'control-center', 'currency': 'BDT', 'currency.symbol': '৳', 'shipping.default_fee': '80', 'shipping.free_threshold': '1500', 'payment.cod': '1', 'payment.bkash': '1', 'payment.nagad': '1', 'payment.rocket': '1', 'payment.sslcommerz': '1', 'payment.bkash.number': '01700000000', 'payment.bkash.instructions': '<p>Send the exact order total using <strong>Send Money</strong> to the number shown above. Then enter the sender last 4 digits or transaction ID at checkout.</p>', 'payment.nagad.number': '01800000000', 'payment.nagad.instructions': '<p>Send the exact order total to the number shown above. Then enter the sender last 4 digits or transaction ID at checkout.</p>', 'contact.email': 'support@shasthocare.local', 'contact.phone': '+880 1700-000000', 'contact.address': 'Dhaka, Bangladesh', 'contact.hours': 'Every day, 8:00 AM – 11:00 PM', 'footer.about': 'A modern pharmacy and healthcare marketplace with configurable content, catalog, orders and prescription workflow.', 'footer.copyright': '© 2026 ShasthoCare. All rights reserved.', 'social.facebook': '#', 'social.instagram': '#', 'social.youtube': '#', 'social.linkedin': '#', 'announcement.enabled': '1', 'announcement.text': 'Free delivery on eligible orders over ৳1,500', 'header.search_placeholder': 'Search medicines, healthcare products...', 'home.hero_badge': 'Your Health, Our Priority', 'home.hero_note': '100% genuine products • Secure checkout • Professional support',
  'home.trust_1_title': 'Express Delivery', 'home.trust_1_text': 'Reliable delivery updates', 'home.trust_2_title': 'Secure Payments', 'home.trust_2_text': 'Protected checkout', 'home.trust_3_title': 'Easy Returns', 'home.trust_3_text': 'Policy-based support', 'home.trust_4_title': 'Customer Support', 'home.trust_4_text': 'Help when you need it'
};
for (const [k, v] of Object.entries(settings)) await query('INSERT INTO store_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=IF(setting_value IS NULL OR setting_value="",VALUES(setting_value),setting_value)', [k, v]);

const pages = [
  ['about', 'About ShasthoCare', '<h2>Healthcare shopping made simpler</h2><p>ShasthoCare is a configurable demo pharmacy and healthcare ecommerce platform. This project demonstrates product discovery, secure accounts, prescription workflows, inventory, orders and administration.</p>'],
  ['contact', 'Contact Us', '<h2>We are here to help</h2><p>Use the contact form or the support information shown in the footer. Store contact details can be changed from Admin → Settings.</p>'],
  ['faq', 'Frequently Asked Questions', '<h2>Orders</h2><p>Track orders from your account or the public tracking page.</p><h2>Prescription items</h2><p>Prescription-required products need an approved prescription before fulfillment.</p>'],
  ['privacy-policy', 'Privacy Policy', '<p>This demo page can be fully edited from Admin → Content → Pages.</p>'],
  ['terms', 'Terms & Conditions', '<p>Demo terms. Replace with legally reviewed terms before production use.</p>'],
  ['shipping-policy', 'Shipping Policy', '<p>Shipping zones, fees and free-shipping thresholds are configurable from the admin panel.</p>'],
  ['return-policy', 'Return Policy', '<p>Returns are processed according to store policy and product eligibility. Replace this demo copy before production.</p>'],
  ['refund-policy', 'Refund Policy', '<p>Refund handling can be managed from the admin order and returns modules.</p>'],
  ['medicine-disclaimer', 'Medicine Disclaimer', '<p>Medicine information on this website is for product and catalog information only and does not replace professional medical advice, diagnosis, treatment, or the official product label.</p>']
];
for (const [slug, title, content] of pages) await query('INSERT INTO cms_pages(slug,title,content,seo_title,seo_description,is_active) VALUES(?,?,?,?,?,1) ON DUPLICATE KEY UPDATE title=VALUES(title),content=VALUES(content),is_active=1', [slug, title, content, title, `Read ${title} for ShasthoCare.`]);

await query("INSERT INTO shipping_zones(id,name,division,district,fee,estimated_days,free_shipping_threshold,is_active,sort_order) VALUES(1,'Inside Dhaka','Dhaka','Dhaka',80,'1-2 business days',1500,1,1),(2,'Outside Dhaka',NULL,NULL,130,'2-4 business days',2500,1,2) ON DUPLICATE KEY UPDATE fee=VALUES(fee),estimated_days=VALUES(estimated_days),is_active=1");
await query("INSERT INTO suppliers(id,name,company,phone,email,address,notes,is_active) VALUES(1,'Demo Supplier','Health Distribution Ltd.','01800000000','supplier@example.com','Dhaka, Bangladesh','Demo supplier record for inventory batches.',1) ON DUPLICATE KEY UPDATE is_active=1");


// Admin-controlled navigation. These rows drive the public header/footer and can be edited from Content -> Navigation.
const navItems = [
  [1, 'Home', '/', 'header', null, 0, 1, 1],
  [2, 'Medicines', '/products?category=medicines', 'header', null, 0, 2, 1],
  [3, 'Vitamins & Supplements', '/products?category=vitamins-supplements', 'header', null, 0, 3, 1],
  [4, 'Personal Care', '/products?category=personal-care', 'header', null, 0, 4, 1],
  [5, 'Mother & Baby', '/products?category=mother-baby', 'header', null, 0, 5, 1],
  [6, 'Medical Devices', '/products?category=medical-devices', 'header', null, 0, 6, 1],
  [7, 'Offers', '/products?sort=price_asc', 'header', null, 0, 7, 1],
  [20, 'About', '/page/about', 'footer_company', null, 0, 1, 1],
  [21, 'Contact', '/page/contact', 'footer_company', null, 0, 2, 1],
  [22, 'Privacy Policy', '/page/privacy-policy', 'footer_company', null, 0, 3, 1],
  [30, 'Medicines', '/products?category=medicines', 'footer_shop', null, 0, 1, 1],
  [31, 'Vitamins & Supplements', '/products?category=vitamins-supplements', 'footer_shop', null, 0, 2, 1],
  [32, 'Personal Care', '/products?category=personal-care', 'footer_shop', null, 0, 3, 1],
  [40, 'FAQ', '/page/faq', 'footer_help', null, 0, 1, 1],
  [41, 'Track Order', '/track', 'footer_help', null, 0, 2, 1],
  [42, 'Shipping', '/page/shipping-policy', 'footer_help', null, 0, 3, 1],
  [43, 'Returns', '/page/return-policy', 'footer_help', null, 0, 4, 1],
  [50, 'Terms & Conditions', '/page/terms', 'footer_legal', null, 0, 1, 1],
  [51, 'Refund Policy', '/page/refund-policy', 'footer_legal', null, 0, 2, 1],
  [52, 'Medicine Disclaimer', '/page/medicine-disclaimer', 'footer_legal', null, 0, 3, 1]
];
for (const x of navItems) await query('INSERT INTO navigation_items(id,label,url,location,parent_id,open_new_tab,sort_order,is_active) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),url=VALUES(url),location=VALUES(location),sort_order=VALUES(sort_order)', x);

// Apply the requested default 20% medicine discount and derive unit/strip/box pricing where values are missing.
await query(`UPDATE products SET discount_percent=20, sale_price=ROUND(regular_price*0.80,2), unit_label=COALESCE(NULLIF(unit_label,''),'Tablet'), unit_price=CASE WHEN unit_price IS NULL OR unit_price=0 THEN ROUND((regular_price*0.80)/GREATEST(1,COALESCE(units_per_strip,10)),2) ELSE unit_price END, units_per_strip=CASE WHEN units_per_strip IS NULL OR units_per_strip<1 THEN 10 ELSE units_per_strip END, strip_price=CASE WHEN strip_price IS NULL OR strip_price=0 THEN ROUND(regular_price*0.80,2) ELSE strip_price END, strips_per_box=CASE WHEN strips_per_box IS NULL OR strips_per_box<1 THEN 10 ELSE strips_per_box END, units_per_box=CASE WHEN units_per_box IS NULL OR units_per_box<1 THEN GREATEST(1,COALESCE(units_per_strip,10))*10 ELSE units_per_box END, box_price=CASE WHEN box_price IS NULL OR box_price=0 THEN ROUND((regular_price*0.80)*10*0.95,2) ELSE box_price END WHERE LOWER(COALESCE(product_type,'medicine')) LIKE '%medicine%'`);

// Populate operational modules so the admin dashboard is useful immediately after seeding.
const demoOrders = [
  [1, 'ORD-20260911-000101', 1240, 100, 80, 1220, 'cod', 'pending', 'processing', 'Sundarban Courier', 'SC-DEMO-101'],
  [2, 'ORD-20260911-000102', 850, 0, 80, 930, 'bkash', 'paid', 'shipped', 'Pathao Courier', 'PT-DEMO-102'],
  [3, 'ORD-20260911-000103', 560, 50, 80, 590, 'nagad', 'paid', 'delivered', 'RedX', 'RX-DEMO-103'],
  [4, 'ORD-20260911-000104', 1750, 150, 0, 1600, 'cod', 'pending', 'prescription_review', 'Steadfast', 'SF-DEMO-104'],
  [5, 'ORD-20260911-000105', 430, 0, 80, 510, 'rocket', 'paid', 'confirmed', 'Paperfly', 'PF-DEMO-105']
];
for (const [id, no, subtotal, discount, shipping, total, paymentMethod, paymentStatus, status, courier, tracking] of demoOrders) {
  await query('INSERT INTO orders(id,user_id,order_number,subtotal,discount,shipping_fee,total,payment_method,payment_status,status,address_json,admin_note,tracking_code,courier_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE subtotal=VALUES(subtotal),discount=VALUES(discount),shipping_fee=VALUES(shipping_fee),total=VALUES(total),payment_method=VALUES(payment_method),payment_status=VALUES(payment_status),status=VALUES(status),tracking_code=VALUES(tracking_code),courier_name=VALUES(courier_name)', [id, 2, no, subtotal, discount, shipping, total, paymentMethod, paymentStatus, status, JSON.stringify({ fullName: 'Demo Customer', phone: '01700000002', division: 'Dhaka', district: 'Dhaka', area: 'Dhanmondi', addressLine: 'Demo Road 12, Dhaka' }), 'Seeded demo order', tracking, courier]);
}
const orderItems = [[1, 1, 1, 2], [2, 2, 6, 1], [3, 3, 16, 1], [4, 4, 5, 1], [5, 5, 20, 1]];
for (const [id, orderId, productId, qty] of orderItems) { const p = (await query('SELECT name,sku,sale_price FROM products WHERE id=?', [productId]))[0]; const img = (await query('SELECT image_url FROM product_images WHERE product_id=? ORDER BY is_primary DESC,id LIMIT 1', [productId]))[0]; if (p) await query('INSERT INTO order_items(id,order_id,product_id,product_name,sku,image_url,unit_price,discount,quantity,subtotal) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE product_name=VALUES(product_name),unit_price=VALUES(unit_price),quantity=VALUES(quantity),subtotal=VALUES(subtotal)', [id, orderId, productId, p.name, p.sku, img?.image_url || '', p.sale_price, 0, qty, Number(p.sale_price) * qty]); }
for (const [id, no, subtotal, discount, shipping, total, paymentMethod, paymentStatus, status] of demoOrders) { await query('INSERT INTO payments(id,order_id,provider,transaction_ref,amount,status,payload_json) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE amount=VALUES(amount),status=VALUES(status)', [id, id, paymentMethod, `DEMO-TXN-${id}`, total, paymentStatus, JSON.stringify({ mode: 'seed-demo' })]); await query('INSERT INTO order_status_history(order_id,status,note,changed_by) SELECT ?,?,?,1 WHERE NOT EXISTS(SELECT 1 FROM order_status_history WHERE order_id=? AND status=?)', [id, status, 'Seeded status for admin demonstration', id, status]); }
const privateDir = path.join(uploadsRoot, 'private', 'prescriptions'); fs.mkdirSync(privateDir, { recursive: true }); const demoRxPath = path.join(privateDir, 'demo-prescription.svg'); if (!fs.existsSync(demoRxPath)) fs.writeFileSync(demoRxPath, `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200"><rect width="100%" height="100%" fill="white"/><text x="70" y="100" font-family="Arial" font-size="38" font-weight="700">Demo Prescription</text><text x="70" y="160" font-family="Arial" font-size="22">Training / development data only — not a real prescription.</text><line x1="70" y1="210" x2="830" y2="210" stroke="#0f9d91" stroke-width="4"/><text x="70" y="285" font-family="Arial" font-size="26">Patient: Demo Customer</text><text x="70" y="340" font-family="Arial" font-size="26">Purpose: demonstrate pharmacist review workflow</text><text x="70" y="420" font-family="Arial" font-size="24">No clinical instructions are contained in this sample.</text></svg>`);
await query("INSERT INTO prescriptions(id,user_id,doctor_name,clinic_name,prescription_date,notes,file_path,status,admin_notes) VALUES(1,2,'Demo Clinician','Demo Clinic',CURDATE(),'Development-only sample prescription','uploads/private/prescriptions/demo-prescription.svg','under_review','') ON DUPLICATE KEY UPDATE status=IF(status='uploaded','under_review',status)");
await query("INSERT INTO reviews(id,user_id,product_id,rating,title,review,status,verified_purchase) VALUES(1,2,1,5,'Easy ordering','Demo review for the seeded catalog.','approved',1),(2,2,6,4,'Good demo item','Sample review visible in admin moderation.','pending',1) ON DUPLICATE KEY UPDATE rating=VALUES(rating),status=VALUES(status)");
await query("INSERT INTO returns(id,order_id,user_id,reason,comments,status,admin_note,refund_amount) VALUES(1,3,2,'Damaged','Demo return request for admin workflow.','requested','',590) ON DUPLICATE KEY UPDATE status=status");
await query("INSERT INTO service_bookings(id,user_id,service_id,booking_date,booking_time,contact_phone,notes,status) VALUES(1,2,1,DATE_ADD(CURDATE(),INTERVAL 2 DAY),'10:30:00','01700000002','Demo consultation booking','pending') ON DUPLICATE KEY UPDATE status=status");
await query("INSERT INTO newsletter_subscribers(id,email,is_active) VALUES(1,'demo.subscriber@example.com',1) ON DUPLICATE KEY UPDATE is_active=1");
await query("INSERT INTO contact_messages(id,name,email,phone,subject,message,status) VALUES(1,'Demo Customer','customer@example.com','01700000002','Order support','This is a seeded support message for the admin inbox.','new') ON DUPLICATE KEY UPDATE status=status");
await query("INSERT INTO purchase_orders(id,po_number,supplier_id,status,expected_date,subtotal,notes,created_by) VALUES(1,'PO-20260911-001',1,'ordered',DATE_ADD(CURDATE(),INTERVAL 7 DAY),6800,'Seeded purchase order for procurement demo',1) ON DUPLICATE KEY UPDATE status=status");
await query("INSERT INTO purchase_order_items(id,purchase_order_id,product_id,quantity,received_quantity,purchase_price,batch_number,expiry_date) VALUES(1,1,1,100,0,12,'PO-DEMO-001',DATE_ADD(CURDATE(),INTERVAL 18 MONTH)),(2,1,6,40,0,140,'PO-DEMO-002',DATE_ADD(CURDATE(),INTERVAL 20 MONTH)) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity)");
await query("UPDATE products p SET rating_avg=COALESCE((SELECT AVG(r.rating) FROM reviews r WHERE r.product_id=p.id AND r.status='approved'),p.rating_avg),review_count=COALESCE((SELECT COUNT(*) FROM reviews r WHERE r.product_id=p.id AND r.status='approved'),p.review_count) WHERE p.id IN (1,6)");

console.log(`Seed complete: ${products.length} detailed demo products, admin data and website content.`);
await pool.end();
